### ISSUE TITLE
Create a "How to Present the Turing Way" Guide

### ISSUE THREAD

**Issue by sgibson91** [the-turing-way/the-turing-way#114]
Create a guide/template/checklist to outline the procedures for presenting the Turing Way at conferences.

--- 

Update, @KirstieJane brain dumping - please add!

* Most importantly: we would LOVE people to give talks about the project!
* We'd like to know who's giving talks so we can collect them together
* Who to credit
* How to describe the project - are there set sentences
* Who do you need to ask (Kirstie at the moment!) Does she need to review? How much time turn around?
* Is there funding available?
* How are those decisions made?

**Comment by pherterich** [comment]
Would this include some standard slides on the project we would expect to show up in every talk? Or should they be a separate issue?

**Comment by KirstieJane** [comment]
@pherterich - I think that could be a separate issue....but a very good one ✅

**Comment by pherterich** [comment]
I feel we have this covered but it's not actually written down anywhere. I'm not sure where the best place is to document this, ways of working or contributing guidelines or just document in the project management folder? Opinions?

**Comment by sgibson91** [comment]
I'd say contributing guidelines, as presenting is a contribution to the Turing Way community and then they'd have to open a PR to add the slides to the repo anyway. It should maybe include how to add them to Zenodo too?

**Comment by HeidiSeibold** [comment]
Since this has been open for such a long time I tried to add something to the contributing guidelines. 

It is just a first idea/suggestion how I would do it but feel free to reject or change completely :wink: 
Just let me know what you think #1223 

CC @malvikasharan @KirstieJane

**Comment by EstherPlomp** [comment]
Hi from the Reviewer/editor-wg! 

I think this is now covered via the trainer/mentor WG? @aldenc, could you please check and close the issue if this is indeed now covered, or alternatively - add it to the catch all issue #2936 if action is still needed?

**Comment by aleesteele** [comment]
Closing this for now, as I believe this was covered in the "presenting about the Turing Way" chapter in the community handbook!: https://the-turing-way.netlify.app/community-handbook/presenting
