### ISSUE TITLE
Collect community persona and impact

### ISSUE THREAD

**Issue by malvikasharan** [the-turing-way/the-turing-way#1181]
### Summary

* Add persona of community members

* Currently 3 contributors have been invited to add their persona (Camila, Tony and Heidi) #1106 
  * They will review the format that works best and will help restructure a standard way to collect persona
* Will invite more members who can be highlighted for their efforts

### List of changes proposed in this PR (pull-request)

* Added a new folder to collect personas: "community-members"

### What should a reviewer concentrate their feedback on?

- [ ] If this structure can be enhanced
- [ ] Everything looks ok?

### Who can help?

* Anyone who has been previously been involved and would like to continue being involved through a subproject that they can lead and would need more visibility for getting people helping them.

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by malvikasharan** [comment]
Define the purpose of the file clearly, and discuss what is the impact of their work and what had been the impact of them working with The Turing Way?

**Comment by malvikasharan** [comment]
TODO: create an issue template for persona with the following possible structure:

1. Provide a clear purpose for inviting contribution of this file:
2. Please provide a short Bio. You are welcome to highlight your other involvement in improving accessibility in Data Science or relevant projects:
3. How did you get involved in The Turing Way and what motivated you to work on your current contributions?
4. What impact _The Turing Way_ has had on you, your work, or your network? [SMART criteria: **S**pecific, **M**easurable, **A**chievable, **R**elevant, and **T**ime-bound. ](https://en.wikipedia.org/wiki/SMART_criteria) to frame your answers.
5. What impact you would like to create with your work in _The Turing Way_? Please use the [SMART criteria: **S**pecific, **M**easurable, **A**chievable, **R**elevant, and **T**ime-bound. ](https://en.wikipedia.org/wiki/SMART_criteria) to frame your answers.

**Comment by EstherPlomp** [comment]
@malvikasharan: is this something that should be picked up or should we close this issue? 

(I think this is now covered in the contributor.md right?)

**Comment by aleesteele** [comment]
Hi @EstherPlomp and @malvikasharan - will close this for now, as we do have personas covered in the contributor.md file!
