### ISSUE TITLE
Chapter idea: How to visualise your work

### ISSUE THREAD

**Issue by KirstieJane** [the-turing-way/the-turing-way#122]
### Detailed description
 - There are two projects lead by Turing Fellows that focus on how to best visualise your data
 - Writing chapters about these topics in detail is probably outside of the scope of The Turing Way BUT a chapter that links out to specific visualisation tools or methods will be very valuable.
 - The goal is to explain WHY showing your working (how you made your optimisation decisions etc) is important for reproducible data science.

**Comment by Ismael-KG** [comment]
Just found this neat issue - I went to a talk yesterday where the data vis was **stunning** and thought it deserves a chapter in TTW! Shall we revive this issue, @KirstieJane @malvikasharan? 😄

**Comment by KirstieJane** [comment]
Yes! That would be fabulous - please do!

There's also huge scope here for using Binder as part of the Jupyter Book.

Here's a note book that I've always meant to incorporate as a chapter.... I wish I had some time!

GitHub Repo: https://github.com/KirstieJane/NH19-Visualization/tree/master

Binder: https://mybinder.org/v2/gh/KirstieJane/NH19-Visualization/master?urlpath=lab

Not exactly what you were thinking of, but hopefully useful!

Anyone with time to integrate is very welcome to work on this task

**Comment by AidaMehonic** [comment]
There are some work packages across ASG projects with a significant data visualisation component. 
Some of them are even thinking about creating tooling for data vis in their own domains. 

So I am keen to be contribute to writing this chapter as I help ASG teams think through data vis tooling options.

**Comment by KirstieJane** [comment]
@rolyp who is working on the WAYS project might be interested too... I know Greg was keen back in the day (maybe @Arielle-Bennett can get in touch?)

**Comment by Ismael-KG** [comment]
Would love to arrange a call on this. I am thinking this might deserve chapters in different books, although that might be confusing! Some thoughts to write about:

1. The need for good data vis for science communication (this could live in the [Guide for Communication](https://the-turing-way.netlify.app/communication/communication.html))
2. The need to compile vis methods used for their replication (@KirstieJane linked to [this](https://github.com/KirstieJane/NH19-Visualization/tree/master) a [few comments above](https://github.com/alan-turing-institute/the-turing-way/issues/122#issuecomment-819501259) and it is SUPERB) -- I think this is great for the [Guide for reproducible research](https://the-turing-way.netlify.app/reproducible-research/reproducible-research.html).
3. Tools and methods for different data visualisations (may very well be covered by *(2)*).
4. The importance of data vis as a way to convey values and emotion that are just as important to science as "objective facts" (see what the authors of [*Data Feminism*](https://mitpress.mit.edu/books/data-feminism) shared [when speaking at The Alan Turing Institute](https://www.turing.ac.uk/blog/challenging-power-data-science)).

I welcome (_encourage_) thoughts on these thoughts!

**Comment by reshamas** [comment]
### Resources
- upset graphs (from the Turing Way Book Dash presentation):  https://upset.app/
- annotating visualizations in python plotly (BLOG + VIDEO):  https://medium.com/nerd-for-tech/enriching-data-visualizations-with-annotations-in-plotly-using-python-6127ff6e0f80
- (VIDEO: animations using python plotly):  https://youtu.be/kMFvpmOaF2I

**Comment by EstherPlomp** [comment]
Fixed by #3214
