### ISSUE TITLE
[BUG] Markdown header levels need to be corrected (28 PRs for HacktoberFest participants)

### ISSUE THREAD

**Issue by BrainonSilicon** [the-turing-way/the-turing-way#1321]
## :tada::balloon::cake: **Welcome Hacktober Contributors! This is The Turing Way repository** :cake::balloon::tada:

:dizzy::hatched_chick::sunny: _We're excited that you're here and want to contribute._ :sunny::hatched_chick::dizzy:

### About Hacktober and The Turing Way
Hacktober is a month long celebration of Open Source Projects where the goal is to make 4 Pull Requests during the month.

#### A bit about Git
If you’re new to git then here are [some instructions](https://help.github.com/articles/signing-up-for-a-new-github-account/) to help you get going. Remember that you can ask us any questions you need to along the way.

A [Pull Request](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request) (what Hacktober is measured on) lets you tell others about changes you've pushed to a branch in a repository on GitHub. Once a pull request is opened, you can discuss and review the potential changes with collaborators and add follow-up commits before your changes are merged into the base branch.

Under the Issues listed in our Hacktober tag, we’ve outlined what needs to be done, and how you can go about addressing it. Once the Issue has been addresses, you can submit a Pull Request for review (tell us what you’ve done) and we can incorporate it into The Turing Way.

We’ve also created this special Hacktoberfest tag to make is easy for you to find places to contribute if you’re new.

In the spirit of Hacktoberfest, please only do a few of these to submit your PR so that we can learn and grow as a community together.

#### Our Community
Please read our core Contributors document and our Code of Conduct while you engage in The Turing Way. We want to ensure that every user and contributor feels welcome, included and supported to participate in The Turing Way community.

In addition, for Hacktober we would also like to recognise the work that you are doing. If you would like to be featured on our [Twitter](https://twitter.com/turingway?s=20) Hacktoberfest series then: 
- Add your twitter handle to the comments when you submit your PR, 
- What brings you to Open Source, Hacktoberfest, and/or The Turing Way,
- and anything else you’d like to celebrate about your contribution!

We welcome all contributions to this project via GitHub issues and pull requests. Please follow these guidelines to make sure your contributions can be easily integrated into the projects. As you start contributing to The Turing Way, don't forget that your ideas are more important than perfect pull requests. ❤️

If you have any questions that aren't discussed below, please let us know through one of the many ways to get in touch.

# Summary of Issue

There are non-consecutive header levels (eg. level 0 to 2, or 1 to 3). Below are listed the current places where this occurs. 

When the issue lists "Non-consecutive header level increase; 0 to 2", it expects headers to follow `#` (a level 0 header), `##` (a level 1 header), `###` (a level 2 header) sequence. So we would love contributors to change the headers to follow (header 0, header 1, header 2, and so on).   

#### What needs to be done
Please select 1-2 of these to fix, open a separate issue, make a PR with the fixed headers, and enjoy your Hacktober! 

**Note:** if there are multiple instances then it means that there are multiple headers that need to be fixed within that book. 

#### List of Non-consecutive header levels to be fixed 
- [x]  Non-consecutive header level increase; 0 to 2 https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/community-handbook/acknowledgement/acknowledgement-examples.md
- [x]  Non-consecutive header level increase; 1 to 3 https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/community-handbook/coc/coc-enforcement.md
- [x]  Non-consecutive header level increase; 1 to 3 https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/community-handbook/style.md
- [x]  Non-consecutive header level increase; 1 to 3 https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/community-handbook/style.md
- [x]  Non-consecutive header level increase; 1 to 3 https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/community-handbook/style.md
- [x]  Non-consecutive header level increase; 1 to 3 https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/community-handbook/style.md
- [x]  Non-consecutive header level increase; 0 to 3 https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/community-handbook/style/style-citing.md
- [x]  Non-consecutive header level increase; 0 to 3 https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/community-handbook/style/style-crossref.md
- [x]  Non-consecutive header level increase; 0 to 3 https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/community-handbook/style/style-crossref.md
- [x]  Non-consecutive header level increase; 0 to 3 https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/community-handbook/style/style-crossref.md
- [x]  Non-consecutive header level increase; 0 to 3 https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/community-handbook/style/style-crossref.md
- [x]  Non-consecutive header level increase; 0 to 3 https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/figures/_figure-list.md
- [x]  Non-consecutive header level increase; 0 to 2 https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/reproducible-research/open/open-access.md
- [x]  Non-consecutive header level increase; 0 to 2 https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/reproducible-research/open/open-data.md
- [x]  Non-consecutive header level increase; 0 to 2 https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/reproducible-research/open/open-hardware.md
- [x]  Non-consecutive header level increase; 0 to 2 https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/reproducible-research/open/open-notebooks.md
- [x]  Non-consecutive header level increase; 0 to 2 https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/reproducible-research/open/open-resources.md
- [x]  Non-consecutive header level increase; 0 to 2 https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/reproducible-research/open/open-resources.md
- [x]  Non-consecutive header level increase; 0 to 2 https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/reproducible-research/open/open-resources.md
- [x]  Non-consecutive header level increase; 0 to 2 https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/reproducible-research/open/open-resources.md
- [x]  Non-consecutive header level increase; 0 to 2 https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/reproducible-research/open/open-resources.md
- [x]  Non-consecutive header level increase; 0 to 2 https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/reproducible-research/open/open-resources.md
- [x]  Non-consecutive header level increase; 0 to 2 https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/reproducible-research/open/open-scholarship.md
- [x]  Non-consecutive header level increase; 0 to 2 https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/reproducible-research/open/open-source.md
- [x]  Non-consecutive header level increase; 0 to 2 https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/reproducible-research/rdm/rdm-resources.md
- [x]  Non-consecutive header level increase; 0 to 2 https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/reproducible-research/rdm/rdm-resources.md
- [x]  Non-consecutive header level increase; 0 to 2 https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/reproducible-research/rdm/rdm-resources.md
- [x]  Non-consecutive header level increase; 0 to 2 https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/reproducible-research/rdm/rdm-resources.md

#### Who can help?
Anyone who would like to participate in Hacktoberfest or contribute to The Turing Way GitHub repository for the first time easier to do locally (by git) but not mandatory

**Comment by KirstieJane** [comment]
Hi @BrainonSilicon! I'm just having a look at this issue with @MariaEriksson and I'm a little confused 😬 

I'm looking at the first example in the list above:

> Non-consecutive header level increase; 0 to 2 https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/community-handbook/acknowledgement/acknowledgement-examples.md

In that file the first line is: `## Different Contributions and their Acknowledgements`

and then the next header down is `### Bug fixing`

Is the activity to move the first one to just one `#` (a level 0 header) and the second to `##` (a level 1 header)? I think I got a bit lost with the "0 to 2" part of the bullet point above. 

Thank you for your help!

**Comment by BrainonSilicon** [comment]
> Hi @BrainonSilicon! I'm just having a look at this issue with @MariaEriksson and I'm a little confused 😬
> 
> I'm looking at the first example in the list above:
> 
> > Non-consecutive header level increase; 0 to 2 https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/community-handbook/acknowledgement/acknowledgement-examples.md
> 
> In that file the first line is: `## Different Contributions and their Acknowledgements`
> 
> and then the next header down is `### Bug fixing`
> 
> Is the activity to move the first one to just one `#` (a level 0 header) and the second to `##` (a level 1 header)? I think I got a bit lost with the "0 to 2" part of the bullet point above.
> 
> Thank you for your help!

Hi @KirstieJane. Thank you for clarifying - I'll update the issue so that it's clearer. 

I believe that the bug came from expecting a  `#`  (level 0) first, followed by a `##` (level 1). 

Does that make it clearer?

**Comment by MariaEriksson** [comment]
Hey @BrainonSilicon! Thanks for explaining :pray: I'd love to try to make these changes - I'm just still very new to GitHub, so could I please double check that I've understood how to do this? For instance, for the example

> Non-consecutive header level increase; 0 to 2 https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/community-handbook/acknowledgement/acknowledgement-examples.md

would I open this example on its own, select `Edit this file`, make the change, and then `Commit the changes`(which would create a new pull request)? Or would I tick several examples, and then select `New Issue`? I got a bit confused by the instructions 😬

**Comment by BrainonSilicon** [comment]
No worries! We worked out separating out this issue into smaller ones (see the [new issue 1398](https://github.com/alan-turing-institute/the-turing-way/issues/1398) here for a further explanation). 

You were spot on with your first comment! 

What to do is: 
- choose which bugs you want to fix (from the list) 
- follow the link to the file 
- find the corresponding bug 
- select `Edit this file`
- then `Commit the Changes` with a comment. This is done on "your" branch. 
- you will then have a screen titled `Open Pull Request` where you can write more about what you've done 
- there is then a `Pull Request` button which officially makes your Pull Request 
- we can then review your changes, check any conflicts, and give feedback 

Let me know if that is clear, there are community coworking hours tomorrow and I would be happy to walk through with you or comment further (and a massive thank you for contributing to The Turing Way!!)

**Comment by malvikasharan** [comment]
I have created a dedicated issue for each file with header issues. Hoping that making it modular will attract newer contributors.

**Comment by MariaEriksson** [comment]
Thanks again @BrainonSilicon! I've given the two first issues a try - hopefully, they look ok! And if they do, I'll do more 👍 If I do do more, I assume I should open the 'dedicated issues' that you have created @malvikasharan, instead of opening the issues listed on this page? And does this mean that I should re-do the issues I did, now that they have become 'dedicated issues'?
