### ISSUE TITLE
Consider working from branches of forks

### ISSUE THREAD

**Issue by bsipocz** [the-turing-way/the-turing-way#1488]
### Summary

There are currently 100 branches in the main repository. Most of these were branches for pull requests, thus contain no extra information compared to the main master branch. 
When someone newly forks the project, all these branches also ends up on the fork, as well as when one works with the main account as a remote.

### What needs to be done?

I would suggest considering to declutter, remove the branches that are no longer relevant. Their content will remain in the git history. I think this would provide a cleaner and smoother experience for all contributors (while I admit it would create a bit of a nuisance for those with write access and editing using the github interface, as that would create a new branch in the main repo rather than on their fork.

### Who can help?

* repo maintainers

---

**Comment by EstherPlomp** [comment]
Hi @bsipocz! Is this still relevant right now and/or being discussed by the maintainer WG? Should we keep this issue open or close it? Thanks (from the editors/reviewers WG :))

**Comment by bsipocz** [comment]
Not sure where this should/could be discussed, or who should discuss and decide on it.

**Comment by aleesteele** [comment]
Flagging this for the #2690 – as this is relevant for the working group.

**Comment by JimMadge** [comment]
Closing as superseded by #3871
