### ISSUE TITLE
Why no custom web domain?

### ISSUE THREAD

**Issue by da5nsy** [the-turing-way/the-turing-way#1962]
### Summary

_Apologies if this is not the right forum for this discussion - will happily be redirected._

I was wondering if there was a reason that the project uses the 'netlify.app' domain rather than a custom name? For a relatively small expenditure (I'm not selling domain names I swear) I personally think there would be a considerable increase in 'polish' and associated trustworthiness.

### What needs to be done?

Auto-response suggestions:
- There is a good reason to not do this. It is...
- Hmm maybe we should do that. How can we make money move from one place to another place to make that a possibility, and then how do we implement that change without cataclysmically breaking everything?
- Other

### Who can help?

* Probably needs input from @KirstieJane and/or @malvikasharan

**Comment by malvikasharan** [comment]
Hey @da5nsy. This has been discussed with early developers and @KirstieJane but not documented in The Turing Way. The decision to stick with 'netlify' link is to actively show that we build on an Open Source project, a practice we want to promote.

We have also visited the idea of having a separate website for The Turing Way. I think this will be something we will need to revisit in the future as the increasing amount of resource within The Turing Way might be better managed via a website - however, for now, we have put a pin on that discussion to avoid pointing people to different webpages when most information exists in the book.
@KirstieJane will be able to add more context to it - and then this issue should be summarised and added to the book.

There are issues open to record history of the book and put them to a Foreword of the book - something I would like to work on in next months.

**Comment by da5nsy** [comment]
Thanks for the info @malvikasharan! 

> There are issues open to record history of the book and put them to a Foreword of the book - something I would like to work on in next months.

Sounds great. This is something I'm bumping into while trying to update the landing page too (see latest commit on #1961), so I'll try to catch up on what the plan is.

**Comment by aleesteele** [comment]
One thing I will add here is that custom domain names improve SEO search (noted in issue #2416), and the findability of _The Turing Way_ as a resource more broadly.

**Comment by sgibson91** [comment]
I think there are other ways we can promote the tool that hosts the book with without having to keep the domain name they give us. Probably somewhere in the Community Handbook volume.

**Comment by RaoOfPhysics** [comment]
Perhaps, to address the issue of flagging the open-source tools upon which TTW is built, we could have a colophon of sorts in the book with links to all the open tooling being used? (I checked rather hastily if such a thing existed but couldn’t find something that fit the description…)

**Comment by aleesteele** [comment]
_Connecting this to #1962_

**Comment by da5nsy** [comment]
Resolved in #3266
