### ISSUE TITLE
[BUG] Netlify previews showing zero-to-binder page

### ISSUE THREAD

**Issue by da5nsy** [the-turing-way/the-turing-way#2308]
### Description

Recent pull request builds have been defaulting to the 'zero-to-binder' page. For example, see: https://github.com/alan-turing-institute/the-turing-way/pull/2307#issuecomment-1079477854

This seems to have happened on every pull request since the start of February.

Tagging @sgibson91 because they seem to know about Netlify things, and also they were working on that page at the start of February 🧐😅

**Comment by sgibson91** [comment]
> Tagging @sgibson91 because they seem to know about Netlify things

I will take a look but I would generally like to dispel this myth. Netlify is a black box to me and I'm beginning to think it's more trouble than it's worth 😅

**Comment by sgibson91** [comment]
This is the only thing I changed relating to Netlify back when I was working on the Binder chapter: https://github.com/alan-turing-institute/the-turing-way/pull/2222

As you can see from my main PR, only the TOC was updated: https://github.com/alan-turing-institute/the-turing-way/pull/1850/files

**Comment by sgibson91** [comment]
I sent a tweet out to Netlify Support because I can't see anything in the repo config or the app config that would cause this https://twitter.com/drsarahlgibson/status/1507679521453092869

**Comment by sgibson91** [comment]
You get the right link (the homepage) from the build on Netlify's site, but it seems not when it comments? https://app.netlify.com/teams/turingway/builds/623e3d0ad2fd5c0008c11297

**Comment by da5nsy** [comment]
> and I'm beginning to think it's more trouble than it's worth

It's super valuable to me - I'm a little embarrassed to say that I've never built the book locally (I should really pluck up the courage, and find the time, to give that a go! 😅) and so I rely very heavily on the Netlify previews

**Comment by sgibson91** [comment]
I agree, the deploy previews _are_ valuable. But if there were another site generator that provided that feature, I'd be lobbying for that over Netlify. Because Netlify's usability in the app _sucks_.

**Comment by da5nsy** [comment]
Aha I understand now

**Comment by da5nsy** [comment]
Discussed on Twitter: https://twitter.com/NetlifySupport/status/1508081294965567493
Posted on Netlify forum: https://answers.netlify.com/t/deploy-preview-directs-to-specific-but-seemingly-arbitrary-page/54077

**Comment by da5nsy** [comment]
Update from Netlify:

https://answers.netlify.com/t/deploy-preview-directs-to-specific-but-seemingly-arbitrary-page/54077/4?u=da5nsy

Summary, they think it's a problem on our end, and that ".../zero-to-binder seems to be changing with every build" 🤔 
Any ideas why that might be @sgibson91?

**Comment by sgibson91** [comment]
Not a clue. Its just a Markdown file?

**Comment by da5nsy** [comment]
https://github.com/alan-turing-institute/the-turing-way/runs/8076310462

**Comment by da5nsy** [comment]
AHA!
I found a smoking gun:

https://github.com/alan-turing-institute/the-turing-way/pull/2312/files#diff-6929ad37ca28b88d7745b68956df5533614c0a481be0facecbb28498a90603ce

_Putting this here for reference but I don't have time to actually look into this right now. Will come back to it if I get a chance._

**Comment by sgibson91** [comment]
So the `_build/html` folder should not be being committed to the repo _at all_... Part of what Netlify automates is generating that folder by running `jupyter-book build .`

**Comment by sgibson91** [comment]
Also, props @da5nsy for sticking with this!! :rocket:

**Comment by da5nsy** [comment]
I suspect what is happening is that Netlify internally looks at the new version of `_build` (that it has just generated) and compares it to the previous version it has, and looks to see what has changed, and then uses that to generate the link. In most cases this would be a reasonable way to estimate the page that the user is most interested in seeing previewed.

**Comment by da5nsy** [comment]
Rebuilding from scratch, without any changes, there are 36 lines that are modified:
<img width="769" alt="Untitled" src="https://user-images.githubusercontent.com/3739866/206017392-c0dd1c1f-5b0d-4e72-9a3b-ad199687b5b2.png">
All of this type.

**Comment by da5nsy** [comment]
It looks like this would resolve following https://github.com/executablebooks/sphinx-design/pull/91 , which was [included in sphinx-design=0.3.0](https://github.com/executablebooks/sphinx-design/releases/tag/v0.3.0). That in turn [looks like it will be included in Jupyter Book soon](https://github.com/executablebooks/jupyter-book/pull/1842) but for now is causing me conflicts if I try to use it.

Current use:
```
Collecting sphinx-design~=0.1.0
  Downloading sphinx_design-0.1.0-py3-none-any.whl (1.9 MB)
```

**Comment by sgibson91** [comment]
Here's the conflict message:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
jupyter-book 0.13.0 requires sphinx-design~=0.1.0, but you have sphinx-design 0.3.0 which is incompatible.
```

I also tried upgrading jupyter book to the latest released version (which is only 0.13.1 tbf) and there is still a requirement on sphinx-design~=0.1.0 there. So I believe we may need to wait for the release of jupyter book with sphinx-design==0.3.0 before we are able to squash this bug.

**Comment by da5nsy** [comment]
I am of the same opinion.

**Comment by da5nsy** [comment]
We might be able to squash this ourselves by modifying the `Execution settings` in the config file.
Either by setting `execute_notebooks` to cache, or adding zero-to-binder to `exclude_patterns`.
Bit hacky though.
I have not tested.

**Comment by sgibson91** [comment]
Do we still see this bug btw?

**Comment by sgibson91** [comment]
I looked at a couple of new PRs and I don't think we're getting specific pages in deploy preview links any more - so I'm going to close this one out

**Comment by da5nsy** [comment]
> I looked at a couple of new PRs and I don't think we're getting specific pages in deploy preview links any more - so I'm going to close this one out

Yeah I'm not sure why we don't get specific page links anymore, and I think that is a little bit of a shame but also not too bad.
It does resolve this specific issue at least! haha
