### ISSUE TITLE
Section on Ethical software licences

### ISSUE THREAD

**Issue by eirini-zormpa** [the-turing-way/the-turing-way#2595]
### Summary
I couldn't find any information on [Ethical licences](https://ethicalsource.dev/licenses/) either in the [Software licences](https://the-turing-way.netlify.app/reproducible-research/licensing/licensing-software.html) chapter of the Guide for Reproducible Research or in the Guide for Ethical Research.

Ethical licences are still very new but the idea is to create ways to license open source software for uses that further social good and human rights (or don't work against them).

I think a short section mentioning that these licences exist could be added in the Software licences section of the Reproducibility guide or there could be a longer chapter in the Ethics guide.

### What needs to be done?

- [ ] Decide if this is a useful addition
- [ ] If yes, how long should it be - i.e. should it go in the Reproducibility or Ethics guide?
- [ ] Write content
- [ ] Get feedback
- [ ] Incorporate feedback

### Who can help?

Not sure?

---

### Updates

No updates yet!

**Comment by malvikasharan** [comment]
@eirini-zormpa I did not know about Ethical license. I thank you for sharing. I think this will be a good fit for the Guide for Ethical Research, with link into the License chapter for software and data. Happy to help review and edit this chapter.

I think @dingaaling can include the links to the license the Big Data workshop/huggingface have developed to also provide access to LLM data in an ethical way. I think that will fit in this chapter - but will let Jen comment on that.

**Comment by aleesteele** [comment]
Hi @eirini-zormpa! So glad to see this upcoming chapter, what an interesting topic. 

Adding a few resources here based on our conversation, as I think I forgot to link them:
- https://firstdonoharm.dev/ - this 'do no harm' approach to ethical licensing is really interesting, and something that i've followed for a little while.
- https://stackoverflow.blog/2022/08/08/can-you-stop-your-open-source-project-from-being-used-for-evil/ - the discussed article about the downstream effects of software
- https://hackernoon.com/6-myths-about-ethical-open-source-licenses-3bfbd042b1dc 

I would also encourage you to post in a slack channel about it, in case other folks are interested in joining in as well. I know folks would be keen to join in.

**Comment by aleesteele** [comment]
@all-contributors please add @eirini-zormpa for ideas

**Comment by dingaaling** [comment]
@eirini-zormpa thank you for opening this! I was hoping to co-write on this subject with a lawyer from HuggingFace who's helped develop this responsible AI license for the BLOOM LLM https://www.licenses.ai/blog/2022/8/18/naming-convention-of-responsible-ai-licenses

Looking forward to discussing further

**Comment by eirini-zormpa** [comment]
shall we work on this at the next Collab Cafe?

**Comment by dingaaling** [comment]
@eirini-zormpa yes! i have invited the HF rep to that Collab Cafe so that is perfect

**Comment by aleesteele** [comment]
Hey @eirini-zormpa and @dingaaling! This looks great! Added a tag for Book Dash - and wondering if you both want to turn this into a pull request this Book Dash!

**Comment by dingaaling** [comment]
@cassgvp has suggested Dylan Roskams-Edris: https://upstream.force11.org/opening-new-paths-to-technology-transfer/.

**Comment by tomichec** [comment]
I don't agree that the so-called "Ethical Licenses" can solve the problem and add do add many others. We must insist on Free/Libre Software. Please read the article refereed below, which states many points why it is not a good idea. Here one of them:

> If we accepted programs with usage restrictions as part of a free operating system such as GNU, people would come up with lots of different usage restrictions. There would be programs banned for use in meat processing, programs banned only for pigs, programs banned only for cows, and programs limited to kosher foods. Someone who hates spinach might license a program to allow use for processing any vegetable except spinach, while a Popeye fan's program might allow only use for spinach. There would be music programs allowed only for rap music, and others allowed only for classical music.
>
> The result would be a system that you could not count on for any purpose. For each task you wish to do, you'd have to check lots of licenses to see which parts of your system are off limits for that task. Not only for the components you explicitly use, but also for the hundreds of components that they link with, invoke, or communicate with.

https://www.gnu.org/philosophy/programs-must-not-limit-freedom-to-run.html
