### ISSUE TITLE
Add a ways of working document

### ISSUE THREAD

**Issue by annakrystalli** [the-turing-way/the-turing-way#26]
To detail the levels of involvement of official members so that expectations of their time are reasonable.

---

### Update

This should be closed soon - requires #74 to close

Outstanding things to add
- [x] comms, see #74 
- [ ] cleanup unused branches once your PR is merged
- [x] some words around the review process, using @r-j-arnold suggestion in #128

**Comment by pherterich** [comment]
@KirstieJane @r-j-arnold with the cleaning up branches outstanding until we have a conversation at the next sprint (and covered by reminders such as #177 ), are we okay closing this issue and start a new one for anything else that comes up?
