### ISSUE TITLE
[NEW CHAPTER] - On and offboarding checklists for lab members

### ISSUE THREAD

**Issue by EstherPlomp** [the-turing-way/the-turing-way#2945]
### Title

On and offboarding checklists for lab members

### Guide

Project design?

### Draft

https://hackmd.io/@TycZoDDEQIq6yttGuqbuww/HynG82Fss

### Summary of proposed chapter

I think it would be helpful to have some pointers to what to think about when a new person joins a lab/team/research group. 

This probably relates to another issue I opened: #2877

### Resources
- [x] https://osf.io/pw7ed/
- [x] https://doi.org/10.5281/zenodo.6321216 
from #2877
- [x] http://hdl.handle.net/2142/111616
- [x] https://resolver.caltech.edu/CaltechAUTHORS:20200519-142758925 
- [x] https://www.nature.com/articles/d41586-022-02967-3 (why you need one – memory loss)

from #650
- [ ] https://theodi.org/article/check-out-our-rd-open-research-tools/ -- similar resource from ODI that already exists (could be reffered to in the onboarding part)

### Updates

- [X] Write chapter outline
- [ ] Add material to the chapter
- [ ] Combine materials into a readable chapter
- [ ] Proofread
- [ ] Create PR and link in the comments
- [ ] Request reviews
- [ ] Address reviews
- [ ] Merge to main branch

**Comment by malvikasharan** [comment]
@EstherPlomp Have you seen this? https://github.com/alan-turing-institute/the-turing-way/pull/1806
