### ISSUE TITLE
[TO EDIT] Planning for Project Design 

### ISSUE THREAD

**Issue by Arielle-Bennett** [the-turing-way/the-turing-way#2973]
### Summary

The Programme Management team from Tools, Practices & Systems at The Alan Turing Institute, would like to propose the ["Planning Project Design"](https://the-turing-way.netlify.app/project-design/pd-overview/pd-overview-planning.html) chapter is revised and restructured. We envision adding additional resources, context and detail, which may result in the chapter being split into sub-chapters for easier referencing and clearer navigation around the content. 

This will form part of an ongoing review of the Project Design Guide by the team, which seeks to bring best practice from the Turing's programme management to The Turing Way readers. 

### What needs to be done?

- [ ] Read & make notes on the current chapter content - what is included, what is missing, how should it be structured? 
- [ ] Propose revised structure for the chapter, including subchapters
- [ ] Write up additional content and add links to external resources (split this out once we know what the subchapters are) 
- [ ] Review subchapters 
- [ ] Check links
- [ ] Approve and merge into Turing Way

### Who can help?

- [ ] Anyone with an interest in project design 
- [ ] People who would like to share how their organisation approaches project design and planning 
- [ ] People who do not have an interest in project design but would like to help review the revised content 

### Updates

- [ ] First set of edits to chapter/subchapter
- [ ] Proofread
- [ ] Request reviews
- [ ] Address reviews
- [ ] Merge to main branch

**Comment by KirstieJane** [comment]
I'm trying to make time to read TTW GitHub issues and just want to say that this is so wonderful! Thank you 💖

**Comment by Arielle-Bennett** [comment]
Notes for this being added here: https://hackmd.io/@Arielle-Bennett/rJ-Sc2t-3

**Comment by Arielle-Bennett** [comment]
Updating this to flag that I want to work on this during the Book Dash in May 🎈
