### ISSUE TITLE
February/march Fireside Chat planning issue: event on 31 March

### ISSUE THREAD

**Issue by malvikasharan** [the-turing-way/the-turing-way#2982]
**The upcoming Fireside chat is on 31 March 2023**

Register here to attend: [Reflect, unlearn, reframe: Community care in times of digital burnout](https://www.eventbrite.co.uk/e/reflect-unlearn-reframe-community-care-in-times-of-digital-burnout-tickets-567859923317?aff=ebdsoporgprofile)

## Before the Event -- at least 6-8 weeks in advance

- [x] Create a Zoom link with a waiting room and live transcription enabled
- [x] identify an overarching theme that we share with a different community -- Fireside chat is intended to promote cross-community collaboration
- [x] reach out to a community representative who can co-facilitate the event with a core team member in The Turing Way
- [x] Set up an internal shared document for discussions and notes (The Turing Way shared google doc, see [this template](https://docs.google.com/document/d/1X_NfRkkH6p47yRgpd6xlw8yrvo6jIsbF_mV0BinjcaQ/edit?usp=sharing))
- [x] discuss what the co-hosts might want to highlight at this fireside chat (note: these discussions don't necessarily need to identify a solution - but recognised shared themes, challenges, and spaces some research communities share)
- [x] Identify speakers from the community and invite them
- [x] Create a private Slack Channels with all speakers and hosts and discuss some overarching topics they are interested in sharing
- [x] Ask for the bio and image of speakers
- [ ] Ask for speakers to sign release form
- [x] Schedule the first check-in 4-5 weeks in advance to surface some common themes, helping plan the title and questions
- [x] Decide on a common date and send placeholder calendar invite blocking their calendar for the event (15 mins pre-event tech-check/Green room, 60 minutes live and 15-30 minutes unrecorded discussion with the audience)
- [x] Create an Eventbrite page in The Turing Way account - see [this page for example](https://www.eventbrite.co.uk/e/navigating-growth-and-scale-to-sustain-open-communities-tickets-360328802147) (you can copy and edit)
- [x] Set up the Etherpad using the template provided here: https://hackmd.io/@turingway/fireside-chats (see [this example](https://pad.sfconservancy.org/p/ttw-fireside-chat-mar2022))
- [x] Create a paragraph to add to the Eventbrite page along with the speakers' and hosts' bio
- [x] Create a flyer to share on social media using [this template](https://docs.google.com/presentation/d/1Fx2WcVvGX6dM3z74VDQp_UD8edKp6Phl/edit?usp=sharing&ouid=102682705838770934280&rtpof=true&sd=true)
- [x] Coordinate on Slack with the speakers if they are happy with the announcements and if their info is correct
- [x] Announce at least 3-4 weeks in advance on Slack, Newsletter, Twitter and different talks
- [x] Add information to the Intro hackmd: https://hackmd.io/@turingway/demo-intro
- [x] Hosts will define an agenda and questions for the session - hosts will also allocate some questions for each other to speak on
- [x] Set another check-in at least 2 weeks in advance to touch base and discuss the plans and questions with the speakers - assign 1-2 questions for each speaker to begin 
- [x] Plan with cohost who will ask which question, how you will time keep, what channel you will use to ask questions to each other privately, who will monitor the chat (maybe ask someone outside this group to help with note taking and chat monitoring)
- [x] Update the calendar invite with Zoom, Etherpad and Eventbrite -- encouraging them to share the Eventbrite page in their network
- [x] Identify someone from the community who can do the introduction of The Turing Way, code of conduct reminder and pass it to the speakers

**During the session**
- [x] Open the Zoom call 15 minutes in advance (keep the waiting room of Zoom enabled)
- [x] test if speakers' microphone, camera and internet work alright - help troubleshoot any tech challenge
- [x] Let participants in right on time
- [x] Welcome them and share Etherpad
- [x] Remind them that the call will be recorded and that participants can use chat (but may not have the chance to speak during the 60 minutes live)
- [x] start recording and enable transcription
- [x] In 5 minutes past as people join, the person designated to welcome them will introduce the Turing Way, CoC, and Etherpad information and Present the topic
- [x] Hosts then introduce themselves and post the opening questions allowing all speakers including the co-host to share their position on the topic in 2 minutes
- [x] As planned in the agenda, hosts ask the question posed to the specific speaker, follow up response from the other speaker is invited
- [x] Speakers will make sure that everyone on the panel has had an equal chance to discuss and share their opinions
- [x] Any question from the chat is copied over the Etherpad, in the last 10 minutes publically posed question can be asked
- [x] The recorded session finish with 30 second closing argument
- [x] After the 60 min recording, all participants are reminded of the next stage of unrecorded discussion informally with the speakers 
- [x] Hosts close the call in maximum of 30 minutes after the session

**After the session**
- [x] Send a thank you email to the speakers - within 1 day
- [x] Archive all notes here: https://hackmd.io/@turingway/fireside-chats
- [x] Download the video from Zoom and edit the live transcription (proofread cc)
- [x] Upload the video on The Turing Way youtube - label and annotate well, and add the flyer as the video's front page
- [x] Share the published videos with the speakers
- [ ] Summarise the session to add to The Turing Way -- invite someone from the community who could do that 
- [x] Promote the video via Slack, Newsletter, Twitter
- [x] Send a thank you email to the Eventbrite participants sharing the video and inviting any ideas and suggestions for improvement via a standard feedback form
- [ ] Update the book chapter and templates if needed
- [x] Update the video link here and update the section for the upcoming Fireside chat
- [x] Add speakers to this GitHub repo using all contribution bot for presentation
- [x] Close this PR as complete

**Comment by aleesteele** [comment]
Adding a note here to follow up with speakers about release form for recording.

Also keen to trial a new advertising template, a few examples coming later this week!

**Comment by aleesteele** [comment]
Complete! Recording is available here: https://www.youtube.com/watch?v=IfNn4WgBUCQ

**Comment by malvikasharan** [comment]
Thanks @aleesteele. Have the speakers been added via all-contributors bot?

**Comment by aleesteele** [comment]
Thanks for the reminder! 

@all-contributors please add @pherterich for Event Organizers

**Comment by aleesteele** [comment]
@all-contributors please add @pherterich for event organizing 🤦‍♀️

**Comment by aleesteele** [comment]
@all-contributors please add @eirini-zormpa for event organizing

**Comment by aleesteele** [comment]
@all-contributors please add @agnes

**Comment by aleesteele** [comment]
@all-contributors please add @chartgerink for event organizing

**Comment by malvikasharan** [comment]
@all-contributors please add @msundukova for event organizing

**Comment by malvikasharan** [comment]
@all-contributors please add @malvikasharan for event organizing

**Comment by malvikasharan** [comment]
We'll carry over the task of summarizing the event.

**Comment by aleesteele** [comment]
Reopening as we still have to grab Agnes' handle (if she has/wants one)!
