### ISSUE TITLE
[WIP] Book Dash: Github Training Workshop

### ISSUE THREAD

**Issue by aldenc** [the-turing-way/the-turing-way#3061]
# Book Dash: Github Training Workshop

### 🚀🌟 Welcome to _The Turing Way_! We're so glad to have you here! 🌟 🚀 

_The Turing Way_ is a community-led resource for reproducible, open, collaborative, and inclusive data science. Created by over 400 contributors, The Turing Way uses open source tools to enable people to collaboratively write chapters, build and maintain resources, as well as share their skills and ideas around best practices. Core to this is the version control tool, Github which supports The Turing Way’s collaborative practices. 

### Workshop Information
**Date:** Thursday 11 May
**Start time:** 17:00 | End time: 18:30
[Workshop Slides](https://docs.google.com/presentation/d/1El505-SI20cS2rSOXHfacdnMMWaasGZ7/edit?usp=sharing&ouid=102590248842101173670&rtpof=true&sd=truehttps://docs.google.com/presentation/d/1El505-SI20cS2rSOXHfacdnMMWaasGZ7/edit?usp=sharing&ouid=102590248842101173670&rtpof=true&sd=true)

In this workshop, co-facilitators from The Turing Way Community will introduce participants to using GitHub as a tool to support collaborative documentation-writing and knowledge sharing. 

They will discuss the importance of open community practices in building and maintaining collective resources, and learn about the importance of different roles in open source documentation communities like The Turing Way: including that of maintainers, reviewers, and translators.

Participants will gain hands-on experience in working collaboratively during the workshop by contributing to the The Turing Way project. A shared document will be used for collaborative note-taking, capturing feedback and learnings.

This training is being offered as a part of [Book Dash](https://the-turing-way.netlify.app/community-handbook/bookdash.html): a week-long event of contributions and collaborations within The Turing Way community.

#### About the Trainers

Alden Conner (@aldenc) is a Senior Researcher in the Research Application Management team at the Turing.

Arielle Bennett (@Arielle-Bennett) is a Programme Manager for Tools, Practices, and Systems at the Turing.

### Housekeeping 
**Privacy statement**
This event follows the [The Alan Turing Institute's Privacy Policy](https://www.turing.ac.uk/privacy-policy).

**Code of Conduct**
* Attendees of this session will be expected to adhere to the The Turing Way's [Code of Conduct](https://github.com/alan-turing-institute/the-turing-way/blob/main/CODE_OF_CONDUCT.md)

If you have any questions, comments, and recommendations, please contact **Alden (aconner@turing.ac.uk), Arielle (abennett@turing.ac.uk), or Alexandra (aaraujo.alvarez@turing.ac.uk)** or comment on this issue. 

# Icebreaker question
Comment below with an answer to the following question: 

**What is an activity you could you do for a long time without getting bored?**

**Comment by emmac123** [comment]
Going to the beach with friends

**Comment by aleesteele** [comment]
Thank you all for the lovely workshop! Going to close this in preparation for our first onboarding of the year 😄
