### ISSUE TITLE
Add another resource to 'open education' list

### ISSUE THREAD

**Issue by aleesteele** [the-turing-way/the-turing-way#3064]
# A Beginner's Guide to Contributing to _The Turing Way_

This is a guide for getting started with contributing to The Turing Way during the Book Dash in May 2023. We're so glad to have you here! 🎉 

Below you'll find some instructions for contributing to the project. If you have any questions, please let @aldenc, @Arielle-Bennett, @AlexandraAAJ know on Zoom so that we can assist you.

## Summary
On the ['open education' page](https://the-turing-way.netlify.app/communication/open/education.html), there is an additional resource that can be added to the list of existing resources.

## Guide to Contribution 

1. Comment on the issue  people working using their Github usernames.

1. Visit the relevant part of the repository to address this issue: https://github.com/alan-turing-institute/the-turing-way/blob/main/book/website/communication/open/education.md

3. Find line 36 to find the phrase `Open Education [benefits (and stakeholders)](https://openeducationalresources.pbworks.com/w/page/24838012/Stakeholders%20and%20benefits)`.

4. Click 'Edit this file'. 

5. Add the following text after line 36, as a new bullet point:
```
- [Why Open Education Matters](https://www.opensocietyfoundations.org/voices/why-open-education-matters)
```

6. Click 'Preview' to check that the changes look the way you'd like them too!

7. Navigate to 'Propose changes' at the bottom of the page: edit the title and the description of the issue to describe your update to the community.

8. Click 'Propose changes'. You will be redirected to a new page to make a Pull Request within the project. 

9. There will be template text in the Pull Request as is: don't worry too much about that! Erase the text, then link the issue tag using a`#`. You can find the issue number next to the title of this issue.  

Example: `this pull request fixes #3064`

10. Click 'Create Pull Request'! Congratulations! 🎉 

11. A reviewer will review your pull request, and ask you if you need to make any changes before it can be approved.

12. There are a number of checks your project will undergo: to check for merge conflicts, inclusive language, and formatting issues. Wait until those checks are complete before merging.

14. Once your pull request is approved and the checks are complete, you can merge your change into the repository! ✅

**Comment by tarunsamanta2k20** [comment]
I'd like to work on this issue
