### ISSUE TITLE
[EVENT Proposal] Open Access Week discussion

### ISSUE THREAD

**Issue by aleesteele** [the-turing-way/the-turing-way#3077]
### Date of talk

2023-10-23

### Details of the talk

This year, the theme of Open Access Week is ["Community over Commercialisation"](https://www.openaccessweek.org/), being held 23-29 October 2023, summarised below from their website:

> Open Access Week 2023 is an opportunity to join together, take action, and raise awareness around the importance of community control of knowledge sharing systems. This year’s theme encourages a candid conversation about which approaches to open scholarship prioritize the best interests of the public and the academic community—and which do not.

This submission follows [A Joint Appeal for Open Science by CERN, OHCHR, UNESCO and WHO](https://www.ohchr.org/en/press-releases/2020/10/joint-appeal-open-science-cern-ohchr-unesco-and-who), and various efforts across open science communities in previous years.

We have a Fireside Chat planned for this week on Thursday with The Maintainers, alongside the theme of "Maintaining Knowledge Infrastructures", which aligns with the theme for the week. This is being organised in parallel - and folks are welcome to get involved and/or suggest names. Planning for that is happening [here](https://docs.google.com/document/d/1JxvmxkEK0K9ziEM3x2we-aWwuA5dxzvp0q_ZR2AxIiE/edit#heading=h.hmjj4rapmv7o).

It could be great to plan for a series of short chats (similar to our event with [Posit team members](https://www.eventbrite.co.uk/e/the-turing-way-hosts-julia-silge-and-ella-kaye-tickets-616033842807?aff=ebdsoporgprofile) related to Open Access and knowledge infrastructure. Would we want to have a separate event from this fireside chat, perhaps something on that Monday, with Thursday closing us off? Or a TPS Coffee Chat takeover?

Tagging: @chartgerink, @vhellon, @EstherPlomp who mentioned interest in getting involved!

### Checklist

- [ ] Schedule your talk and let the community know in [TTW Slack](https://theturingway.slack.com/). If you’d like feedback and/or to schedule a practice talk, ask in the TTW Slack!
- [ ] Download template(s) from the [promotion pack](https://drive.google.com/drive/folders/1mzGmbJkPnP5q1goQesxDc_E5zAPL0eTF?usp=sharing) to ensure stylistic consistency
- [ ] Generate a DOI on [Zenodo](zenodo.org/) and upload your slides when ready, preferably in the original format along with a PDF or any other format you are using. Tag with "the-turing-way" under **Communities**. Zenodo allows [versioning](https://help.zenodo.org/#versioning), so we encourage you to upload your slides before your talk and add additional file(s) with any changes after
- [ ] Check all ackowledgements (bottom right corner of each slide) and add the DOI for your presentation and your personal contact info if desired
- [ ] If you re-used slides from a specific talk, please acknowledge the original author of the slides
- [ ] Double check acknowledgements slide for TTW team, license info, Scriberia link, any additional acknowledgements
- [ ] Double check contact info for TTW links (book, Twitter, GitHub, Slack, newsletter), your own contact into
- [ ] Share the Zenodo link and a recording (if available) in TTW Slack!

**Comment by chartgerink** [comment]
Woo @aleesteele - you're already much further in planning than I am 😅 I was thinking of having a livestreamed discussion as part of what we do at Liberate Science, as there's plenty to talk about (both in terms of pro the statement and against).

I don't think I have much to contribute to the Fireside Chat beyond simply being a sounding board (you and the team rock those every time 👍 ), and that we can refer to one another's events when we know they're happening. 

I would suggest to add to the checklist that the event is added to the OAWeek programme: https://www.openaccessweek.org/events

**Comment by vhellon** [comment]
Happy to help brainstorm some bits! Capacity wise I think I'm probably leaning towards a TPS Coffee Chat takeover at the mo but can discuss :)

**Comment by aleesteele** [comment]
Because the TPS Coffee Chats are usually cancelled on weeks of the Fireside Chat, I don't think we'll be having a TPS Coffee Chat on this topic. We'll definitely get registered on Open Access Week though, thanks for that flag. I also wonder the Collab Cafe before this week could be used alongside this theme as well, for a wider community discussion before the panel in the following week.

**Comment by aleesteele** [comment]
Closing this issue - as we have delayed this discussion!
