### ISSUE TITLE
[WIP] Update RDM chapter

### ISSUE THREAD

**Issue by EstherPlomp** [the-turing-way/the-turing-way#3085]
### Summary

Another update to check if all the resources are still relevant, add some more things (such as qualitative research #2386) 

### To do
- [x] Check methods section
- [x] Check data visualisation section
- [x] Fix definitions of Repository:  Same as Data or Code Reprository. A long-lived place on the internet where resources (be they data, software, publications or anything else) can be stored and accessed. This keyword is often shortened to ‘repo’.
- [x] add the RDM image to the RDM start section

### What needs to be done?

- [x] Actually Accessible Data to the FAIR principles: https://doi.org/10.31274/jlsc.15449
- [x] There were a couple of comments from closed issues: * For example, I believe that section 3.1 on Open Data and Chapter 7 on RDM could be more practical with clearer guidelines on **how to actually deposit data in a data repository**. It is also important to explain why data repositories and dedicated platforms should be used for these purposes **instead of sharing data in supplementary materials of publications**. *
- [x] Add something on labnotebooks/protocols (electronic lab note books + atom/OSF as eln in combi with github)
- [x] Reproducible Data Science: https://ecorepsci.github.io/reproducible-science/index.html 
- [x] Filenaming: https://twitter.com/chazhutton/status/1285955514241875968/photo/1 
- [x] https://guides.uflib.ufl.edu/reproducibility 
- [x] Ten Simple Rules for Creating a Good Data Management Plan
- [x] https://www.scienceeurope.org/our-priorities/research-data/research-data-management/
- [x] Publishing and citing data: https://youtu.be/PpMOkTnBMlI
- [x] https://www.youtube.com/channel/UCZ8NXmIL6uaS10V043VvSwg data/code sharing
- [x] https://github.com/khuyentran1401/Data-science
- [x] https://www.bristol.ac.uk/psychology/research/ukrn/about/resources/ 
- [x] https://www.orion-openscience.eu/publications/training-materials/201808/factsheets
- [x] https://coderefinery.github.io/reproducible-research/ 
- [x] https://vimeo.com/378621271, this but then in 2 page flyer modus
- [x] [datamgmtinedresearch.com](https://datamgmtinedresearch.com/)
- [x]  https://ekaroune.github.io/The-Open-Archaeobotanist/2021-01-30-what_a_data_paper_could_do_for_you/
- [x] File format considerations: https://libguides.ucd.ie/data/description
- [x] Why Does Data Need to be Managed? - https://www.youtube.com/watch?v=C7RZ2t3Cpig
- [x]  How to generate data dictionaries/codebooks, for survey data in particular: [https://doi.org/10.1177/2515245920928007](https://doi.org/10.1177%2F2515245920928007)
- [x] Data sharing and reproducibility.  Dr Laurence Hunt : https://vimeo.com/668640629
- [x] Adapt metadata images: https://libguides.ucd.ie/data/metadata
- [x] https://journals.plos.org/plosone/s/recommended-repositories
- [x] Workflow analysis: https://www.youtube.com/watch?v=9H9xnVRlc_M
- [x] resources for novice librarians: https://crln.acrl.org/index.php/crlnews/article/view/16660
- [x] https://osf.io/xf6ug/ (Klein et al. 2018 transparancy) + publicatie
- [x] Gregory et al. 2018 summary: finding research data
- [x] Research project management: https://www.youtube.com/watch?v=tBGLRXUbCrU&t=524s
- [x] Why cite data? https://datacite.org/cite-your-data.html
- [x] Yenni 2018: RDM workflow case study
- [x]  resources https://nlm-repro.github.io/ reproducibility
- [x] Exact instruction challenge: https://www.youtube.com/watch?v=Ct-lOOUqmyY
- [x] Readme: https://www.youtube.com/watch?v=Jgv34Kwgga8&list=PL1CvC6Ez54KDvJbbdLn5rPvf1kInifEh9&index=6 or  Readme: https://www.youtube.com/watch?v=kodsPukJcE0&list=PL1CvC6Ez54KCcs99wV3eex1v5GUry6Yb7&index=5
- [x] [RDM policies canada](https://science.gc.ca/site/science/en/interagency-research-funding/policies-and-guidelines/research-data-management/published-institutional-research-data-management-strategies)
- [x] [Software sustainability institute blogpost on training resources](https://www.software.ac.uk/blog/2023-06-20-signpost-training-resources)
- [x] https://www.dcc.ac.uk/guidance/how-guides/where-keep-research-data
- [x] https://www.youtube.com/watch?v=5kImiZtU1Fs
- [x] [Data Management in Large-Scale Education Research](https://datamgmtinedresearch.com/index.html)
- [x] [Rethinking Research Data](https://www.youtube.com/watch?v=dXKbkpilQME)
- [x] [Making Qualitative Data Reusable A Short Guidebook For Researchers And Data Stewards Working With Qualitative Data](https://doi.org/10.5281/zenodo.7777519)
- [x] https://cghlewis.com/blog/data_clean_02
- [x] The Research Data Management Workbook https://doi.org/10.7907/z6czh-7zx60
- [x] Use secure deletion tools like [BleachBit](https://www.bleachbit.org/) or [FileShredder](https://www.fileshredder.org/) before discarding any hardware
- [x] OS101x_2020_Module_2_1_1_Research_data_management-video https://www.youtube.com/watch?v=QRy2uGTpEcQ
- [x]  OS101x_2020_Module_2_8_7_Responsibilities_and_resources-video https://www.youtube.com/watch?v=Ry0OA9mDTCc 

### Who can help?

* Anyone happy to get involved :)
*

**Comment by EstherPlomp** [comment]
Add something about Actually Accessible Data to the FAIR principles: https://doi.org/10.1123/jlsc.15449

**Comment by jezcope** [comment]
This DOI doesn't seem to work. Is it this you're referring to?

> Colón, R., Goben, A. & Karcher, S. (2023). Actually Accessible Data: An Update and a Call to Action. Journal of Librarianship and Scholarly Communication, 11(1), eP15449. https://doi.org/10.31274/jlsc.15449

**Comment by jezcope** [comment]
I wonder if I can find some time to take a proper look and contribute to this. It's been a while...

**Comment by EstherPlomp** [comment]
That is the one indeed! Thanks! Super annoying - that is the DOI listed in my pdf version of it..

**Comment by EstherPlomp** [comment]
Continuing the part about 'how to practically share data in a data repository' in #3382

**Comment by EstherPlomp** [comment]
Fixed by #3214
