### ISSUE TITLE
[NEW CHAPTERs] -open source hardware

### ISSUE THREAD

**Issue by jcolomb** [the-turing-way/the-turing-way#3111]
### Title

open source hardware 

### Guide

multiple
linked PR
- main page:  #3114

- citable: #3123
- sharing: #3125
- license: #3148
- "project documentation" on working in the open:#3169

linked issues:

- user/contributors/ other roles #3124

- project scope (first steps in a project): #3131
- project documentation: #3166

### Summary of proposed chapter

- Rewrite the open source hardware chapter
- extend with more information at different places in the book (TBD)

### Who can help?

@jspickering wrote the first draft (that was not an info easy to find :), hopefully we have a  git-guru with us :))

### Updates

- [x] Write chapter outline
- [x] Add material to the chapter
- [x] Combine materials into a readable chapter
- [x] Proofread
- [x] Create PR and link in the comments
- [x] Request reviews
- [ ] Address reviews
- [ ] Merge to main branch

**Comment by Jerzeek** [comment]
Maybe we can ask the people who previously added content to review the new content? https://github.com/alan-turing-institute/the-turing-way/commits/main/book/website/reproducible-research/open/open-hardware.md

**Comment by jcolomb** [comment]
I went through the document: https://hackmd.io/@DItEXDbBTeCvUMaRWchv_Q/Byc3XKiS2/edit
Notes: each sentence is one line in the markdown, as it should then be in the book, I added some yaml at the beginning so hackmd renders it correctly.

I can’t find the OHmaker documentation, although I know it exists… @ julieta can you send me the link, is there a citation for it?
UKRN primer on open science hardware : is there a link ?

---


I moved a large part of the project description here: https://hackmd.io/@DItEXDbBTeCvUMaRWchv_Q/ByNH8vxIh/edit
This is to be pushed to :  https://the-turing-way.netlify.app/project-design/pd-overview/pd-overview-repro.html
Please review, I will make a Pull Request on Tuesday.

—

@santosh, the detailed license information is at https://hackmd.io/@DItEXDbBTeCvUMaRWchv_Q/HkguwDRH3/edit, can you check wether some part would go in https://the-turing-way.netlify.app/reproducible-research/licensing.html, while other in a specific page for hardware (https://github.com/alan-turing-institute/the-turing-way/pull/3148)?

**Comment by jcolomb** [comment]
https://github.com/all-contributors add @thessaly @Jerzeek @SachaHq for content

**Comment by jcolomb** [comment]
@all-contributors add @thessaly @Jerzeek @SachaHq for content

**Comment by jcolomb** [comment]
@all-contributors add  @Jerzeek @SachaHq for content

**Comment by jcolomb** [comment]
@all-contributors add @SachaHq for content

**Comment by jcolomb** [comment]
@all-contributors add @SachaHq for content
