### ISSUE TITLE
[WIP] update pd-overview/pd-overview-repro.html

### ISSUE THREAD

**Issue by jcolomb** [the-turing-way/the-turing-way#3166]
### Summary

Working on OSH project documentation (#3111), we produced some text that would be better go in the project design guide.

I have been merging the text with the corresponding part of the book, expanding the section and adding/modifying sub-headers.
 

### What needs to be done?

- [x] review the hackmd text https://hackmd.io/@DItEXDbBTeCvUMaRWchv_Q/ByNH8vxIh/edit
- [x] create pull request
- [x] change toc (new title)

### Who can help?

- [ ] @malvikasharan 
- [ ] @MIE5R0
- [x] @MoritzMaxeiner
- [X] @SachaHq 

### Updates

- [X] First set of edits to chapter/subchapter
- [x] Proofread
- [x] Request reviews
- [ ] Address reviews
- [ ] Merge to main branch

**Comment by SachaHq** [comment]
I volunteer for 
1. reviewing the text on hackMD
2. offer additional content, i.e. a scope related checklist for the contents based on Nico work.
