### ISSUE TITLE
Add Slack guide in the community handbook

### ISSUE THREAD

**Issue by malvikasharan** [the-turing-way/the-turing-way#3233]
### Summary

Governance-related actions on different committees, working groups and core delivery team
Find details in #3215 

### What needs to be done?

**Add Slack guide in the community handbook**  -- assign to the Community Manager, involve community members

- How long is too long to leave a post unanswered in TTW Slack
    - We have a Slack Guide - not sure if we do need to go into such granular detail. Ideally, CM and other community members keep an eye on the posts.
- slack is a lot - important messages can be lost quickly (many people are in multiple workspaces)
    - Update the Slack guide - add Slack guide in the Community handbook

### Who can help?

- @aleesteele add and also invite community consultation

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by aleesteele** [comment]
Thanks @malvikasharan! Tagging this to #3144 to connect the issue.

Also adding the link to the guide here: https://hackmd.io/@turingway/ttw-slack-intro

**Comment by da5nsy** [comment]
Crumbs for #3217 
_(and a little bit for #3218 too)_
