### ISSUE TITLE
Buy a dedicated domain/URL for The Turing Way

### ISSUE THREAD

**Issue by aleesteele** [the-turing-way/the-turing-way#3266]
### Summary

Ties to current expansion of infrastructure with #3213 and #3272. Below edited by @AlexandraAAJ:

#### **Reasons to buy the Domain and level of importance:**

* The domain name is given by netlify if we swap to readthedocs, the URL will find a broken webpage.
* If we buy one, we will redirect traffic from one to another url. While we could redirect from netlify to readthedocs, it is much better to type [theturingway.org](http://theturingway.org/) (or the preferable domain). We don’t need to rely on netlify or readthedocs.
* If in the future if there’s another platform to deploy, the change will be easier and our URL name will be consistent

#### Update, following community discussion

Following [a request for community input](https://github.com/the-turing-way/the-turing-way/issues/3266#issuecomment-1934599627) and a subsequent discussion, [a decision has been made](https://github.com/the-turing-way/the-turing-way/issues/3266#issuecomment-1966687779) to move forwards with a domain name change to `the-turing-way.org`. 🎉 

---

#### Pain points: create a table 

* Identify Maintenance ownership: (as per Jim’s contribution) “It is worth thinking about the bus factor when we plan how to purchase the domain name and manage DNS. We don’t want to have to require a particular person to make any changes or fix problems.I like the idea of the Infrastructure WG being responsible.”
* Budget & Credit card details: this would cost between £15 - £35 per year. We could use KW’s credit card once approved. 
* DPAP: is there any risk associated with having an independent URL?
* Risk of reputational issue with The Alan Turing Institute: as per the arguments mentioned above, we are buying an URL to avoid depending on external software providers (netlify/readthedocs) and ensure that the notebook is available. In a future stage, having an independent URL will allow us to centralise and organise the diverse content of the project in a single space
* Proposed planning stages and domain structure, open for discussion: (domain name could be different, depending on the URL to buy)
    * Stage 1: (identify the complexity and timeframe of each stage)
        * Get community consensus on what DOMAIN-NAME they want List: 
        * DOMAIN-NAME/book
        * DOMAIN-NAME/root - or start page?
        * SSL (mandatory for security reasons?) - is there any cost related to this?
    * Stage 2:
        * DOMAIN-NAME/calendar
        * DOMAIN-NAME/newsletter
    * Stage 3:
        * DOMAIN-NAME/blog
        * DOMAIN-NAME/news
        * Other (specify)

<table>
  <tr>
   <td>
Aspect
   </td>
   <td>Responsible
   </td>
   <td>Ideas
   </td>
   <td>Comments
   </td>
  </tr>
  <tr>
   <td>Maintenance
   </td>
   <td>Infrastructure WG
   </td>
   <td>
   </td>
   <td>
   </td>
  </tr>
  <tr>
   <td>Budget 
<p>
(between £15 - £35 per year)
   </td>
   <td>Expense will be covered by The Turing
   </td>
   <td>Create calendar alerts to renew or buy for 5-10 years
   </td>
   <td> 
   </td>
  </tr>
  <tr>
   <td>DPAP- Risk related
   </td>
   <td>RPM (AAA) to check with Kit to follow Turing policies 
   </td>
   <td>
   </td>
   <td>
   </td>
  </tr>
  <tr>
   <td>
   </td>
   <td>
   </td>
   <td>
   </td>
   <td>
   </td>
  </tr>
</table>

### Available Domains and prices
| Domain                                          | go daddy - Cost for 1 year in Pounds - (7.9 per year for DNS) | go daddy - Cost for 10 years - (7.9 per year for DNS) | Name chaeap - Cost for 1 year in Pounds - (3.83 per year for DNS) | Name chaeap - Cost for 10 year in Pounds - (3.83 per year for DNS) | Ionos - for 1 year Not sure how to buy DNS (10 years is not allowed) |
| ----------------------------------------------- | ------------------------------------------------------------- | ----------------------------------------------------- | ----------------------------------------------------------------- | ------------------------------------------------------------------ | -------------------------------------------------------------------- |
| [the-turing-way.org](http://the-turing-way.org) | 10.16 or 22                                                   | 209                                                   | 5.87                                                              | 97                                                                 | Cost for 6 months is £1 and then £9                                  |
| [theturingway.org](http://theturingway.org)     | 10.16 or 23                                                   | 209                                                   | 5.87                                                              | 97                                                                 | Cost for 6 months is £1 and then £9                                  |
| [theturingway.io](http://theturingway.io/)      | 37.99                                                         | 209                                                   | 35.32                                                             | 353                                                                | £33                                                                  |
| What other domains?                             |               

## Domain migration timeline

Time t=0 is the purchasing of the domain.

- t<0
  - [x] Create domain change announcement banner for book, but don't merge yet
- t=0
  - [x] Domain purchased
- t=0+δt
  - [x] Add domain to [Netlify custom domains](https://docs.netlify.com/domains-https/custom-domains/)
  - [x] Configure DNS (A/AAAA records for book)
  - [x] Merge domain change announcement banner into book
- t=0+deploy time
  - [x] trigger internet archive to fetch book _including_ domain change announcement banner
    - [the-turing-way.netlify.app](https://web.archive.org/web/20240321090037/https://the-turing-way.netlify.app/index.html)
    - [book.the-turing-way.org](https://web.archive.org/web/20240321090125/https://book.the-turing-way.org/)
- t=0+1 week
  - [x] Email/Slack announcement about upcoming domain change
  - [ ] Set up redirect rules for the-turing-way.netlify.app to new domain (So anyone looking for old URLs should be _moved_ to the new one)
- t=0+3 week
  - [ ] Reminder Email/Slack announcement
- t=0+4 weeks
  - [ ] Replace all remaining the-turing-way.netlify.app links in book
- next (work that domain purchase enables, but not directly part of this migration)
  - Migrate hosting
  - Add DNS records for email (perhaps)

**Comment by AlexandraAAJ** [comment]
Would this also affect splitting the repo's: https://github.com/the-turing-way/the-turing-way/issues/3352 and The Turing Way Knowledge Map (where we can find the info from TTW)

**Comment by JimMadge** [comment]
Copying some comments from Slack,

It is worth thinking about bus factor when we plan _how_ to purchase the domain name and manage DNS. We don't want to have to require a particular person to make any changes or fix problems.

I like the idea of the Infrastructure WG being responsible. If we can find a domain registrar where we can have an organisation that would be great. Otherwise, sharing credentials :grimacing:?

The problem there is, if we are using someone's personal credit card, that exposes them a bit. Not that I think any of us would go on a domain buying spree.

**Comment by JimMadge** [comment]
I think there is some planning/design work, but it is all (I hope) pretty simple.

- Domain structure
  - root - [the-turing-way.org](http://the-turing-way.org/) (redirects to start page)
  - startpage - [start.the-tuing-way.org](http://start.the-tuing-way.org/)
  - book - [book.the-turing-way.org](http://book.the-turing-way.org/)
  - calendar - [cal.the-turing-way.org](http://cal.the-turing-way.org/)
  - _etc._
- SSL certs (if we need to do that ourselves)
  - Let's Encrypt

The DNS configuration should come fairly naturally (I hope). It might be nice to explain what we do/how it works that somehow in the community handbook.

**Comment by AlexandraAAJ** [comment]
### **Buy a dedicated domain/URL for The Turing Way**

Update this issue: [https://github.com/the-turing-way/the-turing-way/issues/3266](https://github.com/the-turing-way/the-turing-way/issues/3266) (remove the WIP)


#### 
**Reasons to buy the URL and level of importance:**



* The domain name is given by netlify if we swap to readthedocs, the URL will find a broken webpage.
* If we buy one, we will redirect traffic from one to another url. While we could redirect from netlify to readthedocs, it is much better to type [theturingway.org](http://theturingway.org/) (or the preferable domain). We don’t need to rely on netlify or readthedocs.
* If in the future if there’s another platform to deploy, the change will be easier and our URL name will be consistent

#### Pain points: create a table 

* Identify Maintenance ownership: (as per Jim’s contribution) “It is worth thinking about the bus factor when we plan how to purchase the domain name and manage DNS. We don’t want to have to require a particular person to make any changes or fix problems.I like the idea of the Infrastructure WG being responsible.”
* Budget & Credit card details: this would cost between £15 - £35 per year. We could use KW’s credit card once approved. 
* DPAP: is there any risk associated with having an independent URL?
* Risk of reputational issue with The Alan Turing Institute: as per the arguments mentioned above, we are buying an URL to avoid depending on external software providers (netlify/readthedocs) and ensure that the notebook is available. In a future stage, having an independent URL will allow us to centralise and organise the diverse content of the project in a single space
* Proposed planning stages and domain structure, open for discussion: (domain name could be different, depending on the URL to buy)
    * Stage 1: (identify the complexity and timeframe of each stage)
        * Get community consensus on what DOMAIN-NAME they want List: 
        * DOMAIN-NAME/book
        * DOMAIN-NAME/root - or start page?
        * SSL (mandatory for security reasons?) - is there any cost related to this?
    * Stage 2:
        * DOMAIN-NAME/calendar
        * DOMAIN-NAME/newsletter
    * Stage 3:
        * DOMAIN-NAME/blog
        * DOMAIN-NAME/news
        * Other (specify)

<table>
  <tr>
   <td>
Aspect
   </td>
   <td>Responsible
   </td>
   <td>Ideas
   </td>
   <td>Comments
   </td>
  </tr>
  <tr>
   <td>Maintenance
   </td>
   <td>Infrastructure WG
   </td>
   <td>
   </td>
   <td>
   </td>
  </tr>
  <tr>
   <td>Budget 
<p>
(between £15 - £35 per year)
   </td>
   <td>Expense will be covered by The Turing
   </td>
   <td>Create calendar alerts to renew or buy for 5-10 years
   </td>
   <td> 
   </td>
  </tr>
  <tr>
   <td>DPAP- Risk related
   </td>
   <td>RPM (AAA) to check with Kit to follow Turing policies 
   </td>
   <td>
   </td>
   <td>
   </td>
  </tr>
  <tr>
   <td>
   </td>
   <td>
   </td>
   <td>
   </td>
   <td>
   </td>
  </tr>
</table>

### Available Domains and prices
| Domain                                          | go daddy - Cost for 1 year in Pounds - (7.9 per year for DNS) | go daddy - Cost for 10 years - (7.9 per year for DNS) | Name chaeap - Cost for 1 year in Pounds - (3.83 per year for DNS) | Name chaeap - Cost for 10 year in Pounds - (3.83 per year for DNS) | Ionos - for 1 year Not sure how to buy DNS (10 years is not allowed) |
| ----------------------------------------------- | ------------------------------------------------------------- | ----------------------------------------------------- | ----------------------------------------------------------------- | ------------------------------------------------------------------ | -------------------------------------------------------------------- |
| [the-turing-way.org](http://the-turing-way.org) | 10.16 or 22                                                   | 209                                                   | 5.87                                                              | 97                                                                 | Cost for 6 months is £1 and then £9                                  |
| [theturingway.org](http://theturingway.org)     | 10.16 or 23                                                   | 209                                                   | 5.87                                                              | 97                                                                 | Cost for 6 months is £1 and then £9                                  |
| [theturingway.io](http://theturingway.io/)      | 37.99                                                         | 209                                                   | 35.32                                                             | 353                                                                | £33                                                                  |
| What other domains?                             |

**Comment by JimMadge** [comment]
Thanks @AlexandraAAJ :tada:!

Some comments,

> SSL (mandatory for security reasons?) - is there any cost related to this?

_I think_ SSL is mandatory now, even for a static site. It is too easy not to use and I believe modern browsers will show warning for sites not using HTTPS.

It doesn't necessarily cost. SSL is a service as you need a trusted party to validate your certificate. However, some organisations will do that for free. If we have the choice I think we should use [Let's Encrypt](https://letsencrypt.org/) because of their commitments to freedom/openness. That said, we should also consider donating and encouraging donations.

Exactly how SSL works will probably depend on how we host. I think hosting providers often take care of it for you.

> Proposed planning stages and domain structure, open for discussion: (domain name could be different, depending on the URL to buy) 

I would suggest using subdomains rather than paths for different things. For example,

- `book.the-turing-way.org` rather than `the-turing-way.org/book`
- `cal.the-turing-way.org` rather than `the-turing-way.org/calendar`

It is easier to manage that way. (At least, that's how I've always done it :smile:).

> (3.83 per year for DNS)

Is this "premium" DNS? I would expect any domain registrar would include DNS in the price (otherwise, what is the point of buying the domain name). I do think I've seem NameCheap selling premium DNS though. I'm not really sure what the difference is, but maybe if your site has high traffic it helps.

**Comment by aleesteele** [comment]
Adding notes here posted on slack about gathering community input about the name shift. This is drawing from frameworks for [consensus for large groups](https://www.citizenshandbook.org/consensus_in_large_groups.pdf).

**Slack**: I can post in the #ask-away channel with a global tag, using emoji reactions to vote. The vote can be a collective infrastructure working group proposal, with three options of 1) No issue, 2) Different preference but go ahead and 3) Disagree, and commitment to comment. Adding draft language here now. Comments will be cross-posted to this issue.
**Collaboration Cafe**: I can reserve the next 'main room' discussion in the Collab Cafe so that folks can join in/discuss the names in real time. The next one is next week on 7 February. Notes can be used for reporting can be added to this issue as well.
**Newsletter**: Flag that voting is happening, linking outwards. Say that it closes on 14 Feb.
**Social media**: Voting is not happening directly on those platforms, but can link people to appropriate channels if they want to engage similarly with deadline.
**Community call**: Votes and comments are compiled and then presented at Community Call, with confirmation of URL name.

How does that sound?

I know it's frustrating to be the one asking to slow down, but two weeks is a very short amount of time for volunteers or community members who are more passively tracking the project. My priority is to make sure they can tune in if they like, and that folks less visible in the community can chime in. If we move too quickly, the 'community-led' element will seem cursory. I also know that if we move too slowly, [we lose momentum](https://www.citizenshandbook.org/wilt.html)... but this is an example of a decision where we can embody the kind of transparency/openness that we're trying to achieve with governance this year.

I would suggest that we set the deadline for choosing this URL as finalised on 15 February at the community call. Can you move forward without the URL for the next two weeks @Danny Garside?

Also adding some notes about the decision tree here: https://github.com/orgs/the-turing-way/projects/3/views/3?filterQuery=decision&pane=issue&itemId=50856916

**Comment by gedankenstuecke** [comment]
Just as I see an .io domain suggested in the tables above: I would strongly suggest not going with io, due to the controversies in relationship to British colonialism: [wikipedia has some info](https://en.wikipedia.org/wiki/.io ), also c.f. [this article from the guardian in 2022](https://www.theguardian.com/world/2022/mar/21/mauritius-challenges-uk-rights-over-indian-ocean-domain-name-chagos-islands)

**Comment by gedankenstuecke** [comment]
Oh yeah, totally agree on most orgs/people not knowing that it's a "country" TLD (and even if, they might not have known about the history)! But as it's been a recurring topic in different places I thought it would be good to sidestep it!

**Comment by da5nsy** [comment]
_Following on from today's @the-turing-way/infrastructure working group meeting (TODO add link to notes) I'm writing this comment to provide the central place to which we can link on Slack and social media._

**Proposal: The @the-turing-way/infrastructure working group proposes that we start using the domain name `the-turing-way.org` (replacing `the-turing-way.netlify.app`).**

See the top comment on this issue for the rationale behind this proposal.

We're opening this up for community input, but to avoid a [boatymcboatface situation](https://en.wikipedia.org/wiki/RRS_Sir_David_Attenborough#Naming_poll) (turing-mcway-face anyone?) we'd like to ask that comments be structured as emoji reactions to this comment:

- 👍 to indicate support for changing the URL to `the-turing-way.org` 
- 👀 Different preference but go ahead 
- 👎 Disagree, with a commitment to comment on this issue with further detail

**Comment by KirstieJane** [comment]
Thank you so much to all the working group for thinking this through so well! 💖

**Comment by llewelld** [comment]
Just to check I'm understanding correctly (I did read through and I think this is made clear, but I wasn't 100% certain) the proposal includes that all requests to the current [the-turing-way.netlify.app](https://the-turing-way.netlify.app) domain will be redirected to the new domain, so no existing inward links will be broken?

**Comment by JimMadge** [comment]
> Just to check I'm understanding correctly (I did read through and I think this is made clear, but I wasn't 100% certain) the proposal includes that all requests to the current [the-turing-way.netlify.app](https://the-turing-way.netlify.app) domain will be redirected to the new domain, so no existing inward links will be broken?

That is a good question @llewelld. I'm actually not sure how easy that is to do. Could we have no HTML on Netlify and just redirects, for example?

I think I was expecting to have a clean break here so that we would have `the-turing-way.org` as the only URL from now on. Some short-term pain for lower maintenance burden.

**Comment by gedankenstuecke** [comment]
I guess in the short-term there's no moving away from netlify, so the "new" URLs and old URLs would work side-by-side. If there's a migration away from netlify it seems that it's possible to create redirect rules: https://docs.netlify.com/routing/redirects/ 

So it would be possible to ensure that the old netlify URLs still work/point to the right sources!

**Comment by penyuan** [comment]
Thank you everyone for this enormous and inclusive effort!!

I agree with @llewelld point about new vs old URLs, and in my opinion, handling and minimising [link rot](https://en.wikipedia.org/wiki/Link_rot) is a problem that's very much related to good open research. 

I suppose another possible solution is to perpetually keep one super simple page at the old `https://the-turing-way.netlify.app/` that contains just one link which says "Click here to go to the new site!" Would this work?

**Comment by llewelld** [comment]
Thanks for clarifying @JimMadge, @gedankenstuecke. Nice that netify supports redirects. Some 301 redirect rules, as early as possible before netify is retired, would be the ideal solution in my view. But I'm on the fringe here and not having to do any of the work, so just checking before applying my thumbs emoji!

**Comment by gedankenstuecke** [comment]
Right, I think as soon as the domain would be there the new 'canonical' URLs would be the ones using the own TLD, but with the netlify ones being redirected to that TLD (even if strictly speaking still being located at those netlify URLs), c.f. how github pages handles it, as soon as you have your own TLD connected to it everything is being redirected to that TLD.

**Comment by npch** [comment]
I support the proposed move to `the-turing-way.org` provided that the current netlify domain is run in parallel with redirects in place for long enough that archives (e.g. Internet Archive) can crawl and archive the redirections to the new domain.

**Comment by JimMadge** [comment]
Thanks @gedankenstuecke @llewelld :tada::pray:.

Redirects with 301 look like the right way to go.

I'm not super keen on _deploying_ the book to two places for an extended period of time (I don't think anyone is suggesting that).
I don't see why we shouldn't leave the redirects and perhaps a "we have moved" page like @penyuan suggested.
Especially as we can have permanent redirects and wildcards.

What tempts me to take a harder line is, we don't own `netlify.app` so we can loose `the-turing-way.netflify.app` and that would be out of our control. `the-turing-way.org` can survive backend migrations indefinitely. So, I would like to "push" people to the canonical URL.

**Comment by gedankenstuecke** [comment]
right, I think we're saying the same thing @JimMadge , but just to double check: 

1. The plan is doing a 301 to the own domain asap after getting the domain, even if still deployed on netlify. 
2. Then, if we ever migrate elsewhere we make sure that the old netlify URLs continue as redirects to the new home?

**Comment by JimMadge** [comment]
> right, I think we're saying the same thing @JimMadge , but just to double check:
> 
> 1. The plan is doing a 301 to the own domain asap after getting the domain, even if still deployed on netlify.
> 
> 2. Then, if we ever migrate elsewhere we make sure that the old netlify URLs continue as redirects to the new home?

1. I not exactly sure about that level of detail right now. If we bring our own domain to Netlify, are we still able to create redirects for `the-turing-way.netlify.app`?

[The docs](https://docs.netlify.com/domains-https/custom-domains/#netlify-subdomain-examples) suggest it is possible.

> The Netlify subdomain URLs will always work even if you set up a custom domain for your site.

So, I think this _is_ the most sensible thing to do :+1:, both for the infra team and readers.

3. Absolutely :+1:.

I think we agree in the broad strokes, but I'm not certain about the mechanism yet.
And I think the feedback I'm getting here is that keeping the existing URL(s) working for as long as possible (at least the foreseeable future) is important.

**Comment by sgibson91** [comment]
> provided that the current netlify domain is run in parallel with redirects in place for long enough that archives (e.g. Internet Archive) can crawl and archive the redirections to the new domain.

@npch do you have any estimation on how long 'long enough' is?

**Comment by penyuan** [comment]
Oh, by the way, could we update the *current* site with an announcement (perhaps on the first page) that a major domain change is coning, and that the URL will be changing soon? There are two advantages: 

1. Visitors coming now will see the announcement that a change is coming.
2. We can then archive the frontpage (along with the announcement) in places like the [Internet Archive](https://www.archive.org/) and others. This way, future generations can at least see the announcement in that archive that the URL has changed.

**Comment by RaphaelS1** [comment]
Hi all, I was chatting with @aleesteele and had a quick accessibility question about the-turing-way.org vs theturingway.org, which I'm also cross-posting to the accessibility Slack. Is it more accessible to have the URL with hyphens which is easier to read but more error prone (and slightly less standard in URLs) or URL without hyphens which is harder to read? Would there also be an associated Turing Way email, like [at]the-turing-way.com (which would be harder to type than [at]theturingway.com)?

I was looking into this when making my own website recently and decided against hyphens as general consensus seemed to be that hyphens are good in subdirectories but not preferable in second-level domain as they make the URL less memorable (because non-standard), possibly more likely to be targeted by people squatting on similar domains (e.g., theturing-way or the-turingway) though this argument goes both ways (e.g., theturlngway.org), and more associated with spammy content (though unsure how valid this is as an argument)

**Comment by KirstieJane** [comment]
Important question on accessibility @RaphaelS1 - thank you for raising it.

One point to emphasise wrt to the suggestion of having hyphens is that we have hyphens now so it becomes less of a change for the url. If we wanted to get rid of the hyphens we would arguably have to change the github repo and organisation name!

Personally I like the readability of the hyphens and I also don't think anyone remembers urls anymore anyway - I think folks will always find us through an external link or a search engine... but happy to be told I'm in the minority in that perspective!

I agree the squatting problem goes both ways - I don't think we're popular enough to have lots of people aiming to spoof us.... but open to best practices on how to avoid it!

**Comment by RaphaelS1** [comment]
Makes sense @KirstieJane, I think it's also mainly just a headache when there's an associated email !

**Comment by JimMadge** [comment]
I don't think there is an _infrastructure_ reason for choosing dashes or no dashes over the other. I think the infrastructure team are happy to be given a steer if there is a strong accessibility or branding reason to prefer one.

I think we definitely should have mailboxes at `the-turing-way.org` for much the same reasons as moving the domain.

**Comment by da5nsy** [comment]
@KirstieJane 
> If we wanted to get rid of the hyphens we would arguably have to change the github repo and organisation name

Just adding the info here that both of these changes are technically possible and it seems like they would be minimally disruptive (github would handle redirects)

**Comment by RaphaelS1** [comment]
*Very* happy to be told this is just a me problem but for mailboxes I personally struggle with hyphens, which I frequently forget and don't notice my mistake (e.g., I wouldn't notice the mistake in "hello@the-turingway.org"). Though I guess @KirstieJane comment still applies if we're not expecting people to remember the mailbox but to click on a 'contact us' or similar link from the website.

**Comment by KirstieJane** [comment]
> _Very_ happy to be told this is just a me problem but for mailboxes I personally struggle with hyphens, which I frequently forget and don't notice my mistake (e.g., I wouldn't notice the mistake in "[hello@the-turingway.org](mailto:hello@the-turingway.org)"). Though I guess @KirstieJane comment still applies if we're not expecting people to remember the mailbox but to click on a 'contact us' or similar link from the website.

Definitely agree about hyphens in email addresses. I guess I like them for URLs but not for emails and I don't feel strongly that they need to be harmonised (which might actually be the personal preference that's the difference between you and me @RaphaelS1!)

**Comment by KirstieJane** [comment]
> I don't think there is an _infrastructure_ reason for choosing dashes or no dashes over the other. I think the infrastructure team are happy to be given a steer if there is a strong accessibility or branding reason to prefer one.
> 
> I think we definitely should have mailboxes at `the-turing-way.org` for much the same reasons as moving the domain.

Do we need mailboxes at that url? We have a gmail email address and a turing institute address. Why do we need mailboxes that align with the domain url? What problem does that solve?

**Comment by KirstieJane** [comment]
> @sgibson91 6-12 months I would suspect is sufficient for the crawlers. I would suggest leaving the redirect in place to ensure the links from blogs, articles, etc stay alive if it's not a cost factor.
> 
> Overall it's good that this change is happening and gave it my thumbs up 👍
> 
> Note
> 
> One consideration we usually make at @libscie is that dashes or hard to spell elements increase likelihood of ending up on the wrong URL. `the-turing-way.org` may have a risk of misspelling. I can recommend going for `theturingway.org` or `turingway.org` if there is no hard brand identification with the dashes.

Thank you @chartgerink ! 🙏

**Comment by KirstieJane** [comment]
> Oh, by the way, could we update the _current_ site with an announcement (perhaps on the first page) that a major domain change is coning, and that the URL will be changing soon? There are two advantages:
> 
>     1. Visitors coming now will see the announcement that a change is coming.
> 
>     2. We can then archive the frontpage (along with the announcement) in places like the [Internet Archive](https://www.archive.org/) and others. This way, future generations can at least see the announcement in that archive that the URL has changed.

I think this is an important part of documenting the process - Can I ask the infrastructure working group to document a proposed the timeline incorporating these announcements and redirects? OR let me know if you'd like input from me / @malvikasharan / @aleesteele on the comms plan ✨

**Comment by aleesteele** [comment]
Adding this excellent note from @trallard here from Slack (with her permission!). She makes a great point: "The advantage of the hyphenated approach is that it is a lot more readable theturingway is definitely harder/takes longer to parse than the-turing-way 
Readability is important to consider especially for cognitive disabilities inclusion"

**Comment by JimMadge** [comment]
> I think this is an important part of documenting the process - Can I ask the infrastructure working group to document a proposed the timeline incorporating these announcements and redirects? OR let me know if you'd like input from me / @malvikasharan / @aleesteele on the comms plan ✨

:100:.
It feels like it would help to have one timeline to coordinate everything. Maybe we can write it in relative time,

- t=0, Domain purchased
- t=0+δt, Add domain to Netlify and configure DNS, Merge domain change announcement banner into book
- t=0+deploy time, trigger internet archive
- t=0+1 week, Email/Slack announcent
- t=0+1 month, Deactivate the-turing-way.netlify.app
- ...

Should I have a go at writing something like that (and adding it to the top comment here)? Input on the comms would be very helpful :pray:.

**Comment by malvikasharan** [comment]
That sounds good to me. Thank you, Jim. I can integrate some comms plan in there which might just mean that we are announcing first in Slack and Newsletter and then deactivating the older URL as you proposed.

The comms plan should have:
- What does this mean to you, the users? (likely not much, just a bit of change as the link will be redirected)
- What does this mean to the infrastructure working group who have so far maintained Netlify?
- What would this mean for the Turing Way project and the project delivery team (like keeping documentation of history, allocating budget for every year, communicating with the community etc)
- Anything else?

**Comment by aleesteele** [comment]
@JimMadge - thanks for preparing this! Love the notation! I've translated it into a (perhaps more traditional) communications plan, to get specific dates down for communicating with the wider community? My larger recommendation would be to stretch out the timelines, as things always take much longer than predicted :) 

- t<0
  - Create domain change announcement banner for book, but don't merge yet
- t=0
  - Domain purchased
- t=0+δt
  - Add domain to [Netlify custom domains](https://docs.netlify.com/domains-https/custom-domains/)
  - Configure DNS (A/AAAA records for book)
  - Merge domain change announcement banner into book
- t=0+deploy time
  - trigger internet archive to fetch book _including_ domain change announcement banner
- t=0+1 week
  - Email/Slack announcement about upcoming domain change
  - Set up redirect rules for the-turing-way.netlify.app to new domain (So anyone looking for old URLs should be _moved_ to the new one)
- t=0+3 week
  - Reminder Email/Slack announcement
- t=0+4 weeks
  - Replace all remaining the-turing-way.netlify.app links in book
- next (work that domain purchase enables, but not directly part of this migration)
  - Migrate hosting
  - Add DNS records for email (perhaps)

This is assuming that this timeline starts with the infrastructure meeting next week, and that this migration kicks off in March:

| Communication Activity | Target Audience | Who is involved & role | Timeline | Notes | Status
| -------- | -------- | -------- | ----- | ---- | --- |
| Preparation & planning | Infrastructure WG | ALS  & AAA | Aug 2023 - March 2024 |  Preparation and needs analysis for TTW url   | ✅ 
| First announcement on Slack for community vote | Wider community (soft launch on Slack) | @da5nsy posted on Slack  |  | | ✅ 
| Newsletter | Wider community/lurkers | ALS + AAA | January Newsletter | | ✅ 
| Newsletter | Wider community/lurkers | ALS + AAA | February Newsletter | | ✅ 
| Second announcement on Slack for community about timeline & upcoming domain change | Wider community (soft launch on Slack) | Infrastructure WG member posting reminder on Slack? | 7 March | | ✅ 
| Website announcement banner on book | Wider community/lurkers/users | Infrastructure WG + ALS | ***X DATE IN MARCH*** | | ✅ 
| Social media announcement (Linkedin, Twitter, Mastodon) | Wider community/lurkers/users | Infrastructure WG + ALS | ***X DATE IN MARCH*** | | ✅ 
| Newsletter | Wider community/lurkers | ALS + AAA | March Newsletter | | ✅

**Comment by AlexandraAAJ** [comment]
Thanks @aleesteele and @JimMadge. Jim, let me confirm you next Tuesday if we can proceed this way.

**Comment by KirstieJane** [comment]
Hi folks! I'll pay on my credit card for this year.

I'm struggling to see the final decision on the vote - could someone update the top level of this issue so that we have an easy to read historical record please? You can us the top level to link to specific comments rather than copying text.

**Comment by KirstieJane** [comment]
On a different note - I think the timeline is too ambitious but I could be convinced otherwise.

**Comment by malvikasharan** [comment]
25 people have upvoted for the-turing-way.org domain, with no disagreement.

My suggestion would be to reserve the domain for 5-10 years https://www.namecheap.com/domains/registration/results/?domain=the-turing-way.

**Comment by KirstieJane** [comment]
Thank you so much @da5nsy!

Domain purchased for 10 years!! 🚀 🌟 

EXCITING!

**Comment by AlexandraAAJ** [comment]
Adding here this to review with the community: https://docs.google.com/document/d/1Btjl1ryDlAwrAiRSVkbWTUORujPGUaQfhF8To9XtNKo/edit#heading=h.kehfirdlwxmb

**Comment by JimMadge** [comment]
Having a look at redirects, I don't think we can redirect `the-turing-way.netlify.app` to `book.the-turing-way.org` while we are still hosting on Netlify. Because `book.the-turing-way.org` has a `CNAME` rule pointing at `the-turing-way.netlify.app` I think it would be a circular redirect?

What we might have to do is prepare the redirects, then deploy a minimal Netlify site with a simple HTML file and the redirects to `book.the-turing-way.org`.

@sgibson91 does that sound right to you? Honestly not sure what happens when an HTTP redirect clashes with a CNAME rule 😱. Related to #3577.

**Comment by sgibson91** [comment]
@JimMadge Yeah, your reasoning and proposed path sound right
