### ISSUE TITLE
21-09-2023 Fireside Chat - Who is building Open Source AI?

### ISSUE THREAD

**Issue by dingaaling** [the-turing-way/the-turing-way#3269]
**The upcoming Fireside chat is on Date - Month - Year**

Info on the proposed session: https://github.com/the-turing-way/the-turing-way/issues/3236#issuecomment-1674606921

Register here to attend: [add registration page link].

## Before the Event -- at least 6-8 weeks in advance

- [x] Create a planning issue on GitHub using the [issue template - Fireside Chat Checklist](https://github.com/alan-turing-institute/the-turing-way/issues/new/choose)
- [x] A Turing Way team member (Community Manager or Research Project Manager) will create a Zoom link with a waiting room and live transcription enabled. They will also open the call on the day of the event, and give 'co-host rights' to all facilitators to allow them to manage Zoom participants and chats.
- [x] Identify an overarching theme that we share with a different community -- Fireside Chat is intended to promote cross-community collaboration
- [x] Reach out to a community representative who can co-facilitate the event with a core team member in The Turing Way
- [x] Set up an internal shared document for discussions and notes (The Turing Way shared google doc, see [this template](https://docs.google.com/document/d/1X_NfRkkH6p47yRgpd6xlw8yrvo6jIsbF_mV0BinjcaQ/edit?usp=sharing)) - https://docs.google.com/document/d/121r5uCkQJJMtkVII-lhm_R24zMJCVnKUWYZtYPuQM2o/edit?usp=sharing
- [x] Discuss what the co-hosts might want to highlight at this Fireside Chat (note: these discussions don't necessarily need to identify a solution but should recognise shared themes, challenges, and spaces for research communities - https://docs.google.com/document/d/121r5uCkQJJMtkVII-lhm_R24zMJCVnKUWYZtYPuQM2o/edit?usp=sharing
- [x] Identify speakers from the community and invite them
- [x] Create a private Slack Channels with all speakers and hosts and discuss some overarching topics they are interested in sharing: #open-source-ai
- [x] Ask for the bio and image of speakers, and their permission to record the session
- [x] Schedule the first check-in 4-5 weeks in advance to surface some common themes, helping plan the title and questions
- [x] Decide on a common date and send placeholder calendar invite blocking their calendar for the event (15 mins pre-event tech-check/Green room, 60 minutes live and 15-30 minutes unrecorded discussion with the audience)
- [x] Create an Eventbrite page in The Turing Way account -https://www.eventbrite.co.uk/e/who-is-building-openai-tickets-709277416847
- [x] Set up the Etherpad using the template provided here: https://hackmd.io/@turingway/fireside-chats (see [this example](https://pad.sfconservancy.org/p/ttw-fireside-chat-mar2022))
- [x] Create a paragraph to add to the Eventbrite page along with the speakers' and hosts' bio
- [x] Create a flyer to share on social media using [this template](https://docs.google.com/presentation/d/1Fx2WcVvGX6dM3z74VDQp_UD8edKp6Phl/edit?usp=sharing&ouid=102682705838770934280&rtpof=true&sd=true)
- [x] Coordinate with the speakers if they are happy with the announcements and if their info is correct
- [x] Announce at least 3-4 weeks in advance on Slack, Newsletter, Twitter and different talks
- [ ] Add information to the Intro hackmd: https://hackmd.io/@turingway/demo-intro
- [x] Hosts will define an agenda and questions for the session - hosts will also allocate some questions for each other to speak on
- [x] Set another check-in at least 2 weeks in advance to touch base and discuss the plans and questions with the speakers - assign 1-2 questions for each speaker to begin 
- [x] Plan with cohost who will ask which question, how you will time keep, what channel you will use to ask questions to each other privately, who will monitor the chat (maybe ask someone outside this group to help with note taking and chat monitoring)
- [x] Update the calendar invite with Zoom, Etherpad and Eventbrite -- encouraging them to share the Eventbrite page in their network
- [ ] Identify someone from the community who can do the introduction of The Turing Way, code of conduct reminder and pass it to the speakers

## During the session

- [x] Open the Zoom call 15 minutes in advance (keep the waiting room of Zoom enabled)
- [x] Test if speakers' microphone, camera and internet work alright - help troubleshoot any tech challenge
- [x] Let participants in right on time
- [x] Welcome them and share Etherpad
- [x] Remind them that the call will be recorded and that participants can use chat (but may not have the chance to speak during the 60 minutes live)
- [x] Start recording (on Zoom Cloud) and enable transcription
- [x] At 5 minutes past, as people join, the person designated to welcome them will introduce the Turing Way, CoC, and Etherpad information and Present the topic
- [x] Hosts then introduce themselves and post the opening questions allowing all speakers including the co-host to share their position on the topic in 2 minutes
- [x] As planned in the agenda, hosts ask the question posed to the specific speaker, follow up response from the other speaker is invited
- [x] Speakers will make sure that everyone on the panel has had an equal chance to discuss and share their opinions
- [x] Any question from the chat is copied over the Etherpad, in the last 10 minutes publically posed question can be asked
- [x] The recorded session finishes with a short closing arguments from each speaker and host
- [x] After the recorded part of the discussion (60-75 minutes), all participants are reminded of the next stage of unrecorded discussion informally with the speakers 
- [x] Hosts close the call after 90 minutes of the session (with 15-30 minutes unrecorded discussion)

## After the session

- [x] Send a thank you email to the speakers - within 1 day
- [ ] Archive all notes here: https://hackmd.io/@turingway/fireside-chats
- [x] Download the video from Zoom and edit the live transcription (proofread cc)
- [x] Upload the video on The Turing Way youtube - label and annotate well, and add the flyer as the video's front page
- [x] Share the published videos with the speakers
- [ ] Summarise the session to add to The Turing Way -- invite someone from the community who could do that 
- [ ] Promote the video via Slack, Newsletter, Twitter
- [x] Send a thank you email to the Eventbrite participants sharing the video and inviting any ideas and suggestions for improvement via a standard feedback form
- [ ] Update the book chapter and templates if needed
- [x] Update the video link here and update the section for the upcoming Fireside chat
- [ ] Add speakers to this GitHub repo using `all-contributions bot` for presentation
- [x] Close the planning issue as complete!

**Comment by aleesteele** [comment]
Adding here for posterity + notes that I am on eventbrite & etherpad duty 🦾

**Comment by dingaaling** [comment]
Next steps from 23 Aug chat:
- JD to email OSI to ask about 21 Sept event date (otherwise we will consider exploring 15 Sept)
- @aleesteele to reach out to new HOTOSM folks that her contacts suggested
- @Arielle-Bennett to check with Mophart on contact info/joining a speaker check in
- After date & speaker check ins confirmed, check with panellists if interest in pre recording

**Comment by dingaaling** [comment]
Final video: https://www.youtube.com/watch?v=e8EBI1ocxt4
