### ISSUE TITLE
Planning / Reviewing repository after transition to Github organisation

### ISSUE THREAD

**Issue by aleesteele** [the-turing-way/the-turing-way#3272]
## Summary
This issue is connected to #3213, which documents the need for a TTW github organisation. This transition was made on 11 August at the Infrastructure Working Group's meeting on 11 August. 

1. What does The Turing Way community need from this new organisation, now that this transition has been made?
2. How do we structure the repositories, projects, and sub-projects of the community to ensure continuity across groups?
3. What bugs & breakages might happen (or have already happened) after this transition?

## Documenting needs
🌶️  = urgent

_Working Groups - please feel free to edit this log! This is to keep track of larger timelines and needs after the splitting of the repository_

| Team and/or Person |  Need   |   Priority Level  |    Timeline      |  Status | 
| -------------------- | ------- | -------------- | -------------- | ------- | 
| All Contributors | Documenting process for getting access to Github organisation and/or repository | Urgent | |
| All Contributors | Splitting repository for ease of access to project | Urgent | Started trial after January 2024 Infrastructure WG meeting and Collaboration Cafe | Currently being done in #3352 - led by @da5nsy 
| All Working Groups | Archiving meeting notes and centralising/making open their activities | | January 2023 |
| Staff Delivery team | Archiving meeting notes and centralising/making open their activities | | |
| Accessibility WG | Creating repository for Accessibility WG | Medium | | ✅ Completed in November 2023
| Infrastructure WG | Creating repository for Infrastructure WG | Medium | | ✅  Completed in January 2024
| Translation and Localisation WG | Transfer forked TW Translation organisation to new TTW organisation | | |
| Translation and Localisation WG | Transfer language-specific organisat | | |
| Infrastructure WG | Reinstall bots lost during the transition | Urgent | November/December 2023 | Completed #3289 
| | | |

Key questions here might be:
- What should remain a folder in the main repository? 
- Should the working groups have their own repositories, or be centralised into one working group?

_If you are interested in commenting below_

### What needs to be done?
- [ ] All WGs to add upcoming issues
- [ ] Should a project board be made to help keep track of these changes?
- [ ] Is there any other mix of issues and questions here to keep track of?

### Who can help?

* All Working Groups and Community Members

**Comment by JimMadge** [comment]
Removing the infrastructure tag as all infra wg tasks are marked as completed :tada:
