### ISSUE TITLE
Do we want an org-level readme?

### ISSUE THREAD

**Issue by da5nsy** [the-turing-way/the-turing-way#3282]
### Summary

It is possible to have an org-level readme.
See https://github.com/data-umbrella

Do we want one?
If so, what should it communicate?

### Who can help?

Anyone (decision-making input)
Anyone with GitHub skills (implementation)

---

**Comment by Arielle-Bennett** [comment]
Yes I think we should have one to give people an idea of how the org is laid out and where to find things / who manages it - good idea @da5nsy !

**Comment by aleesteele** [comment]
Thanks for making this issue, @da5nsy after the CSCCE workshop last week!

I've followed the steps required to have a README at the organisational level, listed here: https://github.com/the-turing-way/.github

Are there particular sections we want to have there? I was thinking that the most urgent information would be to 
- direct people to contribute to the guides
- direct people to appropriate pages for community calls
- share links to other communication channels like this

What do folks think?

_Also adding breadcrumbs to #3272 and #3213_

**Comment by da5nsy** [comment]
Sounds good to me!

**Comment by aleesteele** [comment]
This has been made - woohoo! 🎉 I think we're ready to close, @da5nsy? Or do we want to make one for members as well? 😄

**Comment by aleesteele** [comment]
There are two types of READMEs you can make apparently, one is for members of an organisation, and the other is a public one. I grabbed a few screenshots.

<img width="1136" alt="Screenshot 2023-11-02 at 14 28 24" src="https://github.com/the-turing-way/the-turing-way/assets/18509789/059e9a7b-6225-4ab9-98d5-5638958ad42e">
This is an example of one for members.

<img width="1145" alt="Screenshot 2023-11-02 at 14 28 40" src="https://github.com/the-turing-way/the-turing-way/assets/18509789/79071ed0-096a-42db-972d-0fecd9257113">
This is the one that folks see more publicly.

**Comment by da5nsy** [comment]
My gut feeling is to keep it simple and have a single version for both members and public, but I don't have strong feelings on it. What do you think @aleesteele?

**Comment by KirstieJane** [comment]
Agreed that I don't think we need a difference between members of the organisation and non-members 😸

**Comment by Arielle-Bennett** [comment]
Yeah one document should suffice!

**Comment by aleesteele** [comment]
Sounds good @da5nsy, @KirstieJane, and @Arielle-Bennett! I think this is ready to close then, as we have one that we use currently 😄

**Comment by da5nsy** [comment]
OK, I had misunderstood the situation.
I assumed that if we just had one it would show up for both "members" and "public".
It now seems that if we want it to show up for "members" at all, we also need to have a private one.
Does this mirror your understanding @aleesteele?

If so, I propose we have a duplicate repo.
I'd prefer a way that didn't require duplicate versions that would have the potential to inadvertently diverge, but I don't currently see a way to do that.

**Comment by da5nsy** [comment]
Info source: https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/customizing-your-organizations-profile#adding-a-member-only-organization-profile-readme

**Comment by aleesteele** [comment]
Thanks @da5nsy - we were just talking about this at the coworking call, and I pulled up the same documentation as you, not realising that you had already posted it here. Sorry for my late response and for misunderstanding the points above! Yes, we'll need both a public and private repository. Just pulled up a pull request, if you'd like to take a look! 😄

**Comment by aleesteele** [comment]
Hiya folks - doing some github gardening and saw this - do we think we're ready to close @da5nsy?
