### ISSUE TITLE
Add NHS England as one of the organisations that use Data Wranglers, on `/collaboration/research-infrastructure-roles/data-wrangler.html`

### ISSUE THREAD

**Issue by AdamHollings** [the-turing-way/the-turing-way#3286]
Please can you add NHS England as one of the organisations that use Data Wranglers? I am a Data Wrangler at NHS England

NHS England uses Wranglers to support the NHS England Secure Data Environment. Their work supports a wide range of research done by researchers from HDRUK British Heart Foundation Data Science Centre related to heart disease and covid, as well as other organisations like DATA-CAN looking at the impact of covid on cancer treatment, as well as the Department of Health and Social Care ensuring that they have the data they need and its in an accessible format so they can advise the government leadership, plus more organisations besides

**Comment by aleesteele** [comment]
Hi @AdamHollings! Thanks for your note and a great point in adding NHS England. @RayStick and @Rainiefantasy drafted this page initially, so they can also help in making this edit in a PR as well. Let us know what you'd like to do, and we can help to get you sorted with this edit!

**Comment by AdamHollings** [comment]
Hello @aleesteele   @RayStick and @Rainiefantasy although I can use git I am bit unfamiliar with the organisation of this repo if you could make the change I would be grateful.  

Are we allowed to include paragraphs of text? If so the below has been approved by boss:

NHS England Data Wranglers support a wide range of research done by health and social care organisations using the National Secure Data Environment (NSDE) to ensure the data they need is in an accessible format. They also help suggest and test platform improvements, produce "here's one I made earlier" analysis (such as demographic analysis of data sets) to save user time and advise on data in a technical capacity.

If its just a name of an organisation and a link to a project then this would be fine:

NHS England
Project: [NHSE Secure Data Environment](https://digital.nhs.uk/services/secure-data-environment-service)

**Comment by RayStick** [comment]
Thanks @aleesteele and @AdamHollings 
I am happy to edit the page - will get to this later in the week
Thanks for reaching out @AdamHollings :D
