### ISSUE TITLE
Re-enabling bots after organisation transfer

### ISSUE THREAD

**Issue by da5nsy** [the-turing-way/the-turing-way#3289]
It looks like the bots didn't get transferred when moving organisation, so I'm going through and re-enabling them.
Making an issue to keep track of it, at @aleesteele's [request](https://github.com/the-turing-way/the-turing-way/issues/3213#issuecomment-1697307494).

Linked to #3272 and #3213

**Comment by da5nsy** [comment]
Re-installed all-contributors [here](https://github.com/the-turing-way/the-turing-way/issues/3213#issuecomment-1694426894)

**Comment by da5nsy** [comment]
Re-enabled welcome bot. Tested [here](https://github.com/the-turing-way/the-turing-way/pull/3288).

**Comment by da5nsy** [comment]
Ongoing issues with alt-text bot: #3290

**Comment by sgibson91** [comment]
I have reinstalled the in-solidarity bot for inclusive language. Testing here: https://github.com/the-turing-way/the-turing-way/pull/3353

**Comment by da5nsy** [comment]
Closing for now.
