### ISSUE TITLE
Alt-text bot not working

### ISSUE THREAD

**Issue by da5nsy-test** [the-turing-way/the-turing-way#3290]
Testing alt-text bot.
It didn't work [here](https://github.com/the-turing-way/the-turing-way/pull/3288#issuecomment-1716809329). Maybe it only works in the leading message for an issue/PR?

Linked to #3289.

Here is an example of it when it worked: https://github.com/the-turing-way/the-turing-way/issues/3039#issuecomment-1636751790

Here is the action: https://github.com/marketplace/actions/accessibility-alt-text-bot

Here is where our call to that action is: https://github.com/the-turing-way/the-turing-way/blob/35abf305c11804de15ee0c498499db57694e9360/.github/workflows/accessibility-alt-text-bot.yml

Here is an image without alt-text:
![](https://github.com/the-turing-way/the-turing-way/assets/144863405/d0797f05-971b-43b5-a302-e8b820478f44)

**Comment by da5nsy** [comment]
Here's another image without alt-text:
![](https://github.com/the-turing-way/the-turing-way/assets/3739866/6b440b8e-0b22-47ea-8691-9be0affe2aa2)
