### ISSUE TITLE
[NEW CHAPTER] - Planning Inclusive and Accessible Events

### ISSUE THREAD

**Issue by BrainonSilicon** [the-turing-way/the-turing-way#3307]
### Title

Organizing Inclusive Events

### Guide

Guide for Collaboration

### Draft(s)
> I've made a [Checklist](https://docs.google.com/document/d/1nDAdRwZAbMxys90TPvy2hKnea6E-TQoWq8DEEU60QsY/edit?usp=sharing) and [Gantt chart](https://docs.google.com/spreadsheets/d/11MX3QycuKZGiLPZKGishsjapSc8zJzI5WSpPwg-3xy8/edit#gid=0) to keep track of progress and tasks for the initial drafts during 2023. 

To read the chapter draft, please checkout the [`WIP-Inclusive-Events-chapter-Content`](https://github.com/the-turing-way/the-turing-way/tree/WIP-Inclusive-Events-chapter-Content/book/website/collaboration) branch. 

### Summary of proposed chapter

The chapter collates recommendations and guidance on how to plan and run events that include (or focus on) having people with a lived experience attend and take part. 

Its purpose is to supplement the existing guides on Organizing Conferences, Meetings, Collaboration Cafes, and running hybrid events; and to be specifically focused on the considerations needed to support people with lived experience and accessibility needs. 

### Who can help?

Anyone!

### How to help?

Please review and made suggestions to the content.
You can view the current drafts at the links below:
* The current drafts of the chapter content can be found in the [`inclusive-events`](https://github.com/the-turing-way/the-turing-way/tree/WIP-Inclusive-Events-chapter-Content/book/website/collaboration/inclusive-events) folder on the `WIP-Inclusive-Events-chapter-content` branch

**This chapter is separated into different subsections:**
- **Chapter Landing page**: [here](https://github.com/the-turing-way/the-turing-way/blob/WIP-Inclusive-Events-chapter-Content/book/website/collaboration/inclusive-events.md)
- **The core chapter content:** 
    - [Planning and Logistics](https://github.com/the-turing-way/the-turing-way/blob/WIP-Inclusive-Events-chapter-Content/book/website/collaboration/inclusive-events/inclusive-events-planning.md)
    - [Location](https://github.com/the-turing-way/the-turing-way/blob/WIP-Inclusive-Events-chapter-Content/book/website/collaboration/inclusive-events/inclusive-events-location.md)
    - [Communications](https://github.com/the-turing-way/the-turing-way/blob/WIP-Inclusive-Events-chapter-Content/book/website/collaboration/inclusive-events/inclusive-events-comms.md)
    - [Schedule and Agenda Planning](https://github.com/the-turing-way/the-turing-way/blob/WIP-Inclusive-Events-chapter-Content/book/website/collaboration/inclusive-events/inclusive-events-schedules.md)
    - [Networking and Social Events](https://github.com/the-turing-way/the-turing-way/blob/WIP-Inclusive-Events-chapter-Content/book/website/collaboration/inclusive-events/inclusive-events-socials.md)
    - [Technology and Hybrid Considerations](https://github.com/the-turing-way/the-turing-way/blob/WIP-Inclusive-Events-chapter-Content/book/website/collaboration/inclusive-events/inclusive-events-tech.md)
    - [Content Accessibility Guidance](https://github.com/the-turing-way/the-turing-way/blob/WIP-Inclusive-Events-chapter-Content/book/website/collaboration/inclusive-events/inclusive-events-content-guide.md)
    - Facilitation and Moderation (currently WIP, please make suggestions!!)
- **A checklist summarizing the content:** 
- **A page of resources:** 
    - many of these resources are linked below in this issue and will be compiled and sorted once the chapter content and tone has been finalized.

### Updates

- [X] Write chapter outline
- [X] Make WIP branch for the chapter
- [X] Write chapter landing page
- [X] Write first draft of chapter content
- [x] Work with the @the-turing-way/accessibility Working Group to redefine inclusion for the chapter
- [x] Edit and re-write after reviews
- [ ] Add images to the content accessibility chapter
- [x] Brainstorm and draft Facilitation and Moderation section
- [x] Align to TTW style guide
- [ ] Write chapter checklist
- [x] Organize the resources section for the chapter (see below)
- [x] Combine materials into a readable chapter
- [x] Proofread
- [x] Add in cross-references to checklist and chapter subsections
- [x] Add pages to toc file
- [x] Create PR and link in the comments
- [x] Request reviews
- [x] Address reviews
- [ ] Merge to main branch

### Resources

* https://equity.ubc.ca/resources/accessible-and-inclusive-event-planning/
* https://www.ucl.ac.uk/equality-diversity-inclusion/equality-areas/disability-equality/tips-checklist-making-events-accessible
* https://www.metadocencia.org/en/post/perfiles_accesibilidad/
* https://autisticadvocacy.org/wp-content/uploads/2019/05/Accessible-Event-Planning.pdf
* https://universaldesign.ie/what-is-universal-design/the-7-principles/the-7-principles.html 
* https://sites.google.com/nihr.ac.uk/pi-standards/home 
* https://warwick.ac.uk/fac/soc/impact/policybriefings/6_creating_inclusive_conferences_for_academics_with_caring_responsibilities.pdf
* https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1010164 
* https://accessibility.blog.gov.uk/2016/09/02/dos-and-donts-on-designing-for-accessibility/
* https://shapingourlives.org.uk/report/my-voice-matters/
* https://pad.sfconservancy.org/p/ttw-etherpad
* https://inclusivecommunication.scot/how-to-organise-an-inclusive-and-accessible-event
* https://communications.admin.ox.ac.uk/how-to-plan-and-run-an-accessible-online-event#collapse2035421
* https://www.makethingsaccessible.com/guides/running-accessible-events/
* https://www.friendlylikeme.com/access-spotlight/creating-accessible-events
* https://www.ioic.org.uk/events/event-training-calendar/accessible-communication.html
* [How to Plan a Conference with event interpretation for Deaf people](https://www.signsolutions.uk.com/how-to-plan-a-conference-with-event-interpretation-for-deaf-people/)
* https://www.priyaparker.com/book-art-of-gathering
* https://fakequity.com/2022/07/29/be-a-better-meeting-host-with-relationship-building-questions/ 
* https://www.tamarackcommunity.ca/library/ten-2019
* https://www.seemescotland.org/media/11340/lived_experience_report_2022_web.pdf
* https://www.autism.org.uk/get-involved/raise-money/do-your-own-thing/how-to-guides/holding-an-event
* https://forequity.uk/general-resources/
* https://helenkara.com/2022/07/14/the-value-and-limitations-of-lived-experience/
* https://camdenhealth.org/blog/understanding-preferred-language-for-people-with-lived-experience/
* https://www.youtube.com/watch?v=Ms6BrG-RJJI
* https://www.youtube.com/watch?v=8I4wA52BPGU
* https://docs.google.com/presentation/d/1kwHq6UYSOFWCjOrDCgcvmxByCX_dOr1qmBE7gAbj12s/edit#slide=id.g1a353fcaebd_0_18
* https://docs.google.com/presentation/d/1k6Sft7YH2QrDzqzE6TZhociWVjXe7rLMDjAJ734qNKA/edit#slide=id.g1cd292f458d_0_19
* https://www.washington.edu/accesscomputing/are-text-only-web-pages-accessible-alternative
* https://www.loopify.com/blog/accessibility-in-email-marketing/
* https://abilitynet.org.uk/sites/abilitynet.org.uk/files/Creating-accessible-documents-Easy-Read.pdf?utm_source=Website0&utm_medium=CreatingAccessibleDocsEasyReadPDF&utm_campaign=EasyRead
* https://accessibility.huit.harvard.edu/design-readability
* https://www.kent.ac.uk/guides/accessible-content/accessible-documents
* https://www.colorado.edu/digital-accessibility/pdfs
* https://amimagazine.global/Meetings/Planning-and-design/10-ways-to-create-inclusive-events
* https://theworldcafe.com/key-concepts-resources/design-principles/
* https://theworldcafe.com/key-concepts-resources/world-cafe-method/
* https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7237562/
* https://arc-nenc.nihr.ac.uk/news/the-world-cafe-is-an-unmethod-within-co-produced-research/
* https://www.imperial.ac.uk/media/imperial-college/medicine/perc/PERCs-Rough-Guide-to-Public-Involvement---Dec-2021.pdf
* https://www.imperial.ac.uk/patient-experience-research-centre/ppi/ppi-resource-hub/
* https://www.nihr.ac.uk/documents/briefing-notes-for-researchers-public-involvement-in-nhs-health-and-social-care-research/27371
* https://www.nihr.ac.uk/documents/ppi-patient-and-public-involvement-resources-for-applicants-to-nihr-research-programmes/23437
* https://www.england.nhs.uk/wp-content/uploads/2014/03/bs-guide-plann-part1.pdf
* https://www.england.nhs.uk/wp-content/uploads/2016/07/bitesize-guide-event-planning.pdf
* https://www.nihr.ac.uk/documents/improving-inclusion-of-under-served-groups-in-clinical-research-guidance-from-include-project/25435
* https://www.rdsblog.org.uk/what-s-going-on-i-feel-a-bit-wobbly-crafting-power-dynamics-at-a-public-involvement-event
* https://dareuk.org.uk/wp-content/uploads/2023/06/Public-Involvement-and-Engagement-PIE-Guidelines-for-DARE-UK-Projects.pdf
* https://www.adruk.org/fileadmin/uploads/adruk/Documents/PE_reports_and_documents/PEDRI-Best-Practice-Standards.pdf?_hsenc=p2ANqtz-9I-CNND1ExG4qFNhAixF7DgzUPmx2l6OdSTF524XH1QkQi0TUdR7BnLxfzePrRtOMF48_K
* https://zenodo.org/records/8061622
* https://www.hdruk.ac.uk/news-opinion-events/opinion/?_areas_of_work=public-engagement
* https://www.amrc.org.uk/guidance-and-tools-for-public-involvement
* https://www.ukri.org/blog/creative-communities-co-creating-inclusive-innovation/
* https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6067369/
* https://www.learningforinvolvement.org.uk/content/resource/nihr-involving-children-and-young-people-as-advisors-in-research/?
* https://www.invo.org.uk/resource-centre/resource-for-researchers/
* https://www.hdruk.ac.uk/wp-content/uploads/2023/04/Resource-Survey-Report-Final.pdf
* https://iris.who.int/bitstream/handle/10665/367340/9789240073074-eng.pdf?sequence=1
* https://universaldesign.ie/what-is-universal-design/definition-and-overview/definition-and-overview.html
* https://accessible-toilets.co.uk/2019/02/07/all-about-emergency-cords/ 
* https://www.ucl.ac.uk/equality-diversity-inclusion/equality-areas/disability-equality/tips-checklist-making-events-accessible
* https://tec.scot/sites/default/files/2023-07/Digital%20Pillars%20Paper%20(July%202023).pdf
* https://shapingourlives.org.uk/wp-content/uploads/2023/08/How-we-can-help-you-June-2023.pdf
* https://shapingourlives.org.uk/report/my-voice-matters/
* https://shapingourlives.org.uk/wp-content/uploads/2023/01/Accessible-venues-V3.png
* https://arc-em.nihr.ac.uk/sites/default/files/field/restricted/Preparing%20for%20Implementation_Module%202_V2.pdf
* https://www.friendlylikeme.com/access-spotlight/interpride-san-diego
* https://www.friendlylikeme.com/access-spotlight/atlanta-pride-accessibility-guide
* https://www.friendlylikeme.com/access-spotlight/mental-health-awareness-in-individuals-with-specific-needs
* https://www.friendlylikeme.com/access-spotlight/are-you-comfortable
* https://disabilityequality.scot/easy-read/
* https://rnid.org.uk/information-and-support/technology-and-products/
* https://www.mind.org.uk/media-a/4743/mind-lived-experience-influnce-and-participation-policy.pdf
* https://www.england.nhs.uk/long-read/case-study-how-peoples-lived-experience-is-improving-health-and-care-services-in-the-north-east-and-north-cumbria/
* https://www.york.ac.uk/media/abouttheuniversity/equality/documents/Inclusive-and-accessible-events-good-practice-guidelines.pdf
* https://venues.mmu.ac.uk/wp-content/uploads/2017/03/Planning-Inclusive-Events.pdf
* https://www.portsmouth.gov.uk/wp-content/uploads/2020/05/development-and-planning-design-guide-for-wheelchair-accessible-housing.pdf
* https://www.mos.org/sites/dev-elvis.mos.org/files/docs/offerings/PES_guide_10_20r_HR.pdf
* https://warwick.ac.uk/fac/soc/impact/policybriefings/6_creating_inclusive_conferences_for_academics_with_caring_responsibilities.pdf
* https://mathison.turing.ac.uk/page/2888
* https://www.equalityhumanrights.com/sites/default/files/housing-and-disabled-people-engaging-with-disabled-people-event-planning-guide.pdf
* https://www.glam.ox.ac.uk/workshops-adults-learning-disabilities
* https://www.independentliving.org/docs2/daakit45.html
* file:///Users/sbatchelor/Downloads/Report-of-engagement-activity-with-stroke-survivors-and-carers.pdf
* https://www.citizensadvice.org.uk/Global/CitizensAdvice/Equalities/How%20to%20run%20focus%20groups%20guide.pdf
* https://irep.olemiss.edu/wp-content/uploads/sites/98/2016/05/Trinity_Duke_How_to_Conduct_a_Focus_Group.pdf
* https://www.gov.uk/service-manual/helping-people-to-use-your-service/understanding-wcag
* https://www.w3.org/WAI/standards-guidelines/wcag/
* https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG/Robust
* https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG/Understandable
* https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG/Operable
* https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG
* https://www.ioic.org.uk/events/event-training-calendar/accessible-communication.html
* https://www.friendlylikeme.com/access-spotlight/creating-accessible-dining-spaces
* https://www.friendlylikeme.com/access-spotlight/creating-accessible-events
* https://www.makethingsaccessible.com/guides/running-accessible-events/
* https://communications.admin.ox.ac.uk/guidance-for-planning-and-organising-accessible-events#collapse2055661
* https://communications.admin.ox.ac.uk/how-to-plan-and-run-an-accessible-online-event#collapse2035421
* https://inclusivecommunication.scot/how-to-organise-an-inclusive-and-accessible-event
* https://hodigital.blog.gov.uk/2016/12/28/designing-for-accessibility-an-update-on-our-accessibility-posters/
* https://www.signsolutions.uk.com/how-to-plan-a-conference-with-event-interpretation-for-deaf-people/
* https://www.signsolutions.uk.com/working-with-sign-language-interpreters-for-events/
* https://www.councilofnonprofits.org/articles/making-your-events-accessible-deaf-and-hard-hearing
* https://rnid.org.uk/information-and-support/deaf-awareness/making-your-event-deaf-aware/

**Comment by BrainonSilicon** [comment]
If anyone has suggestions for the Chapter please comment! So far I've come up with: 
- Hosting Inclusive Events: People with Lived Experience
- Inclusive event planning
- Including the public at events 
- Organizing Inclusive events
- Organising Accessible events

**Comment by BrainonSilicon** [comment]
Making a comment here so that it's captured for when the chapter gets merged. @srtee helped with ideation and reviewing initial drafts of the chapter landing page, and chapter content (introduction section and first draft of planning/logistics section) during Collaboration Cafe today.

**Comment by AlexandraAAJ** [comment]
Hi Sophia, I should also flag that the etherpad document was a contribution of the accessibility working group.

**Comment by gcroci2** [comment]
Hi all, have you tagged me on purpose? I didn't know to be involed in this at all, so I am a bit confused ;)

**Comment by malvikasharan** [comment]
Hi @gcroci2, we have another team member called Giulia, who is not already a contributor on this repo, which is where Sophia made a mistake in tagging. Please do mute this thread. Otherwise, you are very welcome to join the conversation if the topic is of your interest too. :)

**Comment by BrainonSilicon** [comment]
> Hi @gcroci2, we have another team member called Giulia, who is not already a contributor on this repo, which is where Sophia made a mistake in tagging. Please do mute this thread. Otherwise, you are very welcome to join the conversation if the topic is of your interest too. :)

Echoing this and apologies @gcroci2! I'll edit the issue now and apologies for causing the confusion. You are more than welcome to stay involved if this is something that interests you - but otherwise I am very sorry for the mix up!!

**Comment by EstherPlomp** [comment]
This links in with #3279 - or at least I think so because I haven't read your full issue yet! But would be good to keep this linked!

**Comment by BrainonSilicon** [comment]
> This links in with #3279 - or at least I think so because I haven't read your full issue yet! But would be good to keep this linked!

I definitely think it can (and should!) link in.

I tried to focus this chapter to address and highlight things that may be different about planning events that involve people with lived experience - but there's so much that can be built upon here. And also "people with lived experience" is so broad and includes people who will be attending events that don't necessarily have a participation aspect to them too.

**Comment by BrainonSilicon** [comment]
> This links in with #3279 - or at least I think so because I haven't read your full issue yet! But would be good to keep this linked!

Hi @EstherPlomp! 

I'm about to start work on the Programming and Agenda subsection. I think there's a lot of wonderful thinking and content that had been brainstormed at the OSF2023NL session that would go really well in that section. 

I am working on the draft this week, and if you/any of the folks who contributed want to add in ideas - please let me know (I think it would be awesome but also totally okay if it ends up going into a different section of TTW).

**Comment by EstherPlomp** [comment]
I can have a look at things during the next collaboration cafe! That is unfortunately the earliest I would have time for this :(

**Comment by BrainonSilicon** [comment]
Based on some feedback from @gedankenstuecke in PR #3327 (Communications subsection). I'm going to be adding some new subsections. 

This is to make the content easier to read, and more uniform in depth. 

Currently, the suggested new subsections will be:
- Networking 
- Guide for Facilitators
- Content Accessibility

**Comment by EstherPlomp** [comment]
Hi @BrainonSilicon! I think I missed a lot in the past month - gmail thought it was necessary to block all my notifications 😢 . Let me know if there's anything I can do to help at this stage!
