### ISSUE TITLE
Capturing Nov 2023 Book Dash Participant's information in the contributors file 

### ISSUE THREAD

**Issue by AlexandraAAJ** [the-turing-way/the-turing-way#3322]
## Summary

All Book Dash participants (13-17 November 2023) will capture their contributions in this issue.
Info will be copied over to the [Contributors file](https://github.com/the-turing-way/the-turing-way/blob/main/contributors.md). (Participants can directly edit this file and comment below with a PR if they prefer.)

The info will appear after merging in the GitHub repo on [Record of Contributions](https://the-turing-way.netlify.app/afterword/contributors-record.html).

### What needs to be done?

Please make sure that you share your feedback and experience from the last 5 days with us in this document: 

- [ ] Comment below your details in the following format (Paul's bio/details below for example)
- [ ] In your highlight you can also provide links to your issues and PRs

**Template**
---
* Role: Book Dash participant (2023)
* GitHub id: 
* ORCID: 
* Short bio:
> write here ...
* Personal highlights:
> write here ...
* More information:
> write here ...
* Quotes:
> write here ...

**Example**
---
### Paul Owoicho

* Role: 
  * Google Season of Doc: Technical Writer (2021)
  * Book Dash Participant (2021)
* GitHub id: [paulowoicho](http://github.com/paulowoicho)
* ORCID: TBA
* Short bio:
> I am a Technical Writer / Google Season of Docs (GSoD) Participant working to make The Turing Way consistent, sustainable, and accessible.
> I have a BSc in Software Engineering from the American University of Nigeria. Thereafter, I worked as a Research Analyst in the Fintech & Innovation Division of Guaranty Trust Bank, Nigeria and helped to drive the Bank's push to become a platform by creating innovative digital products.
> I completed a Master's in Data Science from the University of Glasgow and starting my PhD in January 2021 studying conversational information-seeking systems. I spent two years as a Research Analyst at Guaranty Trust Bank in Lagos, Nigeria helping to build innovative digital products to meet the Bank's customer objectives.

* Personal highlights:
> The Turing Way is my first foray into open source and has been a fantastic learning experience.
> Not only have I gained a deeper understanding and appreciation for how GitHub works, but I am also learning to prioritise sustainability and empowerment in the work that I do.
> Although The Turing Way is my first open source project, I thoroughly enjoyed the experience and learned a lot along the way. Before the GSoD program, I only used Github to 'store' my projects. Now, I am much more proficient at using Github for collaborative endeavours and I am more adept at working with tools such as Markdown, Jupyter Book, and Sphinx. In addition, I gained familiarity with setting up and working with web analytics software.
> You can see the full report from GSoD participation [here](https://github.com/alan-turing-institute/the-turing-way/blob/master/communications/GSOD-applications/GSoD-2020-Project-Report.md).
> The BookDash November 2020 was great! It was awesome to meet, collaborate, and share ideas with people from around the world. Beyond the Book Dash, The Turing Way is the very first open-source project I have ever worked on. The experience has been fantastic, and I intend to stick around as a contributor after the Google Season of Docs program ends. I also see myself getting involved in other open-source projects.

* Personal Quote:
> Asides technical skills, I developed a deep appreciation for what working on an open source project entails. My mentors helped me realise that the value I left behind from the GSoD program was not in the amount of work I did, but how I enabled other contributors to also do the work I was doing. As a result, I learned to contribute as a Technical Writer in a manner that was reproducible, sustainable, accessible, and inclusiv

---

### You can also add sections on:

* Pull requests: 
  * Authored:
  * Reviewed:
* Skills/knowledge you developed through The Turing Way
* Outreach or engagement work you undertook for The Turing Way community
  * These could be a social event you facilitated during the Book Dash, post-event blog post you wrote, previous talks/tutorials/training etc you delivered related to The Turing Way...
* Any data science research/practices that have changed and improved as a result of working on The Turing Way

### Who can help?

All Book Dash attendees

### What happens next

- We will use this to add to our report from the event (see #3210 )
- Finally, we will ask for your permission to give you the spotlight in one of our next newsletters

**Comment by kallewesterling** [comment]
### Kalle Westerling

* Role: 
  * Book Dash Participant (2023)
* GitHub id: [kallewesterling](http://github.com/kallewesterling)
* ORCID: 0000-0002-2014-332X
* Short bio:
> Dr Kalle Westerling is a Research Application Manager at the [Turing Research and Innovation Cluster in Digital Twins (TRIC: DT](https://www.turing.ac.uk/research/research-projects/tric-dt)). He works with the TRIC: DT team of scholars to aid them in providing open and reproducible computational and social tools that are accessible to the UK research and innovation communities, keeping the user perspective prioritised in the development of research software, and to ensure the longevity, sustainability, and collaborative open-source advancement of these vital tools.
> Prior to joining the Alan Turing Institute, Kalle was a Research Software Engineer with the [Living with Machines](https://www.turing.ac.uk/research/research-projects/living-machines) collaboration between the British Library, the Alan Turing Institute, and researchers from a range of UK universities. In that role, he developed new digital research methods, tools and ways of working with historical collections at scale.
> Kalle holds a PhD in Theatre and Performance Studies from The Graduate Center, City University of New York (CUNY), where he visualised and analysed networks of marginalised, itinerant nightlife performers in the 1930s. In the United States, Kalle managed the Scholars program at HASTAC and the Digital Humanities Research Institute at CUNY, both efforts across numerous higher education institutions, aiming to build nation-wide infrastructures and communities for digital humanities skill-building.

* Personal highlights:
> I am excited to become more involved with The Turing Way community after the inspiring experience of this Book Dash.
> During the event, I learned a tremendous amount about JupyterBook. Learning more around the syntax for referencing, adding images, and captions was particularly good for me :) 
> This experience has definitely empowered me to dive into other open-source projects, explore more hackathons, and engage in similar collaborative efforts across the open-source community.
> I also learned more about how to manage the all-contributors bot... and when to give up and just re-start completely!
> I reviewed more pull requests than ever before in such a short span — super fun!
> My role also included a lot of cheering on from the sidelines, a supportive effort to encourage the closure of more pull requests... I love to see a closed PR!!
> Using a Miro board to restructure an entire section of The Turing Way was a big highlight too. It provided an opportunity to collaborate hands-on with colleagues I hadn't worked with closely before. It was not only productive but also brought, for me, a sense of teamwork and community.

* Personal Quote:
> I had an absolutely exhilarating time participating in The Turing Way Book Dash! It was a hands-on, engaging experience where I learned how to embed images into the pages, witnessing the book evolve in real-time with the content we were adding. What made the event stand out was its warm, inviting atmosphere — it transformed my usual solitary days spent in my home-office into a vibrant hub of collaboration. I felt like I was sharing my space with this amazing global community of brilliant minds. It was an unforgettable experience that not only enhanced my technical skills but also provided a sense of connection and camaraderie that I will remember especially, from this week together.

**Comment by aleesteele** [comment]
Closing this for now as this was merged! 🚀
