### ISSUE TITLE
[BUG] Broken Link in Org-level readme

### ISSUE THREAD

**Issue by Arielle-Bennett** [the-turing-way/the-turing-way#3341]
### Description

- Attempting to access the guides using the link provided in the readme file produces the error below (screenshot shows "404 page not found - The main branch of .github does not contain the path the-turing-way.netlify.app.") 

<img width="766" alt="image" src="https://github.com/the-turing-way/the-turing-way/assets/74651964/2ec61cc4-cc44-41f0-bfd1-882973edc133">

This probably needs the hyperlink updating?

**Comment by JimMadge** [comment]
@all-contributors please add @Arielle-Bennett for bug
