### ISSUE TITLE
[TO EDIT] community-handbook fixing minor typos

### ISSUE THREAD

**Issue by llewelld** [the-turing-way/the-turing-way#3346]
### Summary

While reading through the Community Handbook I'm discovering a few very minor but otherwise (I think) uncontroversial typos. For examples:
1. On the [local-build.md](https://the-turing-way.netlify.app/community-handbook/local-build) page there is a missing bracket in the first paragraph that breaks the Jupyter Book link.
2. On the [coc-enformcement.md](https://the-turing-way.netlify.app/community-handbook/coc/coc-enforcement) page, "about someone is the committee" should be "about someone on the committee".
3. On the [style-crossref.md](https://the-turing-way.netlify.app/community-handbook/style/style-crossref) page, "placeholder for subchapter's name" should be "placeholder for the subchapter's name".

These are all minor things, but look easy to fix, and I'm hoping also an easy way for me to make my first pull request and understand the processes involved.

### What needs to be done?

The proposed change would leave the structure as it is but just make minor changes to the wording, alongside small changes to syntax and punctuation.

### Who can help?

Checking the git history it looks like at least @malvikasharan and @arronlacey were involved withe the writing of the relevant chapters.

### Updates

- [ ] First set of edits to chapter/subchapter
- [ ] Proofread
- [ ] Request reviews
- [ ] Address reviews
- [ ] Merge to main branch

**Comment by llewelld** [comment]
I'm collecting the suggestions in PR #3347 as I read through.

**Comment by aleesteele** [comment]
You rock, @llewelld! Thank you for doing this! 🙏
