### ISSUE TITLE
[TO EDIT] community-handbook/style/style-crossref streamline example cases

### ISSUE THREAD

**Issue by llewelld** [the-turing-way/the-turing-way#3349]
### Summary

On the "community-handbook/style/style-crossref" page, ["Examples of cross-referencing"](https://the-turing-way.netlify.app/community-handbook/style/style-crossref#examples-of-cross-referencing) section, there are several cases provided for how to include cross references.

The cases are really clear and helpful; however looking carefully at the following three cases:

1. Cross-referencing a section within the same file before the reference.
2. Cross-referencing a section within the same file after the reference.
3. Cross-referencing a section within a different file.

It looks like (unless I'm missing something, which I may well be) the three cases use the same approach. 

I was wondering  if the advice might be simpler and made clearer if the three cases were combined into a single case, so that the question of whether a reference appears before, after or on a separate page can be avoided.

This is just an idea that occurred to me while reading through the section, which I found to be generally very clear and helpful.

### What needs to be done?

 - [ ] Consider whether there's a reason for having three cases that I missed.
 - [ ] Consider whether the change makes things clearer, or less clear.
 - [ ] Combine the three cases into a single case, noting that "it doesn't matter whether the label appears before or after the reference, or even on a completely different page" (or similar).

### Who can help?

From the git log it looks like the examples cases were originally added by @pgadige in commit 438de8a02bf2296b21cff1f96e5ae0d46bacc0b5. It would be especially helpful therefore to get @pgadige's opinion on this proposal.

### Updates

- [ ] First set of edits to chapter/subchapter
- [ ] Proofread
- [ ] Request reviews
- [ ] Address reviews
- [ ] Merge to main branch

**Comment by kallewesterling** [comment]
I agree with the above -- there are no reasons for indicating that there is a difference between these examples, and that perhaps it could be reframed as three variants of the same example. I like the suggestion to add a note that "it doesn't matter whether the label appears before or after the reference, or even on a completely different page".

I might also add that it would perhaps be interesting to readers to learn about the option to add a label to the link:

```
{ref}`Project Design <pd-overview>`
```
