### ISSUE TITLE
RDM chapter - section on finding data?

### ISSUE THREAD

**Issue by EstherPlomp** [the-turing-way/the-turing-way#3360]
### Summary

We don't really have a section on finding data and how to approach this. 

### What needs to be done?

Extend the following info: 

You can find data to reuse via: 
* Direct browsing of discipline-specific and multidisciplinary repositories 
* B2FIND data search (http://b2find.eudat.eu/)
* BASE (https://www.base-search.net/) (seems very specific to bielefield?)
* DataCite Metadata Search (https://search.datacite.org/)
* Europäisches Datenportal (https://www.europeandataportal.eu/de)
* Google Dataset Search (https://datasetsearch.research.google.com/)
* Search in data journals (link to the data journal section)
* EOSC? :P

You need to check the license if you can actually reuse the data!

After a metadata check to see if the data is of use to you, you'll need to evaluate the dataset more closely. The following questions may help you to do so: 

* What was the original research question? 
* How was the data collected? Are the collection and processing methods appropriate to answer my research question?
* Is the data collection process well documented? Which instruments were used? What settings/parameters? 
* Are protocols of the data collection shared?
* Is there sufficient information available to understand the dataset and its context/origin?
* Is the information complete, understandable and consistent?

You'll need to cite the data to provide credit to the original data creator(s)!

### Who can help?

* @EKaroune 
* Anyone interested in the topic

**Comment by EKaroune** [comment]
Happy to help - I will start thinking of a few places for searching for data.
EOSC - https://eosc-portal.eu/ 
EOSC marketplace - data catalog - https://search.marketplace.eosc-portal.eu/search/dataset?q=*&standard=true&exact=false&radioValueAuthor=A&radioValueExact=A&radioValueTitle=A&radioValueKeyword=A

**Comment by EKaroune** [comment]
List of national data infrastructure includes data repositories: https://rdmkit.elixir-europe.org/national_resources

**Comment by EKaroune** [comment]
Started a hackmd for draft: https://hackmd.io/@d6CiydavSD6KFFgSIBMlGg/SkIi1OyNT

**Comment by RichardJActon** [comment]
Another one for the list: FAIRsharing.org https://fairsharing.org/

**Comment by EstherPlomp** [comment]
Closing this issue since we addressed this with #3369!
