### ISSUE TITLE
[UPDATED CHAPTER] - Electronic Laboratory Notebooks

### ISSUE THREAD

**Issue by RichardJActon** [the-turing-way/the-turing-way#3434]
### Title

Electronic Laboratory Notebooks

### Guide

Reproducible Research

### Draft

https://hackmd.io/2iTX4NYCSwyY-OOy7CQwQQ

### Summary of proposed chapter

Why and Why not to use ELNs and how to choose and ELN

See the Draft it's moderately advanced as it borrows (very) heavily from my previous writing on the subject: https://data-guide.hdbi.org/04-working-with-data.html#sec-elns

Could be an update to the open notebooks chapter - This is was I was originally thinking but might warrant it's own section

### Resources

https://data-guide.hdbi.org/04-working-with-data.html#sec-elns

### Who can help?

- users of ELNs / LIMs systems 
- developers of ELNs / LIMs systems 
- admins of ELNs / LIMs systems

### Updates

- [ ] Write chapter outline
- [ ] Add material to the chapter
- [ ] Combine materials into a readable chapter
- [ ] Proofread
- [ ] Create PR and link in the comments
- [ ] Request reviews
- [ ] Address reviews
- [ ] Merge to main branch

**Comment by EstherPlomp** [comment]
Nice! Have you s[een the section on it in the RDM chapter](https://the-turing-way.netlify.app/reproducible-research/rdm/rdm-methods#electronic-lab-notebooks)?
