### ISSUE TITLE
Duplicated Scriberia Images

### ISSUE THREAD

**Issue by acocac** [the-turing-way/the-turing-way#3438]
### Summary

The scriberia illustration of carbon footprint is duplicated in the The Environmental Impact of Digital Research sub-chapter.

The PR #3376 added a new image with ALT text, however the same image exists (with different colour palettes) before the [data section](https://the-turing-way.netlify.app/ethical-research/activism/activism-env-impact#schedule-tasks-at-low-emission-time)

### What needs to be done?

Leave a single illustration, maybe the one with alt-text.

I'd suggest to double check if duplicates exist in other PRs mentioned in #3331.

### Who can help?

@aleesteele @kallewesterling @EKaroune

### Updates

- [ ] First set of edits to chapter/subchapter
- [ ] Proofread
- [X] Request reviews
- [ ] Address reviews
- [ ] Merge to main branch

**Comment by kallewesterling** [comment]
Oops! This is my fault, and I'll make sure to change it!

**Comment by aleesteele** [comment]
Thank you for catching, @acocac! I'll review the PR.
