### ISSUE TITLE
More Resources For Data Visualization Chapter

### ISSUE THREAD

**Issue by RichardJActon** [the-turing-way/the-turing-way#3441]
Additional Resources and references for the Data Visualization chapter
https://the-turing-way.netlify.app/reproducible-research/rdm/rdm-visualisation.html#data-visualisation

### Training & Workshops

-   

### Books

-   [Building Science Graphics](https://openlibrary.org/works/OL28353366W/Building_Science_Graphics) - I leave my copy of this one in the fishbowl if anyone wants to borrow it
-   [A Field Guide to Digital Color](https://openlibrary.org/works/OL6130168W/A_Field_Guide_to_Digital_Color)
-   [The Grammar of Graphics](https://openlibrary.org/works/OL18235300W/The_grammar_of_graphics)
-   [The Visual Display of Quantitative Information](https://openlibrary.org/works/OL2824012W/The_Visual_Display_of_Quantitative_Information)

### Podcasts

-   [Data Viz Today](https://dataviztoday.com/)
-   [Data Stories](https://datastori.es/)
-   [PolicyViz](https://policyviz.com/podcast/)

### Video

-   Outline of grammar of graphics
    -   [A Grammar of Graphics](https://www.youtube.com/watch?v=RCaFBJWXfZc) - Excellent summary of the grammar of graphics layers or 'functional pipeline'
    -   [Leland Wilkinson - The Grammar of Graphics](https://www.youtube.com/watch?v=1X93Sum_SyM) - Leland himself giving a quick high level summary of the grammar of graphics
-   [Martin Krzywinski: A pandemic of bad charts](https://www.youtube.com/watch?v=_YGmfsKL8N8)
-   [EMBL Keynote Lecture 2019 - Data visualization and data science, Hadley Wickham](https://www.youtube.com/watch?v=9YTNYT1maa4)
-   Practical high level intros to Tufte's principles
    -   [What should we do to improve our graphics and figures?](https://www.youtube.com/watch?v=00Fha1lkRxk)
    -   [Graphical Excellence](https://www.youtube.com/watch?v=VkyzSAPkQ50)

### Organizations

-   [biovis](http://biovis.net/)

### Websites & Blogs

-   [A Comprehensive Guide to the Grammar of Graphics for Effective Visualization of Multi-dimensional Data](https://towardsdatascience.com/a-comprehensive-guide-to-the-grammar-of-graphics-for-effective-visualization-of-multi-dimensional-1f92b4ed4149) - a shorter more accessible introduction to the grammar of graphics than Leland's book or Hadley's paper

### Papers and other scholarly publications

-   [A layered grammar of graphics](http://dx.doi.org/10.1198/jcgs.2009.07098) [@wickham2010]

Hi @EstherPlomp I thought that these might make some good additions what you've been working on

**Comment by kallewesterling** [comment]
This is such a nice list of links @RichardJActon!

**Comment by aleesteele** [comment]
I'd say go ahead an PR an addition, @RichardJActon! What do you think @EstherPlomp?

**Comment by EstherPlomp** [comment]
I added most of the resources now via #3453 - just not the books because I don't think there's an open access version of them available?
