### ISSUE TITLE
Link gives 404 (Issue on page /communication/citable/citable-cite.html)

### ISSUE THREAD

**Issue by zimolzak** [the-turing-way/the-turing-way#3464]
The [link](https://guide.esciencecenter.nl/#/citable_software/making_software_citable) about "adding a zenodo.json file" gives a 404 error.

Full link:
https://guide.esciencecenter.nl/#/citable_software/making_software_citable

Relevant line of markdown code here:
https://github.com/the-turing-way/the-turing-way/blob/46d74abec537a6c27f3699b46a25e60110710ecd/book/website/communication/citable/citable-cite.md?plain=1#L65

**Comment by zimolzak** [comment]
This blob from an older version of NLeSC:

https://github.com/NLeSC/guide/blob/04876418cb92c948cc09ea35e7ef52d9e493351f/citable_software/making_software_citable.md

...says basically, "Don't make a JSON by hand, but use `cffconvert` to make the JSON from `CITATION.cff` ."

**Comment by c-martinez** [comment]
I think this is content that was moved to The Turing Way (https://the-turing-way.netlify.app/communication/citable/citable-cff) -- it is not something that is specific to the eScience center, so it makes more sense at TTW than eScience Center guide.

**Comment by KirstieJane** [comment]
Ah - that's great! So we can have a recursive link that just keeps going back to the same page 😅 

@zimolzak - would you like to have a read through the page and suggest the best edit? It could be just dropping that sentence, or we may want to capture other content that you think would be useful?

**Comment by zimolzak** [comment]
Sure. I can take a look. Thanks for the quick answer!

To be honest, not yet sure when I will get to it or what form my edit will take (pull request vs comment here vs other).

**Comment by zimolzak** [comment]
note to self, this documentation might be useful to link to or reference:

https://developers.zenodo.org/?python#github (has just an example)

https://developers.zenodo.org/#deposit-metadata
...seems like the "big" documentation. Has things like `"upload_type": "presentation"`

**Comment by EstherPlomp** [comment]
I just opened up a small PR to address some other minor things with that section. Would the following adjustment work? That would refer to the [section](https://the-turing-way.netlify.app/communication/citable/citable-cff) @c-martinez highlighted, which I also think is the best reference here.

https://github.com/the-turing-way/the-turing-way/pull/3475/files#diff-9f27d24953d1101cfa84ddc48836a41ae355a1aea99d564670bfc52bb50bbdbeR71

**Comment by EstherPlomp** [comment]
I'll merge the PR and close this issue in a bit - if this wasn't the fix you had in mind, please do re-open the issue!

**Comment by zimolzak** [comment]
@EstherPlomp - Thank you for addressing this! Your commit a1092b771e141fe5f56d2a4cb0df2399c7f28acf from the PR does get rid of the dead link.

It is not quite what I had in mind, though.

1. Now the page suggests making a `CITATION.cff` instead of a `.zenodo.json`. I don't think these are the same. Isn't `.zenodo.json` something *in addition* to `CITATION.cff`, to give Zenodo some extra "hints?" Fair disclosure: I've never used `.zenodo.json` (yet). In my commit 182fcb4ebb8187876956c74f61225acab5af34cb in a separate PR, I tried to clone some instructions from the GitLab tab over to the GitHub tab. If you look at the [rendered page](https://the-turing-way.netlify.app/communication/citable/citable-cite), you'll see the two tabs are now quite different (scroll to the bottom of that page & click back & forth between the tabs).

2. Incidentally, my commit also had a very minor fix to the *GitLab* tab, in the capitalization of `CITATION.cff`. That didn't make it in yet, either.

I'm very sorry that I don't know how to re-open this issue. I don't think I can do that if someone else closed the issue, because I don't have repo write access.

My PR #3468 is still open, but I fear some of its commits got lost in the shuffle because I badly titled the PR. You'll see the difference between our 2 commits if you click [Resolve conflicts](https://github.com/the-turing-way/the-turing-way/pull/3468/conflicts) on my PR.

**Comment by EstherPlomp** [comment]
@zimolzak Apologies! I completely overlooked your PR! I re-opened the issue now.

Please do replace my suggestion with yours - it looks great! I can approve the PR afterwards if you do this by Friday. After that I'm on leave and it may be easier to ask someone else.

**Comment by zimolzak** [comment]
OK, I *think* I completed the "resolve conflicts" so the PR should be in a state ready to be merged. If you or someone could take a look, I would appreciate it.

**Comment by EstherPlomp** [comment]
Yes it looks great! Thanks you @zimolzak - Please do merge 🥳
