### ISSUE TITLE
Welcome bot emoji only render 2 out of 8 times (?!)

### ISSUE THREAD

**Issue by zimolzak** [the-turing-way/the-turing-way#3470]
Sometimes the welcome bot messages have real emoji in them, but often it's just text between colons :like_this: .

I can't figure out why it's so inconsistent!

## Ideas about why it happens

- somehow related to getting text out of the `config.yml` and into the comments field
- weird broken characters somewhere in `config.yml`
- problem on GitHub's end
- problem from welcome bot, behaviorbot, probot, etc.

## List of examples

- new issues comment
    - first Tada: success ✅ 
    - second Tada: **fail** ❌ 
    - sparkling heart: **fail** ❌ 
- new pull request comment
    - first sparkling heart: **fail** ❌ 
    - second sparkling heart: **fail** ❌ 
    - checkered flag: success ✅ 
    - recycle: **fail** ❌ 
    - tada: **fail** ❌ 

Example line within `config.yml`:

https://github.com/the-turing-way/the-turing-way/blob/e5c37c812895cc60939fe95dcf1f563520c79022/.github/config.yml#L9

For those examples of bot emoji not working quite right, please see the bot's comments on issue #3464 and PR #3468 . I have screen shots if needed.

## Things I already checked

- 2 different browsers (looks same in Firefox & Chrome)
- hexdump of `config.yml`

## Next steps?

- Find other, earlier welcome bot comments (I don't know how to do this) and see how far back the problem goes.
- Repair `config.yml` once we figure out why.
- Is it allowed to use unicode emoji directly in the yml file?
- Leave as-is?
- Stop using emoji 😿

**Comment by zimolzak** [comment]
One more data point: they also show up non-rendered in the email I got from welcome bot (notifications@github.com)

So _certainly_ not a browser issue.

**Comment by aleesteele** [comment]
Thanks so much for flagging this, @zimolzak! Flagging for @the-turing-way/infrastructure folks - we've had a few welcome bot problems for the past few months since moving to the new org 😢

**Comment by sgibson91** [comment]
There was also a similar bug in the readthedocs' preview action until about 7 hours ago: https://github.com/readthedocs/actions/issues/34

**Comment by JimMadge** [comment]
@all-contributors please add @zimolzak for bug
