### ISSUE TITLE
Add instructions regarding shallow git clones

### ISSUE THREAD

**Issue by da5nsy** [the-turing-way/the-turing-way#3486]
### Summary

This repo is large, which provides a potential barrier to participation to those with a poor internet connection, should they wish to contribute by editing the project locally. It's large enough that it is also slightly annoying for those with moderately good internet connections.
Modifying the git history for a project such as this, which might be a viable approach for other projects, is not viable (todo: add info on why not).
The next best option is to add to our instructions on how to build the book locally (around [here](https://github.com/the-turing-way/the-turing-way/blob/main/book/website/community-handbook/local-build.md?plain=1#L39)) to include some details on [shallow clones](https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/).

**Comment by richarddushime** [comment]
Hi @da5nsy,
Following your suggestion to utilize shallow clones, I successfully cloned and built the book locally by following the instructions provided in the documentation. If this approach is accepted, I can  proceed to update the necessary files by incorporating the option for shallow clones.

**Comment by da5nsy** [comment]
Fabulous! I'm glad it worked for you @richarddushime! If you make a PR to update the [local build guide](https://the-turing-way.netlify.app/community-handbook/local-build) with instructions I'll be super happy to review it :)
