### ISSUE TITLE
Welcome! Onboarding Call - 31 January 2024

### ISSUE THREAD

**Issue by aleesteele** [the-turing-way/the-turing-way#3508]
### 🚀🌟 Welcome to _The Turing Way_! We're so glad to have you here! 🌟 🚀 

_The Turing Way_ is a community-led resource for reproducible, open, collaborative, and inclusive data science. Created by over 400 contributors, The Turing Way uses open source tools to enable people to collaboratively write chapters, build and maintain resources, as well as share their skills and ideas around best practices. Core to this is the version control tool, Github which supports The Turing Way’s collaborative practices. 

### Workshop Information
**Date:** Wednesday 31 January
**Start time:** 15:00 | End time: 16:00
[Workshop Slides]()

In this workshop, co-facilitators from The Turing Way Community will introduce participants to using GitHub as a tool to support collaborative documentation-writing and knowledge sharing. 

They will discuss the importance of open community practices in building and maintaining collective resources, and learn about the importance of different roles in open source documentation communities like The Turing Way: including that of maintainers, reviewers, and translators.

Participants will gain hands-on experience in working collaboratively during the workshop by contributing to the The Turing Way project. A shared document will be used for collaborative note-taking, capturing feedback and learnings.

This training is being offered as a part of [Book Dash](https://the-turing-way.netlify.app/community-handbook/bookdash.html): a week-long event of contributions and collaborations within The Turing Way community.

#### About the Trainers

Susana Roman Garcia (@Susana465), Danny Garside (@da5nsy), Anne Lee Steele (@aleesteele)

### Housekeeping 
**Privacy statement**
This event follows the [The Alan Turing Institute's Privacy Policy](https://www.turing.ac.uk/privacy-policy).

**Code of Conduct**
* Attendees of this session will be expected to adhere to the The Turing Way's [Code of Conduct](https://github.com/alan-turing-institute/the-turing-way/blob/main/CODE_OF_CONDUCT.md)

If you have any questions, comments, and recommendations, please contact **Anne (asteele@turing.ac.uk) or Alexandra (aaraujo.alvarez@turing.ac.uk)** or comment on this issue. 

# Comment below with an answer to the following question: 

Pluses ➕ : What went well today?
Deltas 🔺 : What could have been improved?

**Comment by Susana465** [comment]
**Pluses: What went well today?**
- Good sticking to time
- Flexible schedule, allowed for introductions at the beginning
- 
**Deltas: What could have been improved?**
- Maybe add more info on working groups to the slides?
- Plan time for presentations at the beginning, with some prompts like: what do you expect to get from this call? or a fun fact about yourself. maybe the icebreaker could be included as part of the spoken intro.

**Comment by CariHV** [comment]
Thanks for being so welcoming. Looking forward to connecting with others in this amazing community

**Comment by CeilidhWelsh** [comment]
Pluses: What went well today?
Really informative and friendly!

Deltas: What could have been improved?
Maybe add into the introduction/chat/framepad one thing that each participant would like to learn, and maybe some specific examples as part of the presentation

**Comment by DDUCL23** [comment]
### Pluses
Really good way to get to know other people who are part of the Turing Way community, and developing my knowledge

### Delatas
Introduction structure, maybe? 
A Workshop on Github skills support would definitely be useful.
I think I would love to know a bit more in depth from the Working Groups, so it might be useful to get some input from representatives of these groups (maybe they could contribute to a single slide, to have a one page quick definition)

**Comment by aleesteele** [comment]
Closing this for now – thanks folks!
