### ISSUE TITLE
TTW Community Call plan (15 Feb)

### ISSUE THREAD

**Issue by AlexandraAAJ** [the-turing-way/the-turing-way#3510]

**Comment by aleesteele** [comment]
Community call flier: 
![Image](https://github.com/the-turing-way/the-turing-way/assets/18509789/59e04cc0-5ac6-4986-9fd0-652ebb0a4594)

**Comment by AlexandraAAJ** [comment]
Community Calls 2024: 
- Tuesday 23 April (15:00 - 16:30)
- Thursday 11 July (15:00 - 16:30)
- Thursday 03 Oct (15:00 - 16:30)
- Thursday 12 Dec (15:00 - 16:30)

**Comment by aleesteele** [comment]
![Image](https://github.com/the-turing-way/the-turing-way/assets/18509789/4a890ad9-985b-4237-a3fe-617fd3ba1261)

Notes review:
- @AlexandraAAJ and @aleesteele to make discussion to continue gathering feedback about decision-making process
- Need think about renaming/branding of call
- Registration form definitely needs to change

**Comment by aleesteele** [comment]
Will shift registration form to this one: https://docs.google.com/forms/d/e/1FAIpQLSeMnjQdCSXUszaBRymcwEj9bteC7GRYTOqvTEcSnoOGX_G8vw/viewform?fbzx=-3273639265032154630
