### ISSUE TITLE
Plan + promote first onboarding call

### ISSUE THREAD

**Issue by aleesteele** [the-turing-way/the-turing-way#3511]
- [x] Make registration page: https://turing-uk.zoom.us/meeting/register/tJwuf-GqpzMqHNG6DQvolLfK5qgXGfgL8aEN
- [x] Promote at Turing internal calendar - @AlexandraAAJ 
- [x] Promote in Turing slack - @aleesteele 
- [x] Promote on TTW social media - @aleesteele 
- [x] Promote in Turing newsletters - @AlexandraAAJ 

Planning onboarding call
- [x] Reach out to possible co-trainers
- [x] Make slide deck
- [x] Upload onboarding materials to github or community handbook
- [x] Make framapad: https://annuel2.framapad.org/p/ttw-onboarding
- [x] Review/practice coordination of repository --> (similar to Github workshop)
- [x] Make beginner mega issue list

**Comment by aleesteele** [comment]
Completed!

**Comment by KirstieJane** [comment]
@aleesteele - where did you document who came etc? Is there a PR open / merged?
