### ISSUE TITLE
[TALK] <Teaming-up With The Turing Way: Time Totally Well-spent>

### ISSUE THREAD

**Issue by Karvovskaya** [the-turing-way/the-turing-way#3521]
### Date of talk

2024-02-27

### Details of the talk

A lightening talk at a Dutch national event about Research Data Management and digital skills https://lcrdm.nl/evenementen/save-the-date-27-feb-2024-teaming-up-across-domains-and-call-for-contributions/
This talk by @c-martinez  @EstherPlomp  @Elisa-on-GitHub and @Karvovskaya 

### Checklist

- [x] Schedule your talk and let the community know in [TTW Slack](https://theturingway.slack.com/). If you’d like feedback and/or to schedule a practice talk, ask in the TTW Slack!
- [x] Download template(s) from the [promotion pack](https://drive.google.com/drive/folders/1mzGmbJkPnP5q1goQesxDc_E5zAPL0eTF?usp=sharing) to ensure stylistic consistency
- [x] Generate a DOI on [Zenodo](zenodo.org/) and upload your slides when ready, preferably in the original format along with a PDF or any other format you are using. Tag with "the-turing-way" under **Communities**. Zenodo allows [versioning](https://help.zenodo.org/#versioning), so we encourage you to upload your slides before your talk and add additional file(s) with any changes after
- [x] Check all ackowledgements (bottom right corner of each slide) and add the DOI for your presentation and your personal contact info if desired
- [x] If you re-used slides from a specific talk, please acknowledge the original author of the slides
- [x] Double check acknowledgements slide for TTW team, license info, Scriberia link, any additional acknowledgements
- [x] Double check contact info for TTW links (book, Twitter, GitHub, Slack, newsletter), your own contact into
- [ ] Share the Zenodo link and a recording (if available) in TTW Slack!

**Comment by aleesteele** [comment]
Hope the talk goes well, @Karvovskaya! If you could archive to the TTW way community on Zenodo, that would be great ❤️ Best of luck!

**Comment by Karvovskaya** [comment]
Thank you @aleesteele ! The slides are submitted for review!

**Comment by aleesteele** [comment]
Fantastic, approved!

**Comment by c-martinez** [comment]
Just reporting back -- @Karvovskaya gave a great talk!
