### ISSUE TITLE
[TALK] ReproHack on Computational Climate Science hosted by the Institute of Computing for Climate Science

### ISSUE THREAD

**Issue by acocac** [the-turing-way/the-turing-way#3524]
### Date of talk

2024-03-12

### Details of the talk

A ReproHack is a hands-on reproducibility hackathon where participants attempt to reproduce the results of a research paper. 

I have been invited to present a talk on The Turing Way at a ReproHack hosted by [the Institute of Computing for Climate Science (ICCS)](https://iccs.cam.ac.uk). The event aims to attract enthusiasts to collaboratively reproduce results of scholarly publications in computational climate science. See details of the event at https://www.reprohack.org/event/27/

I'll highlight the reproducible guide in TTW and practical examples from allied communities, [EDS book](https://github.com/alan-turing-institute/environmental-ds-book),  such as the [Climate Informatics Reproducibility Challenge](https://github.com/eds-book/reproducibility-challenge-2023).

The talk slot is 20 minutes, which includes time for questions. The registration for participants are open until 29th Feb.

I kindly ask to promote the event in TTW February newsletter and social media. Please find below some links shared by the ReproHack organisers. 

- [Linkedin](https://www.linkedin.com/posts/institute-of-computing-for-climate-science-iccs_how-do-we-know-if-our-code-is-reproducible-activity-7138572598791086081-OsU4?utm_source=share&utm_medium=member_desktop)
- [Mastodon](https://mast.hpc.social/@MarionBWeinzierl/111804256846621450)
- [X (formerly Twitter)](https://twitter.com/Cambridge_ICCS/status/1760350882481230076)

### Checklist

- [x] Schedule your talk and let the community know in [TTW Slack](https://theturingway.slack.com/). If you’d like feedback and/or to schedule a practice talk, ask in the TTW Slack!
- [x] Download template(s) from the [promotion pack](https://drive.google.com/drive/folders/1mzGmbJkPnP5q1goQesxDc_E5zAPL0eTF?usp=sharing) to ensure stylistic consistency
- [x] Generate a DOI on [Zenodo](zenodo.org/) and upload your slides when ready, preferably in the original format along with a PDF or any other format you are using. Tag with "the-turing-way" under **Communities**. Zenodo allows [versioning](https://help.zenodo.org/#versioning), so we encourage you to upload your slides before your talk and add additional file(s) with any changes after
- [x] Check all ackowledgements (bottom right corner of each slide) and add the DOI for your presentation and your personal contact info if desired
- [x] If you re-used slides from a specific talk, please acknowledge the original author of the slides
- [x] Double check acknowledgements slide for TTW team, license info, Scriberia link, any additional acknowledgements
- [x] Double check contact info for TTW links (book, Twitter, GitHub, Slack, newsletter), your own contact into
- [x] Share the Zenodo link and a recording (if available) in TTW Slack!

**Comment by acocac** [comment]
- [Zenodo DOI](https://doi.org/10.5281/zenodo.10808448)

Waiting @aleesteele's approval to be added in the Turing Way Zenodo community.

**Comment by aleesteele** [comment]
@acocac - would you be able to request again? I thought I had accepted, but it's not showing up on the internal platform!

**Comment by acocac** [comment]
@aleesteele I confirm I see the talk repo in the TTW Zenodo community.

**Comment by aleesteele** [comment]
@acocac Thank you! Managed to find the bug - it had been stuck in our back log 😄 

Closing this for now, congrats again on a great talk!
