### ISSUE TITLE
Evaluating Buttondown as a community platform

### ISSUE THREAD

**Issue by aleesteele** [the-turing-way/the-turing-way#3541]
### Summary

After discussing our upcoming shift to ReadtheDocs with @JimMadge, I realised that we have not posted on Github about our shift as a community from Tinyletter to Buttondown! This was an urgent shift due to Mailchimp deciding that they would shut down the Tinyletter platform at the end of February 2024.

This issue documents this shift, from initial platform evaluation/comparison to 

### Platform research and comparison

This comparison was done on [Google docs](https://docs.google.com/document/d/1i8KM1IXyWyUQ_hmz8iGezrxwva7oToilyJGyUbWGemA/edit), but has been transferred here.

Platform | Link | Can import from different platform | Freemium | Open Source | DP terms okay? | Location of Data | Notes | Decision
-- | -- | -- | -- | -- | -- | -- | -- | --
Tinyletter | link |   | x |   |   |   | Being shut down in Feb 2024, run by Mailchimp | No
Mailchimp | link |   | x |   |   |   | -- | No
Substack | link |   | x |   |   |   | [Hosts neonazis?](https://www.theguardian.com/media/2024/jan/03/substack-user-revolt-anti-censorship-stance-neo-nazis) | No
Ghost | link |   |   |   |   |   | Suggested by Jim. |  
Drupal | link |   |   |   |   |   | Suggested by Jim. |  
List Monk | link |   |   | x |   |   | Runs locally? Not as user friendly to operate. |  
GNU Mailman | link |   |   | x |   |   | Comes from the GNU team. Not as user friendly to operate. |  
Discourse | link |   |   | x |   |   | More like a forum, but integrating a few different elements. Used by a few communities: Mozilla, Open Source Design. |  
Dadamail Project | link |   |   | x |   |   |   |  
Mautic | link |   | x |   |   |   | More of an automation project? |  
MailerLite | link |   | x |   |   |   | Used by Notion team. |  
Microsoft (Dynamics 360) | link |   |   |   |   |   | Internal Turing system |  
Wordpress |   |   |   | x |   |   | Suggested by Bastian. Has security problems? |  
Buttondown | link | x | x  |  |   |   | Suggested by Malvika (she is testing it).  | 🎉 Yes 🎉 
Sender | link |   | x |   |   |   |   |                                                                                                                                         |     |

## Feature comparison and community needs mapping

| Need | How it currently works with Tinyletter | How it will work with Buttondown |  
| ----------- | ----------------------------------- | ---------------------------- |  
| Using/supporting open infrastructure across TTW project/community (tied to #2811) | Tinyletter was a proprietary platform run by Mailchimp | Buttondown is an open source, community-led platform |  
| Publicly-accessible archive for viewing previous | Tinyletter had option | Buttondown also has option  |  Not sure
| Need to transfer over subscriptions to newsletter | Had 600+ subscribers  | Need to purchase membership in order to send through BD to send to 100+ subscribers, subscribers will need to manually confirm subscription  |  
| |  |  |  

### Who can help?
- [ ] Is this something we can template?

**Comment by RichardJActon** [comment]
(FYI buttondown is not open source see: https://buttondown.email/alternatives they have a github for their general docs, open api documentation etc but not the code their core tool. Looks like a nice tool though.)

**Comment by aleesteele** [comment]
Thanks for clarifying @RichardJActon - updated!

**Comment by aleesteele** [comment]
Closing this for now – since we have made the transition. 🚀
