### ISSUE TITLE
Validate all-contributors JSON.

### ISSUE THREAD

**Issue by JimMadge** [the-turing-way/the-turing-way#3549]
### Summary

Add a CI job to validate the `all-contributors.rc` JSON file.
Mistakes in this file can cause the table to be rendered incorrectly.

### What needs to be done?

- [ ] Schema for `all-contributors.rc` ([one here](https://json.schemastore.org/all-contributors.json) discussed in [this issue](https://github.com/all-contributors/all-contributors/issues/685))
- [ ] Add CI job to validate file (perhaps using [JSON Schema](https://json-schema.org/) Python package?)

### Who can help?

* Anyone interested in CI and doing a little programming

---

**Comment by gedankenstuecke** [comment]
I wonder if an alternative solution would just be to have the CI run the all-contributors CLI tool (to try) to build the updated contributor table? That would highlight any issues with the file itself and could also be a way to ensure that the table in the readme & the source file are in sync?

(Happy to be told that this isn't a great idea due to consequences I hadn't thought about!)

**Comment by gedankenstuecke** [comment]
Gotcha, my (wrong) assumption was that the CLI tool would validate the JSON as part of the build process! 

The alternative explanation could be though that the validation for that broken JSON would still have passed? Maybe it would be worth running that broken file through the validator to check if that would indeed catch it?

**Comment by JimMadge** [comment]
Yes, actually I'm not 100% sure what the CLI does there. It might recognise that the JSON is wrong, but does it's best effort. Or, the JSON may be valid JSON, just not conforming correctly to the schema so the behaviour is undefined.

If we can use the CLI to catch and flag these problems, it would be better than introducing new code.

**Comment by aleesteele** [comment]
Just had this exact issue in #2582! Definitely demonstrates the need.

**Comment by gandrewgabriel** [comment]
Hi all - I've got a WIP script that might get us closer to sorting this. Opening a PR shortly...

**Comment by JimMadge** [comment]
Closed in #3619
