### ISSUE TITLE
[TALK] Mini workshop at Collaborations Workshop 2024 - 5th birthday celebration for the Turing Way!

### ISSUE THREAD

**Issue by KirstieJane** [the-turing-way/the-turing-way#3551]
### Date of talk

2024-04-30

### Details of the talk

The Turing Way community launched the very first few chapters of the guide for reproducibility at the Collaborations Workshop in 2019!! We're FIVE YEARS OLD! 😱 🎂 💝 

I'm excited to head back to the conference in 2024 and _hopefully_ to run a session to mark the 5 years since our launch.

I'm making this issue now while I have a fancy flat white coffee and brainstorm a few options for the application (due on 1 March).

👉  If you have any suggestions on the best topics to cover for a 60 minute workshop please comment in the issue here!

📝 Application google doc drafting: https://docs.google.com/document/d/1jZjvEiAQcrXaNyy3TtbvkV8ViqHQ8hORkZBOrkdc_7g/edit?usp=sharing

### Checklist

- [ ] Schedule your talk and let the community know in [TTW Slack](https://theturingway.slack.com/). If you’d like feedback and/or to schedule a practice talk, ask in the TTW Slack!
- [ ] Download template(s) from the [promotion pack](https://drive.google.com/drive/folders/1mzGmbJkPnP5q1goQesxDc_E5zAPL0eTF?usp=sharing) to ensure stylistic consistency
- [ ] Generate a DOI on [Zenodo](zenodo.org/) and upload your slides when ready, preferably in the original format along with a PDF or any other format you are using. Tag with "the-turing-way" under **Communities**. Zenodo allows [versioning](https://help.zenodo.org/#versioning), so we encourage you to upload your slides before your talk and add additional file(s) with any changes after
- [ ] Check all ackowledgements (bottom right corner of each slide) and add the DOI for your presentation and your personal contact info if desired
- [ ] If you re-used slides from a specific talk, please acknowledge the original author of the slides
- [ ] Double check acknowledgements slide for TTW team, license info, Scriberia link, any additional acknowledgements
- [ ] Double check contact info for TTW links (book, Twitter, GitHub, Slack, newsletter), your own contact into
- [ ] Share the Zenodo link and a recording (if available) in TTW Slack!

**Comment by acocac** [comment]
> 
> * 🌍 https://the-turing-way.netlify.app/ethical-research/activism/activism-env-impact.html

@annefou and I have discussed how to participate in CW24. The mini-workshop for CW24 sounds amazing to celebrate 5 years 🍰 🥳 . For the Environment & Sustainability track, I suggest we work on a sort of timeline highlighting how TTW has inspired and joined forces with other communities including EDS book to advance on vital aspects (computational reproducibility, environmental impact, etc) where community-focused approaches make the difference.

**Comment by KirstieJane** [comment]
Ok - I have to do a few other tasks I have to jump to today but keen to hear any thoughts on this session plan:

10. Mini-workshop or demo session description *
Please describe your session's aims and outcomes, how the session connects to the themes of CW24, how the session will run (tentative format/agenda), and how the session will be inclusive of both in-person and remote participants. If you are proposing a 60-minute session, please outline how you plan to facilitate active participant engagement/interaction with both in-person and remote participants.

> Aims:
> - Celebrate 5 years of community-led collaboration building resources and sharing knowledge. 
> - Summarise three exemplar chapters in The Turing Way to highlight how the book disseminates expertise in environmental considerations, best practices for the use of AI/ML for scientific research, and citizen science.
> - Collect reflections from workshop participants on what has changed in the last 5 years.
> - Collect predictions from workshop participants on what will change in the next 5 years.
> 
> Outcomes:
> - Attendees know that their expertise is welcome in The Turing Way community and know who to contact if they would like to contribute.
> - Attendees can see how The Turing Way project covers many themes across responsible research and innovation, including open science, inclusive practices, ethical considerations and computational sustainability.
> - Attendees feel reassured that there is progress being made in open and responsible research and innovation, even if there are still many challenges to overcome.
> 
> Session agenda:
> - 00-10: Welcome and (very brief) introduction to The Turing Way
> - 10-40: 3 x lightning talks on software testing, environmental impact of open research, and how to include members of the public and experts by lived experience in research projects.
>   - 5 minutes each with 5 minutes for questions and handover
> - Questions either by raising hand in the room or online, or using sli.do for both sets of attendees.
> 40-50: Breakout groups to discuss what has changed in the last 5 years and what we predict will change in the next 5 years
>   - Note collected using Miro for online participants, post-its for in person participants
> - 50-55: Open discussion reflecting on predictions for the future from the breakout groups
> - 55-60: Singing happy birthday and cake distribution for in person attendees
>

**Comment by acocac** [comment]
> Do you think you'd like to put in a 30 minute demo to focus on the EDS book @acocac and @annefou ? Or does teaming up sound like the best plan? 60 minutes is going to fly by so your work is going to end up with only a few minutes of air time... but maybe that's ok.
> 
> I think it depends on how busy you both are and your capacity to attend the conference and lead a workshop (if selected!)

We aren't in the capacity to run a separate workshop, unfortunately 😞 I think we could contribute with a lightning talk. Two options: 1) a testimony of EDS book and how we have extended TTW for environmental scientists or 2) environmental impact with inputs from folks of the #environmental-sustainability channel.

**Comment by KirstieJane** [comment]
For completeness here's the abstract 🎂 

> In 2019, at the Collaborations Workshop in Loughborough, The Turing Way (https://the-turing-way.netlify.app/index.html) was launched as a guide to reproducibility, providing tools, methods, and practices to address the reproducibility crisis in science. When we received a second wave of funding from The Alan Turing Institute we reflected further on what skills are required to maximise efficiency, reusability and openness in data intensive science. The Turing Way added guides for project design, ethics, communication and collaboration in 2020. What began as an open-source project building a handbook for data science, has blossomed into a dynamic, global collaborative community. 
>
> With 450+ co-authors who have shaped its narrative so far, The Turing Way has unfolded into a multi-guide book featuring 300+ chapters. In this session we will highlight three chapters in line with the themes of Collaborations Workshop 2024: 
> * Code Testing (https://the-turing-way.netlify.app/reproducible-research/testing): We will revisit one of the first chapters we published with a particular focus on making sure that there is a human-in-the-loop when using AI tools for software engineering. Imagine a world where the same large language model writes the code and the tests, marking its own homework with no critical oversight!
> * The Environmental Impact of Digital Research (https://the-turing-way.netlify.app/ethical-research/activism/activism-env-impact.html): We will highlight how The Turing Way has inspired and joined forces with other communities including Pangeo (https://pangeo.io/) and the Environmental Data Science Book (https://edsbook.org/welcome.html) to contextualise open research practices for environmental data scientists, as well as considering and minimising the environmental impacts of data science.
> * Running inclusive events for research incorporating patient and public involvement and engagement (https://github.com/the-turing-way/the-turing-way/pull/3550). We will aim for a 5th birthday live merge of a recent chapter written in collaboration with the AI for Multiple Long Term Conditions Research Support Facility (https://www.turing.ac.uk/research/research-projects/ai-multiple-long-term-conditions-research-support-facility) and The Turing Way Accessibility working group as we continue to break down the barrier between “citizen” and “scientist”.
>
> After these lightning talks we will have small discussion groups focused on what we have achieved in the last 5 years and what we predict will change in the next 5 years. At the end of the session we will sing happy birthday to our community and provide cake for anyone who is attending in person.

**Comment by KirstieJane** [comment]
Thank you so much to @Arielle-Bennett for reading through at the last minute 🙏 

Fingers crossed the review panel are excited to have us celebrate with them!

**Comment by malvikasharan** [comment]
Updating here that this submission has been accepted. 🎉

**Comment by KirstieJane** [comment]
Hi folks! 

Building on the proposed agenda from the application, I've put together a few more details:

- 00-10: Welcome and (very brief) introduction to The Turing Way
- 10-40: 3 x lightning talks on software testing, environmental impact of open research, and how to include members of the public and experts by lived experience in research projects.
  - 5 minutes each with 5 minutes for questions and handover
  - Questions either by raising hand in the room or online, or using sli.do for both sets of attendees.
  - Software testing talk by @martintoreilly or @KirstieJane 
  - Environmental impact talk by @acocac and @c-martinez 
  - PPIE talk by @BrainonSilicon and/or @LizHareDogs 
- 40-50: Breakout groups to discuss what has changed in the last 5 years and what we predict will change in the next 5 years
    - Note collected using Miro for online participants, post-its for in person participants
    - @KirstieJane, @AlexandraAAJ, @Arielle-Bennett and @aleesteele to facilitate in person
    - @gedankenstuecke, @GeorgiaHCA, @acocac, @BrainonSilicon or any other community members who will be remote attendees?
- 50-55: Open discussion reflecting on predictions for the future from the breakout groups
  - @KirstieJane to facilitate
- 55-60: Singing happy birthday and cake distribution for in person attendees
  - @KirstieJane and @AlexandraAAJ to host 🎂 

So questions:

- [ ] @martintoreilly - would you like to give a 5 min presentation on software testing (based on the chapter)? I can present if you'd rather not!
    - [ ] I think you have a ticket, right? 
- [ ] @acocac and @c-martinez - are you able to give a 5 min joint presentation about your work considering environmental data science and/or the environmental impact of data science in The Turing Way?
    - [ ] Presenters have to have a ticket - Carlos - are you going to join the Collaborations Workshop? We can pay for a remote ticket if you need one? Or happy for just @acocac to present if you're busy 😌 
- [ ] @BrainonSilicon and @LizHareDogs - would you like to give a 5 min joint presentation about the inclusive events chapter?
    - [ ] Presenters have to have a ticket - Sophia and Liz - we can pay for a remote ticket for you both (or for either of you if you don't have time!) if you're able to present?
- [ ] @gedankenstuecke, @GeorgiaHCA, @acocac - are you ok being online facilitators please? For breakout rooms and just in case there are technical challenges!
- [ ] @AlexandraAAJ - are you ok to be in charge of cake and balloons? I'm happy to help! (I'll have my car with me if that's helpful!)

What other questions do you have?

**Comment by gedankenstuecke** [comment]
Yes, happy to facilitate online for it! 🚀

**Comment by BrainonSilicon** [comment]
I'm very keen and happy to present. It would be awesome to get a merge during the session! 🚀

**Comment by LizHareDogs** [comment]
Great! I'm happy to do anything I can to support Sophia. She has put all this material together and is most familiar with the community it responds to. I also can't be there in person, and I'm not sure whether I can attend at all. Kudos to Sophia!On Apr 8, 2024, at 5:52 AM, Sophia Batchelor ***@***.***> wrote:﻿
I'm very keen and happy to present. It would be awesome to get a merge during the session! 🚀

**Comment by GeorgiaHCA** [comment]
This looks great! Happy to facilitate/take notes too!

**Comment by LizHareDogs** [comment]
Miro is not screen reader accessiblw. Consider having someone to narrate what's going on with it and how people can contribute if they can't access it.

**Comment by c-martinez** [comment]
Unfortunately I won't be able to join CW24, but I'm happy for @acocac to present if he is available (and I could help prepare slides in advance).

**Comment by AlexandraAAJ** [comment]
Excellent, thanks Kirstie. Happy to support during the workshop and to take care of decoration and cake, :)

**Comment by acocac** [comment]
Yes, I'm available and happy to contribute. I'll work on the slides with @c-martinez and validate with contributors/members in TTW #environmental-sustainability slack channel and EDS book.

**Comment by AlexandraAAJ** [comment]
@KirstieJane and @malvikasharan, we have an opportunity to collaborate with Code for thought to complement this workshop with a 5-year celebration for the Turing Way podcast episode. Peter Schmidt, Code for Thought founder and producer will be attending and producing content for the Collaborations Workshop so he could easily interview Kirstie, and some of the workshop attendees there. There is a cost involved that could be covered by project budget. Let me know what you think.

**Comment by acocac** [comment]
@KirstieJane @malvikasharan @AlexandraAAJ  I've worked on a [first draft of the slides](https://docs.google.com/presentation/d/1mzuz--sPMGX7-tDvB_hTqKksjfnP9BqHiFjN8Q_ziJI/edit?usp=sharing) to share and celebrate environmental data science and the environmental impact of data science in The Turing Way. Your feedback or comments in the slides would be welcome!

@c-martinez can you please confirm if we have more activities in the environmental impact track? Happy to add extra slides of how to join, activities from other members of the #environmental-sustainability slack channel e.g.  recent participation in the ELIXIR Environmental Impact Focus Group or future ideas.

ps. Please accept my apologies. I was aiming to validate the slides in today's co-working session, but I'm attending the Climate Informatics event.
