### ISSUE TITLE
[TO EDIT] <chapter/subchapter>

### ISSUE THREAD

**Issue by bglen9309** [the-turing-way/the-turing-way#3562]
### Summary

Chapter/subchapter 

### What needs to be done?

Repository report 

### Who can help?

Repo

### Updates

- [X] First set of edits to chapter/subchapter
- [X] Proofread
- [X] Request reviews
- [X] Address reviews
- [X] Merge to main branch

**Comment by aleesteele** [comment]
Thanks @bglen9309 - I'll close this one for now, in the case that you're interested in suggesting a chapter in the future. Welcome to the community!
