### ISSUE TITLE
[NEW CHAPTER] - Risks of Bias in Research

### ISSUE THREAD

**Issue by scjjb** [the-turing-way/the-turing-way#3565]
### Title

Risks of Bias in Research

### Guide

Guide for Project Design (Also relevant to Guide for Ethical Research but more focused on project design)

### Draft

https://hackmd.io/@scjjb/SyHEOrIQa

### Summary of proposed chapter

'Risks of Bias' in research are opportunities for reported results to become distorted by limitations within the study design, conduct, and analysis. Many risks can be mitigated, though this requires researchers to be aware both of the risks and the mitigation techniques. In our chapter of The Turing Way handbook, we will provide guidance on performing more reliable and reproducible research.

This chapter aims to educate data scientists / researchers about risks of bias, to assist in the design of higher-impact, lower-risk research - we all want our research to be accurate and non-discriminatory, but without knowing about the potential pitfalls and solutions, it's all too easy to get it wrong. The chapter also aims to help in conveying risks when communicating the results of research. 

The chapter currently contains the following sections:
1 - **Identifying Risks of Bias** (Sampling, Exposures and Outcomes, Analysis and Reporting, Blinding)
2 - **Confounding** (Causality, Directed Acyclic Graphs)
3 - **Validation and Generalisability** (Cross-validation, Bootstrapping, Metric Selection)
4 - **Discrimination and Bias** 

My expertise are primarily within sections 1 and 3, so help would be particularly appreciated on sections 2 and 4 (and on any extra proposed sections)! 

### Resources

General guidance:
- [Assessing bias](https://www.nhmrc.gov.au/guidelinesforguidelines/develop/assessing-risk-bias#)
- [Data hazards](https://datahazards.com/index.html) and its [associated TTW chapter](https://the-turing-way.netlify.app/ethical-research/data-hazards)
- [Bias and Confounding](https://www.healthknowledge.org.uk/public-health-textbook/research-methods/1a-epidemiology/biases)

Risk of bias assessment tools (typically used for systematic literature review):
- [Collection of tools](https://osf.io/dmrq6)
- [PROBAST](https://pubmed.ncbi.nlm.nih.gov/30596875/)
- [RoB 2](https://methods.cochrane.org/bias/resources/rob-2-revised-cochrane-risk-bias-tool-randomized-trials)

### Who can help?

Anyone working in data science or associated research fields, especially those with experience in statistics, causal inference, systematic reviews, model fairness/discrimination, etc. 

Also anyone with experience in creating visualisations for The Turing Way. 

### Updates

- [X] Write chapter outline
- [x] Add material to the chapter
- [x] Combine materials into a readable chapter
- [x] Proofread
- [ ] Create PR and link in the comments
- [ ] Request reviews
- [ ] Address reviews
- [ ] Merge to main branch

**Comment by aleesteele** [comment]
Welcome @scjjb! This sounds like a great topic to add to our Guide for Project Design - if you need any help reviewing materials or want someone to join along on your work, please let me know if there's any way I can help!
