### ISSUE TITLE
[TALK] The Critical Role of Open Source in Open Research

### ISSUE THREAD

**Issue by penyuan** [the-turing-way/the-turing-way#3570]
### Date of talk

2024-03-20

### Details of the talk

Thanks to support from Malvika, I'm lucky to be giving a talk at the "[Open Source for Innovation in Universities"](https://www.eventbrite.ie/e/open-source-for-innovation-in-universities-tickets-830091424797?aff=oddtdtcreator) event in Galway, Ireland on the morning of 20 March 2024. The audience is a mix of academics and industry professionals from a tech background with a shared interest in open source. This time, I have a whopping 30 minutes and will use a chunk of it to introduce the Turing Way community.

After some co-work with Malvika, the general idea/structure of the talk is: 

* The nature of open research, and how it can embody the freedoms to use, study, modify, and share that underpin open source software.
* Software could form key infrastructure for research, but this infrastructure is often invisible (at least until something breaks). Give example:
  * GitHub is an "invisible" software infrastructure in the sense that everyone uses it, but when it goes down, we all go down. GitHub down time might be an accident, but it shows how much power it holds over us as software users and developers.
* If this software is closed source, then whomever holds power over that infrastructure holds that power over everything and everyone who relies on it.
* This is what's really important about open source technology, not only because it might speed innovation or aid collaboration, but because it breaks that hold on power and gives everyone agency over their work (and lives!).
* In response/contrast to that, I'd like to use open source hardware as an example of a more equitable distribution of that power.
  * For, we might take microscopes for granted in some fields of scientific research, but when you can't afford it, repair it, or adapt it, it constrains the research questions you can ask.
* Give examples of successful open source projects (including some hardware) that form critical infrastructure for research, such as the Openflexure open source microscope, and possibly open source ventilators.
* What these examples show is that by retaining the freedoms behind open source, we have the *knowledge* to exercise agency.
* This epistemic power is key to open research, and a key reason why open source is critical to open research.
* Without open source technologies, we can only do the research that our tools *allow* us to do.
* Conversations like this are what's really valuable in a community like the Turing Way, where its inclusive environment is one where we all share the power in contributing to discussion and the Turing Way book.
* [basic introduction to the Turing Way]
* And a community similar to the Turing Way, but focused on open source hardware in research, is the [Gathering for Open Science Hardware](https://openhardware.science/).

Similar to [my 2024 FOSDEM Open Research Devroom lightning talk](https://write.as/naclscrg/epistemic-and-disciplinary-diversity), I'd gratefully welcome input from everyone on: 

0. Any other great examples of open source software and hardware being a critical enabler of open research?
1. The Turing Way community holds power together in a remarkably inclusive and equitable way where people feel comfortable taking the lead on things, such as the localisation/translation work. Do YOU have specific examples/experiences in this community that also demonstrates this equitable epistemic power, which underlies open source work?
2. Any general comments/suggestions for the rough structure described above.

Like before, I likely can't squeeze all input into the talk, but will strive to document them and acknowledge you. Thanks!

### Checklist

- [X] Schedule your talk and let the community know in [TTW Slack](https://theturingway.slack.com/). If you’d like feedback and/or to schedule a practice talk, ask in the TTW Slack!
- [x] Download template(s) from the [promotion pack](https://drive.google.com/drive/folders/1mzGmbJkPnP5q1goQesxDc_E5zAPL0eTF?usp=sharing) to ensure stylistic consistency
- [x] Generate a DOI on [Zenodo](zenodo.org/) and upload your slides when ready, preferably in the original format along with a PDF or any other format you are using. Tag with "the-turing-way" under **Communities**. Zenodo allows [versioning](https://help.zenodo.org/#versioning), so we encourage you to upload your slides before your talk and add additional file(s) with any changes after
- [x] Check all ackowledgements (bottom right corner of each slide) and add the DOI for your presentation and your personal contact info if desired
- [x] If you re-used slides from a specific talk, please acknowledge the original author of the slides
- [x] Double check acknowledgements slide for TTW team, license info, Scriberia link, any additional acknowledgements
- [x] Double check contact info for TTW links (book, Twitter, GitHub, Slack, newsletter), your own contact into
- [ ] Share the Zenodo link and a recording (if available) in TTW Slack!

**Comment by jcolomb** [comment]
hardware example is gorgas, you probably know Julieta's paper on it. The white rabbit may also be a good example, as one can buy it from different companies.

Software example are R and python, that was a revolution over SPSS use.

Also another big enabler in academia is that the open source tools can be self hosted at the university, different universities often using the same tools, like gitlab.

**Comment by penyuan** [comment]
Ah yes, thanks @jcolomb for reminding me of the [Gorgas tracker](https://github.com/healthinnovation/gorgas_tracker) (as mentioned [here](https://drexel.edu/coas/news-events/news/2021/July/open-science-hardware-accelerates-innovation-democratizes-science/)). Yes, Julieta's paper on this is super inspiring!

I didn't know about white rabbit, are you talking about [this White Rabbit](https://ohwr.org/project/white-rabbit/wikis/home) from CERN?

Good point about self-hosting, and R and Python vs SPSS and other closed source systems (like MATLAB et al.). I think the *contrast* and how empowering R and Python are is what's interesting.

@everyone: Keep the suggestions coming! :heart:

**Comment by jcolomb** [comment]
Yes, that white rabbit, you can look at https://www.openmake.de/blog/2022/10/20/2022-10-06-interview-white-rabbit/ for an interview

**Comment by malvikasharan** [comment]
I have been enjoying my 1:1 with Pen, it's always so generative to unpack these topics. I love the flow of the talk so far.

- Contextualising open research for open source
- Unpacking the dependency of open source on open research and community
- Unpacking the dependency of open research on open source
- Asking the audience via a collaborative open source tool what software/infra they consider critical
- Providing some examples as a case study for software and Hardware
- Taking about the importance of building agency through fostering community (the real power of Open Research projects)
- Talking about the power dynamics and how that affects participation
- Asking question - provocation for if we truly reflect on how develops knowledge and shares benefit
- Transition to The Turing Way:
  - A project where people can learn about practices for open and collaborative research and data science
  - A community that aims to model behaviours that we want to promote for open working

**Comment by penyuan** [comment]
Indeed @malvikasharan for the thought-provoking discussions! Here are some of my notes, specifically about possible interactions with the audience, which I will run by the organisers.

I mentioned that @sgibson91 reminded me that JupyterHub is a great example of key open source software infrastructure. This prompted @malvikasharan to give the great idea of interaction with the audience, asking them to add to a collaborative space in real time to give their examples. This lets the audience see that they also have knowledge and expertise.

Then, I could ask: "Imagine if this disappears, what does this mean for your research?" Which would highlight how the tech underlying our research is often invisible.

And if I use Etherpad, or another open source collaborative pad, for this exercise, then I can make the meta comment that I'm using a piece of open source infrastructure for collaboration, and the invisibility of those platforms. In other words, when I'm using software (or hardware), I'm not really thinking about the software itself, but the work I'm working on. For example, we often use closed source tools like Google Docs or Microsoft Office 365 for collaboration, but are not conscious of how reliant - and **beholden** -  we've become to these closed source infrastructures. 

Then move on to talk more about open source infrastructure and how that allows us to take back autonomy, agency, and power over our research and our lives.

At the end of the talk, I could invite the audience's knowledge into the Turing Way community.

**Comment by malvikasharan** [comment]
Here is the Zenodo: https://zenodo.org/doi/10.5281/zenodo.10828119

**Comment by penyuan** [comment]
Hello @aleesteele and @malvikasharan, 

Yes, there is a recording made by the organisers which AFAIK is not online yet. Thanks @malvikasharan for posting the Zenodo link.

I'll share the recording as soon as I get it, plus a transcript and other notes ASAP.

Maybe this can still make it into the *next* newsletter??

**Comment by penyuan** [comment]
All right.... @aleesteele @malvikasharan I finally made a post with notes and the full transcript [here](https://write.as/naclscrg/critical-role-of-open-source-in-open-research). Hope it's useful to someone!
