### ISSUE TITLE
Create Netlify redirect rules

### ISSUE THREAD

**Issue by JimMadge** [the-turing-way/the-turing-way#3577]
### Summary

Part of #3266 

Create redirect rules so that old URLs `the-turing-way.netlify.app/*` point to the new URL `book.the-turing-way.org/*`.

### What needs to be done?

- [x] Add redirect rules (301) to Netlify configuration
- [x] Push changes
- [x] Ensure that `the-turing-way.netlify.app/*` correctly redirects
- [ ] Ensure these rules continue to work (A new repo to push just redirect rules to Netlify?)

### Who can help?

* Infrastructure WG

---

**Comment by da5nsy** [comment]
Is this complete @JimMadge ?

**Comment by JimMadge** [comment]
Sort of, [rules were added](https://github.com/the-turing-way/the-turing-way/blob/main/netlify.toml). The last checkbox isn't complete yet as we are still using Netlify for hosting.

We could close this issue though and open a new issue when we need that.
