### ISSUE TITLE
Welcome! Onboarding Call - 27 March 2024

### ISSUE THREAD

**Issue by Susana465** [the-turing-way/the-turing-way#3586]
### 🚀🌟 Welcome to _The Turing Way_! We're so glad to have you here! 🌟 🚀 

_The Turing Way_ is a community-led resource for reproducible, open, collaborative, and inclusive data science. Created by over 400 contributors, The Turing Way uses open source tools to enable people to collaboratively write chapters, build and maintain resources, as well as share their skills and ideas around best practices. Core to this is the version control tool, Github which supports The Turing Way’s collaborative practices. 

### Workshop Information
**Date:** Wednesday 27 March
**Start time:** 15:00 | End time: 16:00
[Workshop Slides]()

In this workshop, co-facilitators from The Turing Way Community will introduce participants to using GitHub as a tool to support collaborative documentation-writing and knowledge sharing. 

They will discuss the importance of open community practices in building and maintaining collective resources, and learn about the importance of different roles in open source documentation communities like The Turing Way: including that of maintainers, reviewers, and translators.

Participants will gain hands-on experience in working collaboratively during the workshop by contributing to the The Turing Way project. A shared document will be used for collaborative note-taking, capturing feedback and learnings.

This training is being offered as a part of [Book Dash](https://the-turing-way.netlify.app/community-handbook/bookdash.html): a week-long event of contributions and collaborations within The Turing Way community.

#### About the Trainers

Susana Roman Garcia (@Susana465), Ceilidh Welsh (@CeilidhWelsh ), Anne Lee Steele (@aleesteele)

### Housekeeping 
**Privacy statement**
This event follows the [The Alan Turing Institute's Privacy Policy](https://www.turing.ac.uk/privacy-policy).

**Code of Conduct**
* Attendees of this session will be expected to adhere to the The Turing Way's [Code of Conduct](https://github.com/alan-turing-institute/the-turing-way/blob/main/CODE_OF_CONDUCT.md)

If you have any questions, comments, and recommendations, please contact **Anne (asteele@turing.ac.uk) or Alexandra (aaraujo.alvarez@turing.ac.uk)** or comment on this issue. 

# Comment below with an answer to the following question: 

Pluses ➕ : What went well today?
Deltas 🔺 : What could have been improved?

**Comment by CeilidhWelsh** [comment]
Pluses➕: What went well today?

- Good sticking to time
- Small group with free flowing discussion for answering questions 
- a **live** PR close! 💪🥳

Deltas 🔼 : What could have been improved?

- Maybe add more info on Interest Groups to the introductory presentation

**Comment by paulmaxus** [comment]
What went well? I liked the open discussion and I'm motivated to contribute :)
What could have been improved? More time ;)

**Comment by rgbayrak** [comment]
I did not come with any expectations but to learn more about TTW. 

➕1 to what went well today:

➕1  Good sticking to time
➕1  Small group with free flowing discussion for answering questions
➕ Very welcoming community

What could have been improved?
N/A

**Comment by aleesteele** [comment]
Pluses➕: What went well today?
- An hour really zooms by!
- The live PR close was really the highlight!
- The size of the group went well!

Deltas 🔼 : What could have been improved?
- Starting talking about the informal interest groups without a lot of information about how to get engaged 
-

**Comment by Susana465** [comment]
## Debrief post-session notes

- To consider for the future (came up last onboarding call too) ->Github workshop & knowing how to contribute: directing people to the github workshop or collaboration cafe (this is a feedback point, no action needed).
- good to go along with the flow - people asked about merging and closing and opening PRs in github and someone closed a PR live (this is a feedback point, no action needed).
- Need to add notes to the slides themselves or to the framapad with information about what to say, and/or with all the links to be able to share them in the call. (Anne to action)
- Missing slides interest groups environment (to add to presentation), practitioners hubs info in slides (Anne to action)
- Pluses and deltas are as above in this issue.
- Agreed to add debrief notes to github and close it (Susana actioning now).

- For next session suggestion: Bring open PR, or issue to the session, offer in the session if someone wants to close it, or just showcase it. 

- Admin issues in github to allow people to add people to the github repo, anne to be there at the beginning of call to add users (Ceilidh to action, ask on slack)

Closing this issue now as onboarding call has passed, and future actions will be carried on to next onboarding call.
