### ISSUE TITLE
[NEW CHAPTER] - Missing Data Handling

### ISSUE THREAD

**Issue by Zeena-Shawa** [the-turing-way/the-turing-way#3593]
### Title

Missing Data Handling

### Guide

Project Design

### Summary of proposed chapter

To introduce missing data handling. This will include introducing the concept of missing data (which is a common occurrence), outlining different missing data structures and how to handle them. The aim of this chapter is to be a starting guide for data scientists looking for a brief introduction on the topic. It will also act as a platform linking to further resources where appropriate. A section of the chapter will introduce the more recent concept of ‘structured missingness’ and the work done within the [Turing-Roche partnership](https://www.turing.ac.uk/research/research-projects/alan-turing-institute-roche-strategic-partnership) to tackle this.

### Who can help?

- Turing-Roche Community Scholars
- Happy to collaborate with anyone! 

### Updates

- [ ] Write chapter outline
- [ ] Add material to the chapter
- [ ] Combine materials into a readable chapter
- [ ] Proofread
- [ ] Create PR and link in the comments
- [ ] Request reviews
- [ ] Address reviews
- [ ] Merge to main branch

**Comment by aleesteele** [comment]
Welcome @Zeena-Shawa - this sounds like a great contribution to *The Turing Way*! I'm sure @vhellon is helping you along with drafting, but if you need any support, don't hesitate to tag me, and/or message on Slack.
