### ISSUE TITLE
Next Milestone

### ISSUE THREAD

**Issue by alexmorley** [the-turing-way/the-turing-way#36]
This will probably require a fair bit of discussion etc. to reach a consensus so we should probably start early/soon!

**Comment by malvikasharan** [comment]
We can use this issue to highlight the next milestones and hopefully link to the relevant issues. What do you think @KirstieJane?

**Comment by aleesteele** [comment]
Hi folks – we can close this for now, as we have other means of tracking project milestones now 😄
