### ISSUE TITLE
[EVENT] London Open Source Day during London Data Week

### ISSUE THREAD

**Issue by dingaaling** [the-turing-way/the-turing-way#3607]
### Summary

We would love to highlight the London Open Source community during London Data Week. The current idea is to:
- Feature different open organisations through open house or public event on the day (tentatively July 4th)
- Convene the London Open Source community at an evening gathering
- (reach goal) Set up an Open Source Bus line that connects different open houses throughout the day (e.g. Chatham House -> British Library -> Open Data Institute -> UCL -> Newspeak House)

### What needs to be done?

Would someone from the London Hub of the The Turing Way community be interested in:
- Leading London Open Source Day alongside Jacob from OSPO++ and Jen
- Crafting a public event that highlights TTW alongside other open source organisations
- Attending or speaking at an evening gathering at Newspeak House on that day?

Please join an upcoming planning meeting on 18 April, 3PM BST if you'd like to collaborate on this!

### Who can help?

* Anyone from the London Hub from TTW interested in getting involved 

---

### Updates

* Upcoming planning meeting on 18 April, 3PM BST
* Planning google doc: https://docs.google.com/document/d/1MXnTPTlZe-IKl-2RRbt7NAlVw09L2Wjt-U_vd-UOLwE/edit?usp=sharing

**Comment by AlexandraAAJ** [comment]
Hi @dingaaling, happy to support on this! Sounds super interesting and cool, I'm not sure if I understand correctly the doble decker bus and my imagination just went wild :).
I will not be able to join the planning meeting on the 18 April (as I have another previous commitment) but l guess all the notes will be hosted on the Google docs? Maybe we could catch up on Friday 19 to review the next steps and how could I support?

**Comment by dingaaling** [comment]
@AlexandraAAJ woohoo! It would be awesome to work with you on this. Your connections to both TTW and BridgeAI will be so valuable. I'll DM you on Slack to coordinate how to start a conversation about this :)

**Comment by dingaaling** [comment]
Unfortunately this event is no longer happening this year, but we look forward to a future London Open Source Day!
