### ISSUE TITLE
I can't access `book.the-turing-way.org`

### ISSUE THREAD

**Issue by da5nsy** [the-turing-way/the-turing-way#3642]
This issue is for collecting information about any problems folks have with accessing The Turing Way at `book.the-turing-way.org`.

We recently bought a new domain (https://github.com/the-turing-way/the-turing-way/issues/3266) and there have been a couple of anecdotal reports of people struggling to access the site via the new URL.

**Has it not worked for you? Please tell us in a comment below!**

Things that would be useful for us to know:
- What network were you connected to?
- What precise URL were you trying to access?
- Did you receive an error code?

**Comment by da5nsy** [comment]
> https://book.the-turing-way.org/ isn't working for me on 17/05/2024 from the Turing office in London my Turing laptop.

Ooh interesting! Thanks for noting! 
Which network were you connected to? Did you receive an error code? (Was it blocked or just not loading?)

**Comment by kallewesterling** [comment]
When I'm using the Turing office's VPN, the page is just stuck on loading:

![image](https://github.com/the-turing-way/the-turing-way/assets/7298727/a6130442-4f91-4921-bdca-2cd40e4f8c24)

When turning it off ("Disconnect"):

The page loads as it should:

![image](https://github.com/the-turing-way/the-turing-way/assets/7298727/6728952f-b112-4820-8b5f-67a6c1e4fc76)

**Comment by JimMadge** [comment]
Closing as this has gone stale. Can reopen or make a new issue if there are more problems.

**Comment by KirstieJane** [comment]
@JimMadge - when you say its gone stale do you mean that the problem still exists but no one is working on it? Or does the problem not exist any more (as in folks at the Turing Institute can now access the book?)

**Comment by JimMadge** [comment]
The problem with access from the Turing offices was fixed (as far as I know).

I think it would be better for there to be new issues if there are problems in the future rather than leave this open in case there are problems.

**Comment by KirstieJane** [comment]
Yes - perfect - that's great!

It just wasn't totally clear from your closing post. Completely agree that a new problem should be a new post 😅
