### ISSUE TITLE
Capturing June 2024 Book Dash Participant's information in the contributors file 

### ISSUE THREAD

**Issue by aleesteele** [the-turing-way/the-turing-way#3655]
_**Please don't forget to add your information by 28 June! This will help the organisers to track your contributions throughout the Book Dash period.**_

## Summary

All Book Dash participants (3-7 June 2024) will capture their contributions in this issue.
Info will be copied over to the [Contributors file](https://github.com/the-turing-way/the-turing-way/blob/main/contributors.md). (Participants can directly edit this file and comment below with a PR if they prefer.)

The info will appear after merging in the GitHub repo on [Record of Contributions](https://the-turing-way.netlify.app/afterword/contributors-record.html).

### What needs to be done?

Please make sure that you share your feedback and experience from the last 5 days with us in this document: 

- [ ] Comment below your details in the following format (Paul's bio/details below for example)
- [ ] In your highlight you can also provide links to your issues and PRs

**Template**
---
* Role: Book Dash participant (2024)
* GitHub id: 
* ORCID: 
* Short bio:
> write here ...
* Personal highlights:
> write here ...
* More information:
> write here ...
* Quotes:
> write here ...

**Example**
---
### Paul Owoicho

* Role: 
  * Google Season of Doc: Technical Writer (2021)
  * Book Dash Participant (2021)
* GitHub id: [paulowoicho](http://github.com/paulowoicho)
* ORCID: TBA
* Short bio:
> I am a Technical Writer / Google Season of Docs (GSoD) Participant working to make The Turing Way consistent, sustainable, and accessible.
> I have a BSc in Software Engineering from the American University of Nigeria. Thereafter, I worked as a Research Analyst in the Fintech & Innovation Division of Guaranty Trust Bank, Nigeria and helped to drive the Bank's push to become a platform by creating innovative digital products.
> I completed a Master's in Data Science from the University of Glasgow and starting my PhD in January 2021 studying conversational information-seeking systems. I spent two years as a Research Analyst at Guaranty Trust Bank in Lagos, Nigeria helping to build innovative digital products to meet the Bank's customer objectives.

* Personal highlights:
> The Turing Way is my first foray into open source and has been a fantastic learning experience.
> Not only have I gained a deeper understanding and appreciation for how GitHub works, but I am also learning to prioritise sustainability and empowerment in the work that I do.
> Although The Turing Way is my first open source project, I thoroughly enjoyed the experience and learned a lot along the way. Before the GSoD program, I only used Github to 'store' my projects. Now, I am much more proficient at using Github for collaborative endeavours and I am more adept at working with tools such as Markdown, Jupyter Book, and Sphinx. In addition, I gained familiarity with setting up and working with web analytics software.
> You can see the full report from GSoD participation [here](https://github.com/alan-turing-institute/the-turing-way/blob/master/communications/GSOD-applications/GSoD-2020-Project-Report.md).
> The BookDash November 2020 was great! It was awesome to meet, collaborate, and share ideas with people from around the world. Beyond the Book Dash, The Turing Way is the very first open-source project I have ever worked on. The experience has been fantastic, and I intend to stick around as a contributor after the Google Season of Docs program ends. I also see myself getting involved in other open-source projects.

* Personal Quote:
> Asides technical skills, I developed a deep appreciation for what working on an open source project entails. My mentors helped me realise that the value I left behind from the GSoD program was not in the amount of work I did, but how I enabled other contributors to also do the work I was doing. As a result, I learned to contribute as a Technical Writer in a manner that was reproducible, sustainable, accessible, and inclusiv

---

### You can also add sections on:

* Pull requests: 
  * Authored:
  * Reviewed:
* Skills/knowledge you developed through The Turing Way
* Outreach or engagement work you undertook for The Turing Way community
  * These could be a social event you facilitated during the Book Dash, post-event blog post you wrote, previous talks/tutorials/training etc you delivered related to The Turing Way...
* Any data science research/practices that have changed and improved as a result of working on The Turing Way

### Who can help?

All Book Dash attendees

### What happens next

- We will use this to add to our report from the event (see https://github.com/the-turing-way/the-turing-way/issues/3520)
- Finally, we will ask for your permission to give you the spotlight in one of our next newsletters

**Comment by NoorhanAbbas** [comment]
Noorhan Abbas
Role:
Google Season of Doc: Technical Writer (2021)
Book Dash Participant (2024)
GitHub id: [[NoorhanAbbas](https://github.com/NoorhanAbbas)]
ORCID: https://orcid.org/0000-0002-1434-6497
Short bio:
I am a Teaching Fellow at the School of Computing, University of Leeds, UK. I instruct two modules in the Online Distance Learning MSc AI programme: Programming for Data Science and Data Mining and Text Analytics. Additionally, I supervise several MSc students' final projects as well as PhD students.

**Comment by chrisdburr** [comment]
Role: Book Dash participant (2024)
GitHub id: @chrisdburr
ORCID: 0000-0003-0386-8182
Short bio: 
I am a Senior Researcher in Trustworthy Systems at the [Alan Turing Institute](https://www.turing.ac.uk/people/researchers/christopher-burr), in the [Tools, Practices, and Systems](https://www.turing.ac.uk/research/research-programmes/tools-practices-and-systems) programme. I also lead the Innovation and Impact Hub for the [Turing’s Research and Innovation Cluster in Digital Twins](https://www.turing.ac.uk/research/research-projects/tric-dt) (TRIC-DT).

Personal highlights:
Hearing about the diversity of contributions made by all the other book dash participants, and being exposed to novel ways to run an online and collaborative session.

Quotes:
It was great to be able to block out time to do this—as always, making time and space for specific pieces of work is really important. Unfortunately, life got in the way on the final day, and I had to miss the share-out to look after my daughter. But I managed to tune in from my phone for a bit of it, and it was great to hear from everyone else.

I didn't finish what I had intended to do, but have made a really solid start and look forward to using the Collaboration Cafes to continue developing the [relevant chapter](https://github.com/the-turing-way/the-turing-way/tree/trustworthy-and-ethical-assurance/book/website/ethical-research/trustworthy-and-ethical-assurance).

**Comment by EstherPlomp** [comment]
Roles:

- Core Team Member, TU-Delft Representative (2020-Present)
- Book Dash Planning Committee (2021-Present), and Working Group member (2023 - Present)
- Book Dash Participant (since 2020)
- GitHub id: [EstherPlomp](https://github.com/estherplomp)
- ORCID: [0000-0003-3625-1357](https://orcid.org/0000-0003-3625-1357)
- Mastodon: [@toothFAIRy](https://scholar.social/@toothFAIRy)

Short bio:

> I’m a Data Steward at the Delft University of Technology, Faculty of Applied Sciences, in the Netherlands, where I support researchers with their data management and open science practices. For my PhD research, I analysed human teeth for their isotopic/chemical composition to say something about human mobility patterns (fields of forensics, archaeology, osteology). Next to the Turing Way I’m also involved with other teams, such as the [Open Research Calendar](https://openresearchcalendar.org/) ([follow the calendar on Twitter!](https://twitter.com/OpenResearchCal)), [IsoArcH](https://isoarch.eu/) and I'm an [OLS](https://openlifesci.org/) mentor/expert/board member. 

Personal highlights:

> Thanks to the Turing Way I really learned how to work collaboratively using GitHub. The book dash in February 2020 was a great kickstart to actually practice and directly apply these skills, which now allows me to contribute more confidently to other projects as well! I primarily contributed to the Reproducible Research Chapter, to the Research Data Management section, and to the Research Infrastructure Roles. I reviewed existing content and I’m working on adding a section on Data Management Plans and how to handle personal data. I also made a [The Turing Way poster](https://doi.org/10.5281/zenodo.4263403) that I presented during a conference. I hope to pay it forward and facilitate others in learning how to work with GitHub through The Turing Way or The Carpentries workshops. I’m very grateful to be part of this great and inclusive community!

> As a Working Group and Planning Committee member I do not focus on content as much as I'd like during Book Dashes. It is a pleasure to work together with the other Committee/Group members and ensure that the Book Dash is an exciting and inspiring event for the participants!

    More information:

> I'm interested in anything related to Open Science and Research Data Management! Please do reach out if you have a nice idea for the Research Data Management chapter in the Turing Way, or if you'd like to collaborate on things! :) I'm also the EU regional coordinator for the [Open Knowledge Foundation](https://okfn.org/en/) - let me know if you would like to become involved in their [Network](https://okfn.org/en/network/)!

**Comment by LizHareDogs** [comment]
Liz Hare
Role: Book Dash participant (2024), Book Dash Organizing June 2024, Fireside Chat co-host Jun 2024
GitHub id: @LizHareDogs 
ORCID: 0000-0002-3978-2543
Short bio:I am a working dog researcher and work to bring open science to dog behavior research through the ManyDogs Project. I work on accessibility and inclusion with the Turing Way.
 ...
Personal highlights:
I am always happy to help organize the Book Dash with attention to accessibility and inclusion. This time I was more focused on hosting three sessions and preparing for the Fireside Chat than book content. The Fireside Chat went well and covered important themes around inclusion of participants from many backgrounds and identities in open science communities and initiatives. It was a great discussion although one panelist could not attend at the last minute. In the future I'd take more time to prepare in advance to make sure there is enough planning for speakers.


More information:
write here ...
The Fireside Chat is described in this issue:
https://github.com/the-turing-way/the-turing-way/issues/3632


Quotes:
Thanks to everyone who helped organize the Book Dash and Fireside Chat!

**Comment by sandygudie** [comment]
Role: Book Dash participant (2024)
GitHub id: @sandygudie
Short bio: I am a fullstack developer and enjoy contributing to open source projects. I contribute to the open science community Saudi Arabia and contribute to the localization effort in the TTW.

Personal highlights:
Thanks to the bookdash, I was able to make a contribution to the localisation of the TTW Handbook.  I got to learn about the challenges andnthe effort to improve the process. I contribute to writing documentation on the history and localization efforts in the TTW so far. it covers the achievements and challenges.

Quotes:
So excited that i learned and met a new friend @amefonaffia

**Comment by mishkanemes** [comment]
**Mishka Nemes**
Role: Book Dash participant (2024), Book Dash Organising Committee member June 2024, GitHub upskilling co-facilitator June 2024
GitHub id: @mishkanemes 
ORCID: n/a
Short bio: I am a researcher working at the intersection of AI & Skills, developing products, programmes and opportunities for folks to learn about AI. I am interested in open science and responsible AI, as well as community building.
Personal highlights: I enjoyed my first book dash as I wore many hats and I could experience it both backend and frontend, so to speak! Whilst we are on track with achieving some set goals around development of new resources for AI educators, I also learnt how to run such collaborative sprints and I feel the knowledge gained from latter is particularly useful as it can be replicated.
Quotes: I particularly cherished the opportunity to peripherally learn what other contributors are up to and to continuously identify opportunities to synergise and collaborate, whilst also having a dedicated space for quiet co-working. And who knew how difficult is to define openness?! Maybe many folks here, I just started asking more questions as I delve deeper, and it's a fun and challenging process.

**Comment by lucyjstephenson** [comment]
Role: Book Dash participant (2024)
GitHub id:  @lucyjstephenson 
ORCID: 0000-0003-2489-7476
Short bio: 
I'm a Scientific Data Coordinator at the Polar Data Centre hosted at the British Antarctic Survey. The Polar Data Centre is part of the NERC Environmental Data Service. I help UK polar scientists throughout the research data lifecycle, from data management planning to making data open access with a DOI. I also work with the other NERC data centres to harmonise policies and processes. My background is as a marine biologist and I have a Code First Girls Data Science qualification. 

Personal highlights:
write here ...
Participating in the first cohort of the TW Practitioner's Hub. Learning how to work collaboratively using GitHub - before I had only collaborated on projects with <5 participants. Hearing from other community members about the ways the TW has helped them professionally. 

More information:
write here ...
I am interested in research data management, collecting data from remote places, data management planning, reusable code publishing, environmental data science 

Quotes:
write here ...
The Turing Way community keeps me coming back - I learn so much from everyone I interact with!

**Comment by SaraVilla** [comment]
**Role:** Book Dash participant (2024)
**GitHub id**: SaraVilla
**ORCID**: https://orcid.org/0000-0001-9502-0888
**Short bio**: I'm a molecular neuroscientist with experience in bioinformatic analysis. I am focusing now in Open Science and how to implement reproducible practices in our analyses.

**Personal highlights**: This year's book dash has been great for me to keep consolidating my GitHub learning. I have finally started shaping myc ontribution to the Mental Health chapter, though it is still in early phases and I hope to keep working on it during Collab cafes and the next Book Dash. I have also identified a potential link with the Hybrid working chapter and are in touch with other collaborators. 

**More information**:
(https://github.com/the-turing-way/the-turing-way/pull/3405#issuecomment-2037542213)

**Quotes**:
Amazing organisation, great experience as always. It is very uplifting and always learning something new from this community. I only hope to someday give it back :)

**Comment by amefonaffia** [comment]
Abasi-amefon Obot Affia

Role: Book Dash participant (2024)
GitHub id: @amefonaffia 
ORCID: 0000-0001-7627-1198
Pull requests: #3730 

Short bio: 
> I am a Security Engineer and a Lecturer in Information Security at the University of Tartu. I am currently focusing my research efforts on hackathons as collaborative learning environments. Generally, I am focusing on collaborative strategies that can bridge the gap between theory and practice in information security and human aspects of cybersecurity.

Personal highlights:
> Biggest highlight is simply attending Book Dash for the first time, having the opportunity to contribute to the Hybrid collaboration chapter and actually finalise current contributions. I had very interesting conversations, revealing impactful intersections of hybrid collaboration with other topics in TTW book, and I hope to continue to work on this Chapter and other Chapters with other collaborators.  I also met new friends at this event too -- S/O to @sandygudie! Very appreciative of the planning and execution of the event and the welcoming and helpful community.

Skills/knowledge you developed through The Turing Way:
> I had been a bit rusty on working collaboratively on Github, so this was a great refresher.

More information:
Interested in continuing with current work on Hybrid collaboration -- Issue #3707 .
I am also interested in all things collaborative that intersect with hackathons or hackathon-like events. Please reach out if there are any research interests on the topic.

**Comment by aranas** [comment]
* Role: Book Dash participant (2024)
* GitHub id: @aranas 
* ORCID: https://orcid.org/0000-0001-9708-7058
* Short bio:
I am a Research Application Manager at the Turing Research and Innovation Cluster in Digital Twins (TRIC:DT). As part of the Innovation and Impact Hub, I work towards open and reproducible computational and social tools around digital twin technology across a range of sectors. My educational background is in cognitive computational neuroscience.
* Personal highlights:
I got to experiment and learn about SEO and website analytics tools which was great. I particularly enjoyed the share-outs at the end of the book dash, it was a fantastic way to end the week with lots of celebrations and feeling inspired by others'
 work.
* Quotes:
The Turing Way community is has this extremely collaborative & supportive spirit, where everyone celebrates each others contributions no matter how big and small. Participating in the book dash for the first time was a wonderful example of this. It really made me experience the uniqueness of this community and the power of team work.

**Comment by luisacutillo78** [comment]
Role: Book Dash participant (2024)
GitHub id: luisacutillo78
ORCID: https://orcid.org/0000-0002-2205-0338
Short bio:

I am an Associate Professor in the Department of  Statistics at the School of Mathematics, University of Leeds and have a very multidisciplinary background. I received my PhD in applied mathematics from the University of Naples “Federico II”. I recently joined the board of director of Women In Machine Learning. My main role at UoL is to be Programme Manager for the following Masters programmes in the School of Mathematics:
Data Science and Analytics MSc Statistics MSc, Statistics with Applications to Finance MSc.
Responsibilities:
Alan Turing Fellow, Leader of the Local DS&AI education Interest group, LITE Fellow
Personal highlights:
This was my first bookdash, it was very inclusive and collaborative and I feel like I want to contribute much more!
Quotes:
I believe that sharing knowledge is the way to grow a better community and the bookdash was a great example of this.

**Comment by aleesteele** [comment]
@all-contributors please add @aranas for content

**Comment by aleesteele** [comment]
@all-contributors please add @NoorhanAbbas for content, ideas

**Comment by aleesteele** [comment]
@all-contributors please add @chrisdburr for ideas, content

**Comment by aleesteele** [comment]
@all-contributors please add @sandygudie for event organising, content, translation

**Comment by aleesteele** [comment]
@all-contributors please add @mishkanemes for event organising, content, review

**Comment by aleesteele** [comment]
@all-contributors please add @lucyjstephenson for ideas, review

**Comment by aleesteele** [comment]
@all-contributors please add @giuliatomba for ideas, content, review

**Comment by aleesteele** [comment]
@all-contributors please add @amefonaffia for ideas, content

**Comment by aleesteele** [comment]
@all-contributors please add @aranas for content, review

**Comment by aleesteele** [comment]
@all-contributors please add @luisacutillo78 for ideas, content
