### ISSUE TITLE
Open Science Meeting 2024: The Turing Way Showcase with facilitated discussion on digital commons and public infrastructure

### ISSUE THREAD

**Issue by malvikasharan** [the-turing-way/the-turing-way#3761]
### Summary

* @malvikasharan and @KirstieJane are attending the Open Science Meeting in Boston (11-14 June) where they will showcase The Turing Way
* Malvika will facilitate a discussion on digital commons and public infrastructure, and how we can build practices and standards to promote that in open source/science projects

### What needs to be done?

- [ ] Notes from the discussion will be added here as comments
- [ ] Folks attending the event can contribute their thoughts here in comment - so that we can add your notes in the book, and if you'd like - also add you as contributors

### Who can help?

* Anyone attending the open science meeting

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by malvikasharan** [comment]
Comment from panel from Kirstie: SAFE-D principles for ethics review -- can this be added in the guide for ethics?

**Comment by malvikasharan** [comment]
@pierrepo would like to write about software archiving

**Comment by aleesteele** [comment]
Hi @malvikasharan - going to close this issue for now, after what sounds like a successful meeting! 💪
