### ISSUE TITLE
The Turing Way Community Forum Planning - 12 July

### ISSUE THREAD

**Issue by aleesteele** [the-turing-way/the-turing-way#3772]
This issue ties to https://github.com/the-turing-way/the-turing-way/issues/3528 and https://github.com/the-turing-way/the-turing-way/issues/3579

* When: 12 July (15:00 - 16:30) - [In your time zone](https://arewemeetingyet.com/London/2024-07-11/15:00)
* How: virtual: https://www.eventbrite.co.uk/e/the-turing-way-community-forum-12-july-tickets-940535355567

- Agenda: https://annuel2.framapad.org/p/turing-way-forum-July-2024

Before: @aleesteele 
- [x] Liaise with Working group Chairs (@da5nsy, @BatoolMM, @LizHareDogs, @EstherPlomp) to get updates (1 slide each: https://docs.google.com/presentation/d/12yZZw56BWYKaRhRUhFe6ikQSdTV2KiB7/edit#slide=id.p1)
- [x] Liaise with a Delivery team meeting the presentation topics and speakers 
- [x] Make a registration page
- [x] Promote the event in our newsletter and social media platforms

One week before:
- [x] Finish the agenda on Framapad (linked above) and share it with working groups and delivery team
- [x] Send a reminder to the working groups and delivery team to request their slide deck
- [x] Promote the event in our newsletter and social media platforms

During Community Call:
- [x] Record the session
- [x] Share the Framapad with the attendees

After the Community Call:
- [x] Review Community Call pluses and deltas
- [x] Community Call debrief
- [x] Upload notes to the governance folder
- [x] Upload the recording on our YouTube Channel 
- [x] Share the recording in our newsletter and social media platforms

### Who can help?

* Working groups
* RCM
* RPM
* Delivery team
* Community members: actively participating and providing feedback about the Community Calls

**Comment by malvikasharan** [comment]
Role of a Community Forum Chair:
- Welcome people
- Housekeeping: 
  - We have Framapad for shared note-taking
  - The Turing Way Code of Conduct applies to the call
  - We want to make sure that you can interact in both written and spoken form, so please edit your name to add S in front of your name to indicate spoken and W to indicate written form of interaction. It will help us to allocate you to the writing room in breakout sessions. 
- Introduce yourself (a slide saying who you are)
- Follow the agenda and timekeeping

Members of the Turing Way will be there to help monitor chat and Framapad notes. You don't have to worry about those - they will flag to you if something needs to be mentioned.

You can watch the recording from a previous call to see what to expect: https://www.youtube.com/watch?v=QFjXbvylGp8

**Comment by aleesteele** [comment]
Flagging here that I will add a script for chairs of the Community Forum that is modeled after the Fireside Chat - which we usually give to each person introducing the community.

**Comment by aleesteele** [comment]
Recording has been uploaded here: https://www.youtube.com/watch?v=h7MTNw1CEE4&t=768s
