### ISSUE TITLE
Question: How did you place the search icon in the article header?

### ISSUE THREAD

**Issue by gradill22** [the-turing-way/the-turing-way#3794]
In my Jupyter Book project, I've been trying to move my search bar from underneath my logo in the primary sidebar to the article header with the page color, GitHub links, etc. How can I replicate this feature? I have not found a single source of documentation on this matter.

**Comment by aleesteele** [comment]
Welcome, @gradill22! We're so glad to have you here. 

I will ping it to @the-turing-way/infrastructure-working-group folks to confirm, but I believe that this is just due to a update for Jupyter Book more broadly 😄

**Comment by sgibson91** [comment]
@gradill22 Anne is right, it's coming from upstream Jupyter Book and we haven't done anything specific to move it around. I recommend asking your question in the Executable Books project https://github.com/orgs/executablebooks/discussions
