### ISSUE TITLE
The upcoming Community Forum - October Planning Issue

### ISSUE THREAD

**Issue by malvikasharan** [the-turing-way/the-turing-way#3815]
**The upcoming Community Forum - October checklist**

Date: ~~3 October~~ Proposed to move to 18 Oct

Register here to attend: [add registration page link].

Related to #3528 
Review notes and tasks remaining from #3772 

## Before the Event 

- [x] Create a planning issue on GitHub  - copy this issue's checklist
- [ ] Set up the Etherpad using a template 
- [x] Create a registration page
- [ ] Create a Zoom link with a waiting room and live transcription enabled. They will also open the call on the day of the event, and give 'co-host rights' to all facilitators to allow them to manage Zoom participants and chats.
- [x] The Turing Way team will define an agenda and invite speakers to the session -  send placeholder calendar invite blocking their calendar for the event (15 mins pre-event tech-check/Green room)
  - [x] Identify the main topics to discuss beyond the WG update from a Governance perspective
- [ ] Reach out to a WG representative who can share updates from WGs on the day
- [ ] Invite a chair from the Maintainers level - debrief them as needed (housekeeping, agenda, introducing speakers) - the team will help with timekeeping, zoom and notes management and helping with breakouts
- [x] Set up a shared doc (slide deck) for all WG members to share updates before the event
- [ ] Coordinate in the maintainer's channel - Community and Project manager
- [x] Identify other presenters who may present or lead a session during the call
- [ ] Add information to the start page
- [ ] Announce at least 3-4 weeks in advance on Slack, Newsletter, Twitter and different talks
- [ ] Update the Turing Way calendar with Zoom, Etherpad and Registration form - and pass it to registered participants

## During the session

- [ ] Open the Zoom call 15 minutes in advance (keep the waiting room of Zoom enabled)
- [ ] Test if speakers' microphone, camera and internet work alright - help troubleshoot any tech challenge
- [ ] Let participants in right on time
- [ ] Welcome them and share Etherpad
- [ ] Remind them that the call will be recorded and that participants can use chat (but may not have the chance to speak during the 60 minutes live)
- [ ] Start recording (on Zoom Cloud) and enable transcription
- [ ] At 5 minutes past, as people join, the person designated to welcome them will introduce the Turing Way, CoC, and Etherpad information and Present the topic
  - [ ] Share agenda
  - [ ]  Record the main room session

## After the session

- [ ] Review Community Call pluses and deltas
- [ ] Community Call debrief
- [ ] Upload notes to the governance folder
- [ ] Download the video from Zoom and edit the live transcription (proofread cc)
- [ ] Upload the video on The Turing Way YouTube - label and annotate well, and add the flyer as the video's front page
- [ ] Share the published videos with the speakers
- [ ] Summarise the session to send an update on Slack and newsletter
- [ ] Promote the video via Slack, Newsletter, Twitter
- [ ] Update the book chapter and templates if needed
- [ ] Add speakers to this GitHub repo using `all-contributions bot` for presentation
- [ ] Close the planning issue as complete!

## Who can help?

- [ ] Working groups - inform them on Slack
- [ ] RCM: @aleesteele 
- [ ] RPM: When in place
- [ ] Community members: actively participating and providing feedback about the Community Calls

**Comment by malvikasharan** [comment]
@aleesteele can you please check and update this Chair's checklist and provide a script based on Fireside chat?

## Copying over from previous issue

Role of a Community Forum Chair:
- Welcome people
- Housekeeping: 
  - We have Framapad for shared note-taking
  - The Turing Way Code of Conduct applies to the call
  - We want to make sure that you can interact in both written and spoken form, so please edit your name to add S in front of your name to indicate spoken and W to indicate written form of interaction. It will help us to allocate you to the writing room in breakout sessions. 
- Introduce yourself (a slide saying who you are)
- Follow the agenda and timekeeping

Members of the Turing Way will be there to help monitor chat and Framapad notes. You don't have to worry about those - they will flag to you if something needs to be mentioned.

You can watch the recording from a previous call to see what to expect: https://www.youtube.com/watch?v=QFjXbvylGp8

**Comment by aleesteele** [comment]
Yep, will do @malvikasharan 👍 - Have you flagged someone to be the chair for the call?

**Comment by aleesteele** [comment]
Adding an introductory script here for the chair: 
>

**Comment by aleesteele** [comment]
_Adding breadcrumbs to #3787_

**Comment by aleesteele** [comment]
Flagging this as closed and completed ✅
