### ISSUE TITLE
[BUG] - link checking CI job

### ISSUE THREAD

**Issue by bsipocz** [the-turing-way/the-turing-way#3816]
We need to either unblock the broken link checking workflow: https://github.com/the-turing-way/the-turing-way/actions/workflows/external_link_check.yml

Or start anew with a new action, and to add something that runs from cron and can be triggered to run in PRs.

**Comment by JimMadge** [comment]
Trying to recall the thinking when I first made the workflow, I believe we decided not to have PRs as a trigger as

- there are a large number of broken link
- false positives are quite common

So we thought the job would be more confusing than helpful.

**Comment by bsipocz** [comment]
Could we just link check the diff for PRs?

**Comment by JimMadge** [comment]
That could be a good idea, I think it would require a new workflow. I think Lychee works on files so you might need to do something like `git diff $target_branch > commit.diff && lychee commit.diff`.

You would still have the problem of false positives though.
