### ISSUE TITLE
 Capturing November 2024 Book Dash Participant's information in the contributors file

### ISSUE THREAD

**Issue by aleesteele** [the-turing-way/the-turing-way#3854]
_**Please don't forget to add your information by 20 November! This will help the organisers to track your contributions throughout the Book Dash period.**_

## Summary

All Book Dash participants (4-8 November 2024) will capture their contributions in this issue.
Info will be copied over to the [Contributors file](https://github.com/the-turing-way/the-turing-way/blob/main/contributors.md). (Participants can directly edit this file and comment below with a PR if they prefer.)

The info will appear after merging in the GitHub repo on [Record of Contributions](https://the-turing-way.netlify.app/afterword/contributors-record.html).

### What needs to be done?

Please make sure that you share your feedback and experience from the last 5 days with us in this document: 

- [ ] Comment below your details in the following format (Paul's bio/details below for example)
- [ ] In your highlight you can also provide links to your issues and PRs

**Template**
---
* Role: Book Dash participant (2024)
* GitHub id: 
* ORCID: 
* Short bio:
> write here ...
* Personal highlights:
> write here ...
* More information:
> write here ...
* Quotes:
> write here ...

**Example**
---
### Paul Owoicho

* Role: 
  * Google Season of Doc: Technical Writer (2021)
  * Book Dash Participant (2021)
* GitHub id: [paulowoicho](http://github.com/paulowoicho)
* ORCID: TBA
* Short bio:
> I am a Technical Writer / Google Season of Docs (GSoD) Participant working to make The Turing Way consistent, sustainable, and accessible.
> I have a BSc in Software Engineering from the American University of Nigeria. Thereafter, I worked as a Research Analyst in the Fintech & Innovation Division of Guaranty Trust Bank, Nigeria and helped to drive the Bank's push to become a platform by creating innovative digital products.
> I completed a Master's in Data Science from the University of Glasgow and starting my PhD in January 2021 studying conversational information-seeking systems. I spent two years as a Research Analyst at Guaranty Trust Bank in Lagos, Nigeria helping to build innovative digital products to meet the Bank's customer objectives.

* Personal highlights:
> The Turing Way is my first foray into open source and has been a fantastic learning experience.
> Not only have I gained a deeper understanding and appreciation for how GitHub works, but I am also learning to prioritise sustainability and empowerment in the work that I do.
> Although The Turing Way is my first open source project, I thoroughly enjoyed the experience and learned a lot along the way. Before the GSoD program, I only used Github to 'store' my projects. Now, I am much more proficient at using Github for collaborative endeavours and I am more adept at working with tools such as Markdown, Jupyter Book, and Sphinx. In addition, I gained familiarity with setting up and working with web analytics software.
> You can see the full report from GSoD participation [here](https://github.com/alan-turing-institute/the-turing-way/blob/master/communications/GSOD-applications/GSoD-2020-Project-Report.md).
> The BookDash November 2020 was great! It was awesome to meet, collaborate, and share ideas with people from around the world. Beyond the Book Dash, The Turing Way is the very first open-source project I have ever worked on. The experience has been fantastic, and I intend to stick around as a contributor after the Google Season of Docs program ends. I also see myself getting involved in other open-source projects.

* Personal Quote:
> Asides technical skills, I developed a deep appreciation for what working on an open source project entails. My mentors helped me realise that the value I left behind from the GSoD program was not in the amount of work I did, but how I enabled other contributors to also do the work I was doing. As a result, I learned to contribute as a Technical Writer in a manner that was reproducible, sustainable, accessible, and inclusiv

---

### You can also add sections on:

* Pull requests: 
  * Authored:
  * Reviewed:
* Skills/knowledge you developed through The Turing Way
* Outreach or engagement work you undertook for The Turing Way community
  * These could be a social event you facilitated during the Book Dash, post-event blog post you wrote, previous talks/tutorials/training etc you delivered related to The Turing Way...
* Any data science research/practices that have changed and improved as a result of working on The Turing Way

### Who can help?

All Book Dash attendees

### What happens next

- We will use this to add to our report from the event (see https://github.com/the-turing-way/the-turing-way/issues/3834)
- Finally, we will ask for your permission to give you the spotlight in one of our next newsletters

**Comment by LizHareDogs** [comment]
Role: Book Dash organizing committee (2024)
GitHub id: @LizHareDogs 
ORCID: 0000-0002-3978-2543 
Short bio: I research genetics, health, and behavior of working dogs. I'm on the Book Dash organizing committee and the co-lead of the Accessibility Working Group. I'm a member of this year's rOpenSci Champions Program cohort.

Personal highlights:
Organizing events, onboarding and planning with new participants, editing accessibility policy ([issue 3145](https://github.com/the-turing-way/the-turing-way/issues/3145)), initiated review of new chapter ([issue 3930](https://github.com/the-turing-way/the-turing-way/issues/3930)), hosting three contribution sessions.

**Comment by seunolufemi123** [comment]
Role: Participant (November 2024)
GitHub: seunolufemi123
ORCID: 0000-0002-8292-2345
Short bio: I am an Open Science enthusiast and OLS (Open Life Science) Resident Fellow. I co-lead the Bioinformatics Outreach Nigeria project to expand bioinformatics capacity through Open Science.

Personal Highlights: I initiated the writing of a new chapter [issues 3885](https://github.com/the-turing-way/the-turing-way/issues/3885) which was reviewed by two individuals, also Interacted with other participants during the book dash event, and participated in the community and shareouts sessions

**Comment by KatrionaGoldmann** [comment]
Role: Participant (November 2024)
GitHub: KatrionaGoldmann
ORCID: 0000-0002-9073-6323
Short bio: I am a research data scientist at the Alan Turing Institute. My current work focuses on using machine learning for biodiversity monitoring, particularly in studying moth populations. Alongside my research and software engineering work, I am committed to fostering best practices in diversity and inclusive hiring within research technical professions.

Personal Highlights: Building connections with participants from varied expertise and interests allowed me to learn from their experiences and engage in meaningful discussions on accessibility and inclusivity. Additionally, the Scriberia session provided a unique way to visualize our ideas, showing how different perspectives could bring new dimensions to our work.

**Comment by Preshh0** [comment]
Role: Book Dash participant (2024)
GitHub id: preshh0
ORCID: 0009-0000-1386-0366
Short bio:
I am an open source manager with a background in community management, and technical writing. My current interests are in accessibility, usability, design, and security. 

Personal highlights:
My personal highlight was giving life to a topic that started from a friend of mine expressing grieviance concerning a design situation and how it affected her. It gave birth to issue [#3930](https://github.com/the-turing-way/the-turing-way/issues/3930), and I got very great feedback to implement to make my topic better. 

Quotes:
Something I learned recently from @aleesteele who learned it from @LizHareDogs: "Nothing about us without us". It's origin, is from this wikipedia page: https://en.wikipedia.org/wiki/Nothing_about_us_without_us.

**Comment by aleesteele** [comment]
@Preshh0, @KatrionaGoldmann, @jyoti-bhogal, @sayalaruano, @seunolufemi123 and @LizHareDogs - thank you so much for logging your contribution information from this book dash! You'll get some pings for me to add you to the contributors list if you haven't been already!
