### ISSUE TITLE
[BUG] broken links for conference materials

### ISSUE THREAD

**Issue by stain** [the-turing-way/the-turing-way#3962]
Github https://github.com/the-turing-way/the-turing-way/blob/main/CONTRIBUTING.md#representing-the-turing-way links to a "conferences/" folder which no longer exists

**Comment by Arielle-Bennett** [comment]
Thanks for flagging @stain, looks like the link needs updating to https://github.com/the-turing-way/conferences 

Adding the Good First Issue label for this as it should be a quick update for someone to make :)

**Comment by chirag1701** [comment]
Hi Arielle . Do let me know if it needs any more corrections !!
