### ISSUE TITLE
Write and review version control chapter 

### ISSUE THREAD

**Issue by r-j-arnold** [the-turing-way/the-turing-way#73]
## Detailed description
 
Write a chapter for the book on version control. This will need to include an explanation of Git and Github. Experience from this issue will likely be used to assist with issue #52 and #53. 

## Issue progress

- [x] Collect pre-written material 
- [x] Shape material into a coherent structure
- [x] Write up a neat chapter
- [x] Get reviews on the chapter
- [x] Edit the chapter following reviews
- [x] Merge to master

**This chapter is being reviewed on pull request #88 to be merged into master.**

**Comment by alexmorley** [comment]
https://rachelcarmena.github.io/2018/12/12/how-to-teach-git.html just posting this because I think the diagrams are beautiful and might be useful to link to or borrow ideas from.
