### ISSUE TITLE
Software documentation chapter

### ISSUE THREAD

**Issue by mkuzak** [the-turing-way/the-turing-way#879]
## Detailed description
 * This issue is a place to discuss matters relating to the writing of the chapter on software documentation.
 * This chapter is being written in _pull_request_number_ (tbd)
 * This chapter is being developed on the _chapter_topic_ branch (tbd)

I would like to migrate Documentation chapter from [eScience Center Guide's Documentation Chapter](https://guide.esciencecenter.nl/#/best_practices/documentation)
Documentation touches many things already covered in other parts of the book. For example README or Code of Conduct are described in the collaboration chapter. The Documentation chapter should cover the description of different kinds of documentation and why it is important and link to other places when it makes more sense.

### Table of contents
  1. About
    - Markdown
  2. Project Documentation
    - README
    - CONTRIBUTING (link to collaboration chapter)
    - ROADMAP
    - CHANGELOG
    - LICENSE
    - Code of Conduct (link to collaboration chapter)
    - how to cite this software (expand section in recognition chapter)
  3. Code Documentation
    - code comments
    - API documentation
    - usage documentation
    - development setup
    - description of issue labels
    - code style (link to review)
    - how to file a bug report
    - software version (there should also be somewhere description of semantic versioning)

### Resources
[eScience Center Guide's Documentation Chapter](https://guide.esciencecenter.nl/best_practices/documentation.html)
[Mozilla Open Leadership Training Series](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/)

## Current status
This chapter is empty. If anyone would like to collaborate on that, they are welcome.

 - [ ] Write chapter outline
 - [ ] Add material to the chapter
 - [ ] Combine materials into a readable chapter
 - [ ] Proofread
 - [ ] Request reviews
 - [ ] Address reviews
 - [ ] Merge to master branch.

## Updates
no updates yet

**Comment by FrancesMadden** [comment]
I added in some info about software citation - let me know what you think!

**Comment by sofievdbos** [comment]
Some additional options for: [WIP]
3. Code Documentation
- installation guideline (Windows/Mac/Linux)
- dependencies as a [badge](https://shields.io/) + incorporated installation guide
- development setup: create a _-dev_ branch
- software version as a [badge](https://shields.io/) + under _releases_

**Comment by sofievdbos** [comment]
--> several README.md templates with relevant items to implement: [_WIP_]  
https://gist.github.com/fvcproductions/1bfc2d4aecb01a834b46 
https://gist.github.com/PurpleBooth/109311bb0361f32d87a2 
https://github.com/othneildrew/Best-README-Template 
https://github.com/dbader/readme-template 
https://github.com/matiassingers/awesome-readme

**Comment by sgibson91** [comment]
Hey folks! 👋I've also been thinking a lot about documentation recently and @malvikasharan suggested that I drop in on your issue. It looks like you have made a great on the kinds of things that a well-documented project needs!

The aspect of documentation I've been thinking about is "what makes _good_ documentation?". For example, it's all well and good having extensive API documentation but if it's overwhelming, confusing and unreadable then it serves the same purpose as no documentation at all. I'm interested in addressing things like:

- Style and tone of docs
- Making sure documentation doesn't have (too many) abbreviations that need to be looked up by the reader
- Link out to docs/resources/tutorials of any tools that are dependencies of the project
- Provide an easily digestable overview of the project so diving into the more in depth stuff doesn't feel so overwhelming
- Giving short examples/tutorials of what to expect from the project
- Providing a "Getting Started" guide that is simple and works

What do you think?

**Comment by sverhoeven** [comment]
I agree that API documentation can be overwhelming and different documentation is needed for different purposes. I really like the  modes of documentation explained on https://diataxis.fr/ .

**Comment by bouweandela** [comment]
I was quite surprised to find that there is no chapter on documentation in The Turing way yet, it would be good do start working on having at least something soon.
